### ISSUE TITLE
Ubuntu 16.04 - PPA: After last update Cura behave like a fresh install

### ISSUE THREAD

**Issue by BerndJM** [Ultimaker/Cura#1098]
@thopiekar 
Since the todays update Cura "greets" after startup with the "Add printer" dialog.
Even in this dialog my custom printer isn't present.
Had a look in .local/share/cura - all my definitions are there. Seems like cura ignores the definitions in this place ?!? Any idea what's going wrong here?

**Comment by thopiekar** [comment]
Which printer do you own?

**Comment by BerndJM** [comment]
It's a Velleman K8200 - and worked fine with my definitions all the time 'til today

**Comment by thopiekar** [comment]
@Ghostkeeper has this printer been removed? 🤔 
@BerndJM I can find your printer neither in the "2.3" branch nor in the "master" branch. Was this definition you own? One you've created and copied somewhere?

**Comment by BerndJM** [comment]
I've created the definition on base of the custom FDM printer

**Comment by thopiekar** [comment]
Where was it copied to? Is it still there?

**Comment by BerndJM** [comment]
As I wrote above:
Had a look in .local/share/cura - all my definitions are there

**Comment by BerndJM** [comment]
[local-share-cura.zip](https://github.com/Ultimaker/Cura/files/564677/local-share-cura.zip)

**Comment by thopiekar** [comment]
`k8200.def.json` ? Never added a custom definition this way, but I'm sure @Ghostkeeper can help with that.
Alternatively you can try moving your file to /usr/share/cura/resources/definitions/ as root.
This directory really has to work as all the other defintions are there..
(the path might be incorrect, as I'm on Windows at the moment to work on something...)

Good luck 😉
.. Ah, and don't forget to share your definition if it works. I'm sure other Velleman K8200 users might find it useful 😃

**Comment by thopiekar** [comment]
Btw. the log might be useful here, too. Maybe Cura already says what is hurting here..

**Comment by BerndJM** [comment]
O.k. the strange thing: it worked 'til yesterday without any problems.
Here is the log from the last start:
[cura.log.zip](https://github.com/Ultimaker/Cura/files/564695/cura.log.zip)

**Comment by mgroene** [comment]
I was just running into this problem, too. Windows 7, Cura 2.3 setting up from scratch.
I can't reproduce reliable, but if I use german umlauts in the material profile e.g. for the name/color, everything seems to be gone at the next restart.

**Comment by BerndJM** [comment]
In addition:
I played around a bit more
- placing my printer definition in /usr/share/cura/resources/definitions/ gives me the possibility to select it under "Others"
- but Cura didn't remember this - after closing and reopening, there is again the "Add printer" dialog
- even if I choose a different printer (to be sure it's not caused by my def file) - the same behavior.

It looks like Cura didn't read the config file in ".config/cura" and/or the files in ".local/share/cura" at startup. The files have full read/write access. And Cura writes also to the files e.g. if I choose another printer ... strange ?!?

**Comment by mgroene** [comment]
okay, indeed there seems to be problems with utf8 or some unicode-things. see logs:
```
2016-11-01 22:08:00,850 - INFO - C:\Program Files\Cura 2.3\plugins\UpdateChecker\UpdateChecker.py (run [28]): Checking for new version of cura
2016-11-01 22:08:00,866 - INFO - D:\2.3\build\inst\lib\python3.4\site-packages\UM\PluginRegistry.py (loadPlugin [63]): Loaded plugin USBPrinting
2016-11-01 22:08:00,881 - INFO - D:\2.3\build\inst\lib\python3.4\site-packages\UM\PluginRegistry.py (loadPlugin [63]): Loaded plugin VersionUpgrade21to22
2016-11-01 22:08:00,897 - INFO - D:\2.3\build\inst\lib\python3.4\site-packages\UM\PluginRegistry.py (loadPlugin [63]): Loaded plugin SimpleView
2016-11-01 22:08:00,897 - INFO - D:\2.3\build\inst\lib\python3.4\site-packages\UM\PluginRegistry.py (loadPlugin [63]): Loaded plugin WireframeView
2016-11-01 22:08:00,913 - INFO - D:\2.3\build\inst\lib\python3.4\site-packages\UM\PluginRegistry.py (loadPlugin [63]): Loaded plugin X3DReader
2016-11-01 22:08:00,928 - INFO - D:\2.3\build\inst\lib\python3.4\site-packages\UM\PluginRegistry.py (loadPlugin [63]): Loaded plugin XmlMaterialProfile
2016-11-01 22:08:00,944 - INFO - D:\2.3\build\inst\lib\python3.4\site-packages\UM\PluginRegistry.py (loadPlugin [63]): Loaded plugin XRayView
2016-11-01 22:08:00,944 - INFO - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\QtApplication.py (__init__ [39]): Command line arguments: {'debug-mode': False, 'external-backend': False, 'disable-textures': False, 'file': []}
2016-11-01 22:08:00,960 - INFO - D:\2.3\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py (upgrade [98]): Looking for old configuration files to upgrade.
2016-11-01 22:08:01,022 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_logSocketState [165]): Socket state changed to Listening
2016-11-01 22:08:01,022 - INFO - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (startEngine [55]): Started engine process: C:\Program Files\Cura 2.3\CuraEngine.exe
2016-11-01 22:08:01,022 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] Calling engine with: ['C:\\Program Files\\Cura 2.3\\CuraEngine.exe', 'connect', '127.0.0.1:49674', '-j', 'C:\\Program Files\\Cura 2.3\\resources\\definitions\\fdmprinter.def.json', '']
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] 
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] Cura_SteamEngine version DEV
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] Copyright (C) 2014 David Braam
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] 
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] This program is free software: you can redistribute it and/or modify
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] it under the terms of the GNU Affero General Public License as published by
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] the Free Software Foundation, either version 3 of the License, or
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] (at your option) any later version.
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] 
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] This program is distributed in the hope that it will be useful,
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] but WITHOUT ANY WARRANTY; without even the implied warranty of
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] GNU Affero General Public License for more details.
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] 
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] You should have received a copy of the GNU Affero General Public License
2016-11-01 22:08:01,038 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_backendLog [88]): [Backend] along with this program.  If not, see <http://www.gnu.org/licenses/>.
2016-11-01 22:08:01,053 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_logSocketState [165]): Socket state changed to Connected
2016-11-01 22:08:01,053 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Backend\Backend.py (_onSocketStateChanged [155]): Backend connected on port 49674
2016-11-01 22:08:01,318 - DEBUG - C:\Program Files\Cura 2.3\plugins\MachineSettingsAction\MachineSettingsAction.py (_onContainerAdded [40]): Not attaching MachineSettingsAction to ultimaker2_plus; Machines that use variants are not supported
2016-11-01 22:08:01,506 - DEBUG - C:\Program Files\Cura 2.3\plugins\MachineSettingsAction\MachineSettingsAction.py (_onContainerAdded [40]): Not attaching MachineSettingsAction to ultimaker_original_dual; Multi-extrusion printers are not supported
2016-11-01 22:08:01,552 - DEBUG - C:\Program Files\Cura 2.3\plugins\MachineSettingsAction\MachineSettingsAction.py (_onContainerAdded [40]): Not attaching MachineSettingsAction to ultimaker3; Multi-extrusion printers are not supported
2016-11-01 22:08:01,802 - DEBUG - C:\Program Files\Cura 2.3\plugins\MachineSettingsAction\MachineSettingsAction.py (_onContainerAdded [40]): Not attaching MachineSettingsAction to ultimaker3_extended; Multi-extrusion printers are not supported
2016-11-01 22:08:02,036 - DEBUG - C:\Program Files\Cura 2.3\plugins\MachineSettingsAction\MachineSettingsAction.py (_onContainerAdded [40]): Not attaching MachineSettingsAction to ultimaker2_extended_plus; Machines that use variants are not supported
2016-11-01 22:08:12,789 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]): Exception: Could not deserialize container generic_pla #2
2016-11-01 22:08:12,789 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]): Traceback (most recent call last):
2016-11-01 22:08:12,789 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]):   File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Settings\ContainerRegistry.py", line 238, in load
2016-11-01 22:08:12,789 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]):   File "C:\Python34\lib\codecs.py", line 319, in decode
2016-11-01 22:08:12,789 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]): UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 238: invalid start byte
2016-11-01 22:08:13,907 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Settings\ContainerStack.py (deserialize [229]): While deserializing, we got the following container string: ultimaker_original_dual_2nd #2_current_settings,empty_quality_changes,normal,generic_pla,empty_variant,ultimaker_original_dual_2nd,
2016-11-01 22:08:13,911 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Settings\ContainerStack.py (deserialize [229]): While deserializing, we got the following container string: ultimaker_original_dual_1st #2_current_settings,empty_quality_changes,normal,generic_pla #2,empty_variant,ultimaker_original_dual_1st,
2016-11-01 22:08:13,911 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]): Exception: Could not deserialize container ultimaker_original_dual_1st #2
2016-11-01 22:08:13,913 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]): Traceback (most recent call last):
2016-11-01 22:08:13,913 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]):   File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Settings\ContainerRegistry.py", line 238, in load
2016-11-01 22:08:13,913 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]):   File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Settings\ContainerStack.py", line 256, in deserialize
2016-11-01 22:08:13,913 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]): Exception: When trying to deserialize ultimaker_original_dual_1st #2, we received an unknown ID (generic_pla #2) for container
2016-11-01 22:08:13,915 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Settings\ContainerStack.py (deserialize [229]): While deserializing, we got the following container string: Prusa i3 Mk2_current_settings,empty_quality_changes,normal,generic_pla #2,Prusa i3 Mk2_variant,prusa_i3_mk2,
2016-11-01 22:08:13,917 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]): Exception: Could not deserialize container Prusa i3 Mk2
2016-11-01 22:08:13,917 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]): Traceback (most recent call last):
2016-11-01 22:08:13,917 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]):   File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Settings\ContainerRegistry.py", line 238, in load
2016-11-01 22:08:13,917 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]):   File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Settings\ContainerStack.py", line 256, in deserialize
2016-11-01 22:08:13,918 - ERROR - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Logger.py (logException [53]): Exception: When trying to deserialize Prusa i3 Mk2, we received an unknown ID (generic_pla #2) for container
2016-11-01 22:08:13,921 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Settings\ContainerStack.py (deserialize [229]): While deserializing, we got the following container string: Ultimaker Original Dual Extrusion_current_settings,empty_quality_changes,normal,generic_pla,empty_variant,ultimaker_original_dual,
2016-11-01 22:08:13,927 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Controller.py (setActiveView [80]): Setting active view to SolidView
2016-11-01 22:08:14,753 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\Bindings\Theme.py (load [118]): Loading theme file: C:\Program Files\Cura 2.3\resources\themes\cura\theme.json
2016-11-01 22:08:14,851 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\Bindings\Theme.py (load [118]): Loaded theme C:\Program Files\Cura 2.3\resources\themes\cura
2016-11-01 22:08:14,914 - CRITICAL - D:\2.3\build\inst\lib\python3.4\site-packages\cura\CrashHandler.py (show [24]): An uncaught exception has occurred!
2016-11-01 22:08:14,914 - CRITICAL - D:\2.3\build\inst\lib\python3.4\site-packages\cura\CrashHandler.py (show [24]): TypeError: unable to convert a Python 'str' object to a C++ 'bool' instance
2016-11-01 22:08:14,917 - WARNING - D:\2.3\build\inst\lib\python3.4\site-packages\cura\Settings\ContainerManager.py (getContainerMetaDataEntry [171]): Could not get metadata of container  because it was not found.
2016-11-01 22:08:14,917 - CRITICAL - D:\2.3\build\inst\lib\python3.4\site-packages\cura\CrashHandler.py (show [24]): An uncaught exception has occurred!
2016-11-01 22:08:14,917 - CRITICAL - D:\2.3\build\inst\lib\python3.4\site-packages\cura\CrashHandler.py (show [24]): TypeError: unable to convert a Python 'str' object to a C++ 'bool' instance
2016-11-01 22:08:15,309 - DEBUG - C:\Program Files\Cura 2.3\plugins\OctoPrintPlugin\DiscoverOctoPrintAction.py (_createAdditionalComponentsView [143]): Creating additional ui components for OctoPrint-connected printers.
2016-11-01 22:08:15,313 - DEBUG - C:\Program Files\Cura 2.3\plugins\UM3NetworkPrinting\DiscoverUM3Action.py (_createAdditionalComponentsView [133]): Creating additional ui components for UM3.
2016-11-01 22:08:15,615 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\GL\QtOpenGL.py (__init__ [19]): Initialized OpenGL subsystems.
2016-11-01 22:08:15,617 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\GL\QtOpenGL.py (__init__ [19]): OpenGL Version:  3.3.0
2016-11-01 22:08:15,617 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\GL\QtOpenGL.py (__init__ [19]): OpenGL Vendor:   NVIDIA Corporation
2016-11-01 22:08:15,617 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\GL\QtOpenGL.py (__init__ [19]): OpenGL Renderer: GeForce 210/PCIe/SSE2
2016-11-01 22:08:25,770 - DEBUG - C:\Program Files\Cura 2.3\plugins\AutoSave\AutoSave.py (_onTimeout [46]): Autosaving preferences, instances and profiles
2016-11-01 22:13:29,965 - DEBUG - D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\QtApplication.py (windowClosed [197]): Shutting down cura
2016-11-01 22:13:31,224 - DEBUG - C:\Program Files\Cura 2.3\plugins\CuraEngineBackend\CuraEngineBackend.py (_terminate [186]): Attempting to kill the engine process
2016-11-01 22:13:31,225 - DEBUG - C:\Program Files\Cura 2.3\plugins\CuraEngineBackend\CuraEngineBackend.py (_terminate [186]): Killing engine process
2016-11-01 22:13:31,233 - DEBUG - C:\Program Files\Cura 2.3\plugins\CuraEngineBackend\CuraEngineBackend.py (_terminate [186]): Engine process is killed. Received return code 1
```

**Comment by Ghostkeeper** [comment]
I've been running into the same problem the past few days too. It just seemed to delete my printers. I couldn't pinpoint it though, and maybe it was just because of me switching between master and 2.3. Nobody else seemed to run into it. So I held off with creating an issue about it until I could find reliable reproduce steps.

There was a Velleman definition coming in via a pull request: https://github.com/Ultimaker/Cura/pull/1079
It isn't accepted yet though, and it seems to be a different printer. The pull request isn't accepted yet mainly because of a syntax error in the definition.

**Comment by Ghostkeeper** [comment]
As for the other question, if you put definitions in `~/.local/share/cura/definitions`, it should load just like any other definition. But the `definitions` subfolder doesn't exist by default, so you might have to create it.

**Comment by Ghostkeeper** [comment]
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 238: invalid start byte

Highlighting this. We recently changed some things in the saving to more reliably use UTF-8 everywhere regardless of system preferences. The series of commits to do this was these:
* https://github.com/Ultimaker/Cura/commit/bfec96f58425517cb89fa91d4c41a085fa515c70
* https://github.com/Ultimaker/Uranium/commit/c976a275f4dc7daaf0cbed69a2f890029048372d
* https://github.com/Ultimaker/Uranium/commit/5e45e969fe0d14c3553e58e7b7b178b14af5a5d9
* https://github.com/Ultimaker/Uranium/commit/0f7ecc1b5bb576bf9c9feee649a7c781d2b88f01
* https://github.com/Ultimaker/Uranium/commit/49e6e67dd4e430e834c250af25cdf25c4c40d2c3
* https://github.com/Ultimaker/Uranium/commit/5502a4cb418f4846eb68cf89e060ece963541817

We might have missed a place to use UTF-8.

**Comment by BerndJM** [comment]
Yes the Velleman Vertex K8400 is a different printer.
And about the `~/.local/share/cura/definitions` - I know this and it worked the whole time fine 'til today.
Out of courisity just switched between "master" and "stable" but the behavior is the same. All time on startup comes the "Add printer" dialog - as said before it looks like Cura didn't read the config folder at startup ...

**Comment by thopiekar** [comment]
@Ghostkeeper Can confirm the same behaviour here on master. :disappointed:

**Comment by mgroene** [comment]
Additionally I want to mention, that filenames of Definitions in the config path contain some utf8codes. Dont know whether this is intended or should ne striped off, so i just leave the Note.

**Comment by awhiemstra** [comment]
I pulled master yesterday and suddenly saw the not-saving behaviour. It seems something recent broke things.

**Comment by BerndJM** [comment]
Looked a bit around in the sources for changes in the last days, and think I found the reason let Cura ignoring the configuration:
https://github.com/Ultimaker/Uranium/commit/ba1a3d7b66ed46a89b6045e635bf2ce44c59d221
Reverted the changes there and all seems to work fine.
Can someone please check and confirm this?

@mgroene:
I'm seriously wondering why you hijack a Linux/Ubuntu related thread with your windows/utf-8 issues ?!?

**Comment by thopiekar** [comment]
I'm not sure, but I guess that is has been solved now.
At least I don't see that problem here anymore, neither on [2.3] nor in [master].

**Comment by awhiemstra** [comment]
Yes, I fixed it with https://github.com/Ultimaker/Uranium/commit/f8594982b720d33eac206b0be1f5d7b5ef6bccf8 . Forgot to mention it here.

**Comment by thopiekar** [comment]
@awhiemstra Thanks :smile:
