### ISSUE TITLE
Module use of python34.dll conflicts with this version of Python.

### ISSUE THREAD

**Issue by Zeroxus** [Ultimaker/Cura#1133]
Hi,I use anaconda3 with Python3.5.You updated the python version of the project the day before yesterday.But I have encountered some problems in compiling this project today.As follows:

    Traceback (most recent call last):
    File "setup_win32.py", line 6, in <module>
    import UM
    File "C:\Users\Zeroxus\Anaconda3\lib\site-packages\UM\__init__.py", line 9, in <module>
    from .Application import Application
    File "C:\Users\Zeroxus\Anaconda3\lib\site-packages\UM\Application.py", line 17, in <module>
    from UM.Preferences import Preferences
    File "C:\Users\Zeroxus\Anaconda3\lib\site-packages\UM\Preferences.py", line 8, in <module>
    from UM.MimeTypeDatabase import MimeTypeDatabase, MimeType #To register the MIME type of the    preference file.
    File "C:\Users\Zeroxus\Anaconda3\lib\site-packages\UM\MimeTypeDatabase.py", line 4, in <module>
    from PyQt5.QtCore import QMimeDatabase
    ImportError: Module use of python34.dll conflicts with this version of Python.
    CMakeFiles\build_exe.dir\build.make:56: recipe for target 'build_exe' failed
    mingw32-make[2]: *** [build_exe] Error 1
    CMakeFiles\Makefile2:637: recipe for target 'CMakeFiles/build_exe.dir/all' failed
    mingw32-make[1]: *** [CMakeFiles/build_exe.dir/all] Error 2
    makefile:148: recipe for target 'all' failed
    mingw32-make: *** [all] Error 2
what could I do to fix this? thanks!

**Comment by sedwards2009** [comment]
Is your %PYTHONPATH% correct?
