### ISSUE TITLE
TypeError: unable to convert a Python 'float' object to a C++ 'int' instance

### ISSUE THREAD

**Issue by bjornpijnacker** [Ultimaker/Cura#11525]
### Application Version

4.13.1-1

### Platform

Arch Linux 5.16.10-arch1-1; NVIDIA GTX 1650 GPU

### Printer

Ender 3 Max w/ Octoprint

### Reproduction steps

Sliced a model and clicked "print with Octoprint"

### Actual results

Cura crashes, with the following log entries:

```
2022-02-22 15:00:42,528 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2022-02-22 15:00:42,528 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: TypeError: unable to convert a Python 'float' object to a C++ 'int' instance
2022-02-22 15:00:42,542 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2022-02-22 15:00:42,542 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: TypeError: unable to convert a Python 'float' object to a C++ 'int' instance
2022-02-22 15:00:42,545 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2022-02-22 15:00:42,545 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: TypeError: unable to convert a Python 'float' object to a C++ 'int' instance
2022-02-22 15:00:42,548 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2022-02-22 15:00:42,548 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: TypeError: unable to convert a Python 'float' object to a C++ 'int' instance
```

### Expected results

Cura doesn't crash

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

Not including a project file, since this happens with almost any project.

Related log entries that do not crash Cura is the following exception:
```
2022-02-22 14:58:55,467 - DEBUG - [MainThread] UM.Operations.OperationStack.push [72]: <UM.Operations.AddSceneNodeOperation.AddSceneNodeOperation object at 0x7fdfec740670>, took 0ms
2022-02-22 14:58:55,468 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]: Exception: Failed to arrange the models
2022-02-22 14:58:55,468 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]: Traceback (most recent call last):
2022-02-22 14:58:55,468 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:   File "/usr/lib/python3.10/site-packages/cura/CuraApplication.py", line 1947, in _readMeshFinished
2022-02-22 14:58:55,468 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:     arrange(nodes_to_arrange, self.getBuildVolume(), fixed_nodes)
2022-02-22 14:58:55,468 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:   File "/usr/lib/python3.10/site-packages/cura/Arranging/Nest2DArrange.py", line 160, in arrange
2022-02-22 14:58:55,469 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:     grouped_operation, not_fit_count = createGroupOperationForArrange(nodes_to_arrange, build_volume, fixed_nodes, fa
ctor, add_new_nodes_in_scene)
2022-02-22 14:58:55,469 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:   File "/usr/lib/python3.10/site-packages/cura/Arranging/Nest2DArrange.py", line 119, in createGroupOperationForArran
ge
2022-02-22 14:58:55,469 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:     found_solution_for_all, node_items = findNodePlacement(nodes_to_arrange, build_volume, fixed_nodes, factor)
2022-02-22 14:58:55,469 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:   File "/usr/lib/python3.10/site-packages/cura/Arranging/Nest2DArrange.py", line 43, in findNodePlacement
2022-02-22 14:58:55,469 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:     build_plate_bounding_box = Box(machine_width * factor, machine_depth * factor)
2022-02-22 14:58:55,469 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]: TypeError: Box(): arguments did not match any overloaded call:
2022-02-22 14:58:55,469 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:   overload 1: argument 1 has unexpected type 'float'
2022-02-22 14:58:55,469 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:   overload 2: argument 1 has unexpected type 'float'
2022-02-22 14:58:55,470 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:   overload 3: argument 1 has unexpected type 'float'
2022-02-22 14:58:55,470 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:   overload 4: argument 1 has unexpected type 'float'
2022-02-22 14:58:55,470 - ERROR - [MainThread] cura.CuraApplication._readMeshFinished [1949]:   overload 5: argument 1 has unexpected type 'float'
```

Complete session log file is attached:
[cura-excerpt.log](https://github.com/Ultimaker/Cura/files/8117266/cura-excerpt.log)

**Comment by Ghostkeeper** [comment]
This is an issue when using Python 3.10 (Cura 4.13 used Python 3.8, so it is not expected to work with other Python versions). We encountered this ourselves too when we upgraded to Python 3.10. The issue was fixed here for the next release, which will require Python 3.10: https://github.com/Ultimaker/Cura/commit/652043e1d8599460ecf2612042587c46217ef2eb
