### ISSUE TITLE
Unrecoverable Error on Cura 5 startup

### ISSUE THREAD

**Issue by msteele999** [Ultimaker/Cura#11922]
### Application Version

5.0.0-beta+1

### Platform

Windows 10

### Printer

None

### Reproduction steps

1. Installed Beta version
2. Attempted to start the program

### Actual results

Error Windows presented

### Expected results

Program would start

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Snag_1f3afad](https://user-images.githubusercontent.com/6474337/164949330-3e76f2fa-0031-4c23-aca1-324875277c10.png)

Error Traceback:

Traceback (most recent call last):
  File "cura_app.py", line 238, in <module>
  File "cura\CuraApplication.py", line 813, in run
    super().run()
  File "UM\Qt\QtApplication.py", line 366, in run
    super().run()
  File "UM\Application.py", line 256, in run
    self.initialize()
  File "cura\CuraApplication.py", line 323, in initialize
    self.__sendCommandToSingleInstance()
  File "cura\CuraApplication.py", line 339, in __sendCommandToSingleInstance
    if self._single_instance.startClient():
  File "cura\SingleInstance.py", line 32, in startClient
    if single_instance_socket.state() != QLocalSocket.ConnectedState:
AttributeError: type object 'QLocalSocket' has no attribute 'ConnectedState'

Logs:

Thread 0x00000578 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004ba8 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002b34 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004958 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003974 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004b08 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004260 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002228 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003978 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000e2c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002960 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003a4c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Current thread 0x000042d8 (most recent call first):
  File "cura\CrashHandler.py", line 396 in _logInfoWidget
  File "cura\CrashHandler.py", line 182 in _createDialog
  File "cura\CrashHandler.py", line 86 in __init__
  File "cura_app.py", line 176 in exceptHook

**Comment by msteele999** [comment]
Using the Reset Configuration and then running as Administrator seemed to resolve the issue.

**Comment by nallath** [comment]
Fixed that in https://github.com/Ultimaker/Cura/commit/c1ed7b97f9e5083c2571d60d2e1a031ee48fd9ca

Note that you would only need to delete the preferences file for this to work as a workaround.
