### ISSUE TITLE
Cura 5.0 Wont Run on MacOS 10.14.6

### ISSUE THREAD

**Issue by chappy1978** [Ultimaker/Cura#12452]
### Application Version

5.0

### Platform

MacOS

### Printer

CR10S Pro

### Reproduction steps

I downloaded a new copy from Ultimaker's website. Then dropped it into the Applications folder. When I open the file the first time it does the security check, other times after that it doesn't run at all. What I found in the console.app is that Cura has been built to run on 10.15 and above. The log is in the additional section.

### Actual results

Nothing happens

### Expected results

Cura should open.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Failed to execute script 'cura_app' due to unhandled exception: dlopen(/Applications/Ultimaker-Cura.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /Applications/Ultimaker-Cura.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /Applications/Ultimaker-Cura.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so

Traceback:
Traceback (most recent call last):
  File "cura_app.py", line 27, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cura/CrashHandler.py", line 27, in <module>
    from UM.Application import Application
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "UM/Application.py", line 9, in <module>
    from UM.Controller import Controller
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "UM/Controller.py", line 3, in <module>
    from UM.Scene.Iterator.DepthFirstIterator import DepthFirstIterator
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "UM/Scene/Iterator/DepthFirstIterator.py", line 3, in <module>
    from UM.Scene.SceneNode import SceneNode
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "UM/Scene/SceneNode.py", line 14, in <module>
    from UM.Mesh.MeshBuilder import MeshBuilder
  File "PyInstaller/loader/pyimod03_im<…>

**Comment by plusline-morland** [comment]
"From version 5.0 onwards - Ultimaker Cura is only supported on operating systems actively maintained by their software manufacturer or community. This means Windows 7 and MacOS 10.14 will no longer be supported.
Ubuntu 18.04 is also no longer supported because of the update to Qt6."
Source: https://github.com/Ultimaker/Cura/releases
