### ISSUE TITLE
Exception: Error loading plugin ConsoleLogger

### ISSUE THREAD

**Issue by frank-pian** [Ultimaker/Cura#12911]
### Application Version

lastest

### Platform

ubuntu 20.04

### Printer

_

### Reproduction steps

According to the build document: https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source

1.
pip install conan --upgrade
conan config install https://github.com/ultimaker/conan-config.git
conan profile new default --detect --force
2.
conan remote remove cura
3.
conan install . cura/5.1.0-beta@ultimaker/stable --build=missing --update -o cura:devtools=True -g VirtualPythonEnv
4.
source venv/bin/activate
5.
python cura_app.py

### Actual results

start the app

### Expected results

```
frank@ubuntu:~/project/cura_dev/Cura$ python cura_app.py
/home/frank/.conan/data/uranium/5.1.0/_/_/package/e0048d903da3f6245f7e22f0b7132b2aa5f5826c/site-packages/UM/PluginRegistry.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
[MainThread] UM.Application.initialize [161]: Initializing Ultimaker Cura
[MainThread] UM.Application.initialize [162]: App Version 5.1.0-beta
[MainThread] UM.Application.initialize [163]: Api Version 8.1.0
[MainThread] UM.Application.initialize [164]: Build type None
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/Cura/venv/bin/share/uranium/plugins must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/Cura/venv/bin/share/cura/plugins must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/lib/uranium must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/lib64/uranium must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/lib32/uranium must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/Cura/venv/bin/plugins must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/Resources/uranium/plugins must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/Resources/cura/plugins must be a folder.
[MainThread] UM.Resources.__initializeStoragePaths [481]: Initializing storage paths
[MainThread] UM.Resources.__initializeStoragePaths [491]: Config storage path is /home/frank/.config/cura/5.1
[MainThread] UM.Resources.__initializeStoragePaths [499]: Data storage path is /home/frank/.local/share/cura/5.1
[MainThread] UM.Resources.__initializeStoragePaths [511]: Cache storage path is /home/frank/.cache/cura/5.1
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/.conan/data/uranium/5.1.0/_/_/package/e0048d903da3f6245f7e22f0b7132b2aa5f5826c/site-packages/UM/../plugins must be a folder.
[MainThread] UM.Qt.QtApplication.initialize [163]: Preferences file not found, ignore and use default language 'en_US'
[MainThread] UM.PackageManager.__init__ [56]: Found bundled packages JSON file: /home/frank/project/cura_dev/Cura/cura/../resources/bundled_packages/cura.json
[MainThread] UM.PackageManager.__init__ [56]: Found bundled packages JSON file: /home/frank/.conan/data/uranium/5.1.0/_/_/package/e0048d903da3f6245f7e22f0b7132b2aa5f5826c/site-packages/UM/../../resources/bundled_packages/uranium.json
[MainThread] UM.View.GL.OpenGLContext.detectBestOpenGLVersion [124]: Trying OpenGL context 4.1...
[MainThread] UM.View.GL.OpenGLContext.detectBestOpenGLVersion [132]: Yay, we got at least OpenGL 4.1 core: 4.1 Core profile
[MainThread] UM.Qt.QtApplication.initialize [191]: Detected most suitable OpenGL context version: 4.1 Core profile
[MainThread] UM.Qt.QtApplication.initialize [198]: Initializing job queue ...
[MainThread] UM.Qt.QtApplication.initialize [202]: Initializing version upgrade manager ...
[MainThread] UM.PackageManager._loadManagementData [174]: Loaded bundled packages data from /home/frank/project/cura_dev/Cura/cura/../resources/bundled_packages/cura.json
[MainThread] UM.PackageManager._loadManagementData [174]: Loaded bundled packages data from /home/frank/.conan/data/uranium/5.1.0/_/_/package/e0048d903da3f6245f7e22f0b7132b2aa5f5826c/site-packages/UM/../../resources/bundled_packages/uranium.json
[MainThread] UM.PackageManager._loadManagementData [203]: User package management file /home/frank/.local/share/cura/5.1/packages.json doesn't exist, do nothing
[MainThread] UM.PackageManager._removeAllScheduledPackages [280]: Attempting to remove the following scheduled packages: - 
[MainThread] UM.PluginRegistry.initializeBeforePluginsAreLoaded [121]: Loading plugin configuration file '/home/frank/.config/cura/5.1/plugins.json'
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/lib/cura must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/lib64/cura must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/libx32/cura must be a folder.
[MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location /home/frank/project/cura_dev/lib32/cura must be a folder.
[MainThread] UM.PluginRegistry.removeCorruptedPluginMessage [529]: Exception: Error loading plugin ConsoleLogger:
[MainThread] UM.PluginRegistry.removeCorruptedPluginMessage [529]: NoneType: None
[MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
[MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
[MainThread] cura.CrashHandler.__init__ [69]:   File "/home/frank/project/cura_dev/Cura/cura_app.py", line 239, in <module>
[MainThread] cura.CrashHandler.__init__ [69]:     app.run()
[MainThread] cura.CrashHandler.__init__ [69]:   File "/home/frank/project/cura_dev/Cura/cura/CuraApplication.py", line 821, in run
[MainThread] cura.CrashHandler.__init__ [69]:     super().run()
[MainThread] cura.CrashHandler.__init__ [69]:   File "/home/frank/.conan/data/uranium/5.1.0/_/_/package/e0048d903da3f6245f7e22f0b7132b2aa5f5826c/site-packages/UM/Qt/QtApplication.py", line 377, in run
[MainThread] cura.CrashHandler.__init__ [69]:     super().run()
[MainThread] cura.CrashHandler.__init__ [69]:   File "/home/frank/.conan/data/uranium/5.1.0/_/_/package/e0048d903da3f6245f7e22f0b7132b2aa5f5826c/site-packages/UM/Application.py", line 264, in run
[MainThread] cura.CrashHandler.__init__ [69]:     self.startSplashWindowPhase()
[MainThread] cura.CrashHandler.__init__ [69]:   File "/home/frank/project/cura_dev/Cura/cura/CuraApplication.py", line 490, in startSplashWindowPhase
[MainThread] cura.CrashHandler.__init__ [69]:     super().startSplashWindowPhase()
[MainThread] cura.CrashHandler.__init__ [69]:   File "/home/frank/.conan/data/uranium/5.1.0/_/_/package/e0048d903da3f6245f7e22f0b7132b2aa5f5826c/site-packages/UM/Qt/QtApplication.py", line 234, in startSplashWindowPhase
[MainThread] cura.CrashHandler.__init__ [69]:     self._loadPlugins()
[MainThread] cura.CrashHandler.__init__ [69]:   File "/home/frank/project/cura_dev/Cura/cura/CuraApplication.py", line 802, in _loadPlugins
[MainThread] cura.CrashHandler.__init__ [69]:     self._plugin_registry.loadPlugins()
[MainThread] cura.CrashHandler.__init__ [69]:   File "/home/frank/.conan/data/uranium/5.1.0/_/_/package/e0048d903da3f6245f7e22f0b7132b2aa5f5826c/site-packages/UM/PluginRegistry.py", line 382, in loadPlugins
[MainThread] cura.CrashHandler.__init__ [69]:     self.loadPlugin(preloaded_plugin)
[MainThread] cura.CrashHandler.__init__ [69]:   File "/home/frank/.conan/data/uranium/5.1.0/_/_/package/e0048d903da3f6245f7e22f0b7132b2aa5f5826c/site-packages/UM/PluginRegistry.py", line 436, in loadPlugin
[MainThread] cura.CrashHandler.__init__ [69]:     raise PluginNotFoundError(plugin_id)
[MainThread] cura.CrashHandler.__init__ [69]: UM.PluginError.PluginNotFoundError: Could not find plugin ConsoleLogger
Fontconfig error: Cannot load default config file
/home/frank/project/cura_dev/Cura/venv/lib/python3.10/site-packages/sentry_sdk/worker.py:83: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  self._thread.setDaemon(True)
/home/frank/project/cura_dev/Cura/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py:259: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  context = SSLContext(ssl_version or PROTOCOL_TLS)
/home/frank/project/cura_dev/Cura/venv/lib/python3.10/site-packages/urllib3/connection.py:406: DeprecationWarning: ssl.match_hostname() is deprecated
  match_hostname(cert, asserted_hostname)
```

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

_

**Comment by jellespijker** [comment]
Yes this is a known bug which will be addressed in the coming weeks. Devs see CURA-8827 and CURA-8831.

A workaround for now would be to clone Uranium as well.
Remove the two uranium paths from the `PYTHONPATH` in the `venv/bin/activate` and add the root directory of the cloned Uranium directory to the the `PYTHONPATH` instead.
