### ISSUE TITLE
Cura crashes if setting file does not have a platform

### ISSUE THREAD

**Issue by scotthraban** [Ultimaker/Cura#136]
Not entirely sure if this is the right place to enter this, or if it should be in Uranium, please let me know if this is not the right place.

I have been playing with creating a settings file for my printer, since I am (shhh) not using an Ultimaker. I ran into the problem where I did not specify a platform in the settings json file, and this causes Cura to crash on startup if that printer is the active printer.

it appears that this code in Uranium is at fault: https://github.com/Ultimaker/Uranium/blob/db7b77b53ef371cbdb51833e86bdcd5fef0c3eba/UM/Scene/Platform.py#L45, in that if getPlatformMesh returns None, bad things happen. If I set the value to the empty string ("") in the json, then life is good.

This is the traceback:

Traceback (most recent call last):
  File "cura_app.py", line 9, in <module>
  File "c:\dev\cura\cura\CuraApplication.py", line 173, in run
  File "c:\dev\uranium\UM\Application.py", line 243, in setActiveMachine
  File "c:\dev\uranium\UM\Signal.py", line 96, in emit
  File "c:\dev\uranium\UM\Scene\Platform.py", line 46, in _onActiveMachineChanged
  File "c:\dev\uranium\UM\Resources.py", line 46, in getPath
  File "c:\dev\uranium\UM\Resources.py", line 128, in __find
  File "c:\dev\python34\lib\ntpath.py", line 110, in join
  File "c:\dev\python34\lib\ntpath.py", line 159, in splitdrive
TypeError: object of type 'NoneType' has no len()

**Comment by nallath** [comment]
Yeah this is an uranium bug. It's fixed for next release.
