### ISSUE TITLE
Cura does not work properly after installation.

### ISSUE THREAD

**Issue by NARUTOfzr** [Ultimaker/Cura#15708]
### Application Version

cura4.8 / cura5.0 / cura5.2 / cura5.3 

### Operating System

Windows 10  / Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz   3.19 GHz

### Printer

All

### Reproduction steps

Recently I formatted the windows10 computer D disk. I'm not sure if I deleted some necessary files that caused cura to not work properly after installation.
![err1](https://github.com/Ultimaker/Cura/assets/64059773/ad3aee8d-d88b-4ef6-a5a2-9eceb94da22b)
![err2](https://github.com/Ultimaker/Cura/assets/64059773/7e091803-ca91-4e21-acd8-48a59dca24b1)

### Actual results

![error](https://github.com/Ultimaker/Cura/assets/64059773/4a09121c-cc94-4353-bc57-a067ae3ea135)

### Expected results

Unable to achieve the desired results.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

- Error traceback

Traceback (most recent call last):
  File "cura\Settings\MachineManager.py", line 434, in addMachine
    new_stack = CuraStackBuilder.createMachine(cast(str, name), definition_id)
  File "cura\Settings\CuraStackBuilder.py", line 67, in createMachine
    cls.createExtruderStackWithDefaultSetup(new_global_stack, position)
  File "cura\Settings\CuraStackBuilder.py", line 112, in createExtruderStackWithDefaultSetup
    approximate_diameter = round(extruder_definition.getProperty("material_diameter", "value"))  # Can't be modified by definition changes since we are just initialising the stack here.
TypeError: type NoneType doesn't define __round__ method

- Logs

Thread 0x00001a70 (most recent call first):
  File "E:\APP\UltiMaker Cura 5.4.0-alpha+cura_10389_148\share\cura\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 81 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000158 (most recent call first):
  File "threading.py", line 324 in wait
  File "zeroconf\__init__.py", line 2534 in wait
  File "zeroconf\__init__.py", line 1715 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002bb4 (most recent call first):
  File "threading.py", line 324 in wait
  File "threading.py", line 600 in wait
  File "E:\APP\UltiMaker Cura 5.4.0-alpha+cura_10389_148\share\cura\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 81 in _handleOnServiceChangedRequests
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000e60 (most recent call first):
  File "zeroconf\__init__.py", line 1369 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003e88 (most recent call first):
  File "E:\APP\UltiMaker Cura 5.4.0-alpha+cura_10389_148\share\cura\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000004d8 (most recent call first):
  File "UM\Backend\Backend.py", line 169 in _storeStderrToLogThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000045d0 (most recent call first):
  File "UM\Backend\Backend.py", line 157 in _storeOutputToLogThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002f14 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002be0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001230 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000022d4 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Current thread 0x000035c8 (most recent call first):
  File "cura\CrashHandler.py", line 397 in _logInfoWidget
  File "cura\CrashHandler.py", line 182 in _createDialog
  File "cura\CrashHandler.py", line 86 in __init__
  File "cura_app.py", line 165 in exceptHook
  File "UM\Qt\QtApplication.py", line 416 in exec
  File "cura\CuraApplication.py", line 898 in run
  File "cura_app.py", line 239 in <module>

**Comment by MariMakes** [comment]
Hey @NARUTOfzr,

Sorry, it took us a while to get back to you 😞 
Are you still stuck? 

Do I understand correctly that you want to do a clean install for Cura?
This is how you perform a clean install
	1. Quit the application
	2. In a file explorer window, navigate to:
			My Computer/users/[user_name]/AppData/Local/cura
			My computer/Users//AppData/Roaming/cura
	3. Delete the entire 'cura' folder of your current version. Note: Cura folders of previous versions will be imported if not deleted!
	4. Open Ultimaker Cura. If it has been reset correctly, you will be greeted with the onboarding flow

If you do this you will use any custom profiles. If you want to keep these make sure to make a backup.
You can read more about them here: https://support.makerbot.com/s/article/1667412704080

I also noticed that your screenshots are from a Nightly version of Cura. 
An internal version like that is not up to our normal testing standards. 

Can you also reproduce this with the latest version of Cura 5.4?
You can get it here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
