### ISSUE TITLE
Error on setting up materials

### ISSUE THREAD

**Issue by ManuelW77** [Ultimaker/Cura#1576]
Version: 2.5.0-BETA
Platform: Darwin-16.4.0-x86_64-i386-64bit
Qt: 5.7.0
PyQt: 5.7.1

Exception:
Traceback (most recent call last):
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Qt/Bindings/PreferencesProxy.py", line 22, in setValue
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Preferences.py", line 66, in setValue
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Signal.py", line 201, in emit
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Signal.py", line 305, in __performEmit
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/cura/PrintInformation.py", line 173, in _onPreferencesChanged
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/cura/PrintInformation.py", line 134, in _calculateInformation
AttributeError: 'PrintInformation' object has no attribute '_material_amounts'

**Comment by Ghostkeeper** [comment]
What were you doing when this error occurs? How can we reproduce this?
