### ISSUE TITLE
Fatal exception: AttributeError: 'PrintInformation' object has no attribute '_material_amounts'

### ISSUE THREAD

**Issue by laurenweinstein1** [Ultimaker/Cura#1618]
Version: 2.5.0-BETA
Platform: Linux-4.4.0-70-generic-x86_64-with-debian-stretch-sid
Qt: 5.7.0
PyQt: 5.7.1

Exception:
Traceback (most recent call last):
  File "/build/2.5/build/inst/lib/python3/dist-packages/cura/CuraApplication.py", line 652, in event
  File "/build/2.5/build/inst/lib/python3/dist-packages/UM/Qt/QtApplication.py", line 216, in event
  File "/build/2.5/build/inst/lib/python3/dist-packages/UM/Event.py", line 187, in call
  File "/build/2.5/build/inst/lib/python3/dist-packages/UM/Signal.py", line 305, in __performEmit
  File "/build/2.5/build/inst/lib/python3/dist-packages/cura/PrintInformation.py", line 187, in _onMaterialMetaDataChanged
  File "/build/2.5/build/inst/lib/python3/dist-packages/cura/PrintInformation.py", line 134, in _calculateInformation
AttributeError: 'PrintInformation' object has no attribute '_material_amounts'

**Comment by fieldOfView** [comment]
What were you doing when this happened? Can you reproduce it?

**Comment by nallath** [comment]
I think this already has been fixed.

**Comment by laurenweinstein1** [comment]
Triggered when reloading a saved project file. 100% reproducible.

**Comment by fieldOfView** [comment]
Can you share the project file so we can check it is ondeed fixed?

**Comment by laurenweinstein1** [comment]
I checked but unfortunately I no longer have that project file. I took a
different approach due to the recurring error at the time.

**Comment by Ghostkeeper** [comment]
This was CURA-3617. It's been fixed by this commit: https://github.com/Ultimaker/Cura/commit/b3bc019cd0ea8b022dc020a30bf61538a07c4476
