### ISSUE TITLE
AtributeError: 'NoneType' object has no attribute 'getMetaDataEntry'

### ISSUE THREAD

**Issue by dintid** [Ultimaker/Cura#1678]
Using Cura. 2.5.0 Beta

Been using just fine for a bit and have used new materials. Today cura crashes with this error message when changing material or try to save changes to it.

> Version: 2.5.0-BETA
> Platform: Windows-10-10.0.14393
> Qt: 5.7.1
> PyQt: 5.7.1
> 
> Exception:
> Traceback (most recent call last):
>   File "D:/2.5/build/inst/lib/python3.5/site-packages/cura\Settings\MachineManager.py", line 764, in setActiveMaterial
>   File "D:/2.5/build/inst/lib/python3.5/site-packages/cura\Settings\MachineManager.py", line 828, in setActiveQuality
>   File "D:/2.5/build/inst/lib/python3.5/site-packages/cura\Settings\MachineManager.py", line 944, in _replaceQualityOrQualityChangesInStack
> AttributeError: 'NoneType' object has no attribute 'getMetaDataEntry'

**Comment by Ghostkeeper** [comment]
The error seems to occur here: https://github.com/Ultimaker/Cura/blob/701570283227bbe717e3b6d7f121fcfa0d1d9990/cura/Settings/MachineManager.py#L923

It is called from one of these two: https://github.com/Ultimaker/Cura/blob/701570283227bbe717e3b6d7f121fcfa0d1d9990/cura/Settings/MachineManager.py#L807
So the quality or quality changes profile seems to be `None`.

**Comment by Ghostkeeper** [comment]
I can't reproduce this yet though.

**Comment by dintid** [comment]
Anything I can do to help sort this? What's odd is that I have created other materials without any issues.

**Comment by Ghostkeeper** [comment]
Maybe you could save a project file while you have one of those materials that gives the bug active?
It's under File -> Save Project.

**Comment by dintid** [comment]
I can't. As soon as I change to the material Cura crashes. It's only 1 material. I have an identical one, aside from the color, so it's a bit odd
![image](https://cloud.githubusercontent.com/assets/4258031/25043036/1bbd04e2-211d-11e7-92a4-e79b8eb62bfa.png)

I just noticed the profiles for the printer, where i use the material has gone missing, and I'm unable to create any - I can adjust the "active profile" though. Meaning I can change settings in main window.
![image](https://cloud.githubusercontent.com/assets/4258031/25043057/491464e4-211d-11e7-8d3f-ca930851350a.png)

**Comment by Ghostkeeper** [comment]
Well, I'm going to need to know what printer and materials you're using then, and where to download them. By default, I don't see any DuetUME3D printer, or PrimaSelect material.

**Comment by dintid** [comment]
It's just a custom printer I added, and added a material to that printer, which I copied from one of the ultimaker ones.
I havn't had time to create a new custom printer yet, which is what I planned to do next.

**Comment by synthead** [comment]
I am experiencing this.  I'm running Cura 2.5.0 on Arch Linux.

Steps to reproduce:

1. Open Cura and observe prompt for a printer.
2. Select *Ultimaker 2 Extended+* and click the *Add Printer* button.
3. Click the yellow-highlighted drop-down selection on the top-right and click *Manage Profiles*.
4. Click *Printers* from the selection on the left, click *Ultimaker 2 Extended+*, and click the *Activate* button.
5. Click *Profiles* from the selection on the left.
6. Observe segmentation fault as detailed below.

Segmentation fault:
```
2017-05-18 18:07:20,905 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:20,906 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:20,906 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/MachineManager.py", line 1091, in getDefinitionByMachineId
2017-05-18 18:07:20,906 - CRITICAL - cura.CrashHandler.show [39]:     return containers[0].getBottom().getId()
2017-05-18 18:07:20,907 - CRITICAL - cura.CrashHandler.show [39]: AttributeError: 'NoneType' object has no attribute 'getId'
2017-05-18 18:07:22,000 - WARNING - cura.Settings.ExtruderManager.getMachineExtruders [404]: Tried to get the extruder trains for machine Ultimaker 2 Extended+, which doesn't exist.
2017-05-18 18:07:22,001 - WARNING - cura.Settings.ExtruderManager.getMachineExtruders [404]: Tried to get the extruder trains for machine Ultimaker 2 Extended+, which doesn't exist.
2017-05-18 18:07:22,004 - WARNING - cura.Settings.ExtruderManager.getMachineExtruders [404]: Tried to get the extruder trains for machine Ultimaker 2 Extended+, which doesn't exist.
2017-05-18 18:07:22,005 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,005 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,006 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/MachineManager.py", line 507, in activeMaterialNames
2017-05-18 18:07:22,006 - CRITICAL - cura.CrashHandler.show [39]:     if ExtruderManager.getInstance().getActiveGlobalAndExtruderStacks() is not None:
2017-05-18 18:07:22,007 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/ExtruderManager.py", line 418, in getActiveGlobalAndExtruderStacks
2017-05-18 18:07:22,007 - CRITICAL - cura.CrashHandler.show [39]:     result.extend(self.getActiveExtruderStacks())
2017-05-18 18:07:22,008 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/ExtruderManager.py", line 429, in getActiveExtruderStacks
2017-05-18 18:07:22,008 - CRITICAL - cura.CrashHandler.show [39]:     for extruder in sorted(self._extruder_trains[global_stack.getId()]):
2017-05-18 18:07:22,008 - CRITICAL - cura.CrashHandler.show [39]: KeyError: 'Ultimaker 2 Extended+'
2017-05-18 18:07:22,009 - WARNING - cura.Settings.ContainerManager.getContainerMetaDataEntry [182]: Could not get metadata of container  because it was not found.
2017-05-18 18:07:22,009 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,010 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,010 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Settings/Models/InstanceContainersModel.py", line 60, in _update
2017-05-18 18:07:22,010 - CRITICAL - cura.CrashHandler.show [39]:     self._instance_containers = self._fetchInstanceContainers()
2017-05-18 18:07:22,010 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/UserProfilesModel.py", line 25, in _fetchInstanceContainers
2017-05-18 18:07:22,011 - CRITICAL - cura.CrashHandler.show [39]:     machine_definition = quality_manager.getParentMachineDefinition(global_container_stack.getBottom())
2017-05-18 18:07:22,011 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/QualityManager.py", line 251, in getParentMachineDefinition
2017-05-18 18:07:22,011 - CRITICAL - cura.CrashHandler.show [39]:     machine_entry = machine_definition.getMetaDataEntry("machine")
2017-05-18 18:07:22,011 - CRITICAL - cura.CrashHandler.show [39]: AttributeError: 'NoneType' object has no attribute 'getMetaDataEntry'
2017-05-18 18:07:22,011 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,011 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,011 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Settings/Models/InstanceContainersModel.py", line 60, in _update
2017-05-18 18:07:22,012 - CRITICAL - cura.CrashHandler.show [39]:     self._instance_containers = self._fetchInstanceContainers()
2017-05-18 18:07:22,012 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/UserProfilesModel.py", line 25, in _fetchInstanceContainers
2017-05-18 18:07:22,012 - CRITICAL - cura.CrashHandler.show [39]:     machine_definition = quality_manager.getParentMachineDefinition(global_container_stack.getBottom())
2017-05-18 18:07:22,012 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/QualityManager.py", line 251, in getParentMachineDefinition
2017-05-18 18:07:22,012 - CRITICAL - cura.CrashHandler.show [39]:     machine_entry = machine_definition.getMetaDataEntry("machine")
2017-05-18 18:07:22,012 - CRITICAL - cura.CrashHandler.show [39]: AttributeError: 'NoneType' object has no attribute 'getMetaDataEntry'
2017-05-18 18:07:22,012 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,013 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,013 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Settings/Models/InstanceContainersModel.py", line 60, in _update
2017-05-18 18:07:22,013 - CRITICAL - cura.CrashHandler.show [39]:     self._instance_containers = self._fetchInstanceContainers()
2017-05-18 18:07:22,013 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/ProfilesModel.py", line 54, in _fetchInstanceContainers
2017-05-18 18:07:22,013 - CRITICAL - cura.CrashHandler.show [39]:     extruder_stacks = extruder_manager.getActiveExtruderStacks()
2017-05-18 18:07:22,013 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/ExtruderManager.py", line 429, in getActiveExtruderStacks
2017-05-18 18:07:22,014 - CRITICAL - cura.CrashHandler.show [39]:     for extruder in sorted(self._extruder_trains[global_stack.getId()]):
2017-05-18 18:07:22,014 - CRITICAL - cura.CrashHandler.show [39]: KeyError: 'Ultimaker 2 Extended+'
2017-05-18 18:07:22,014 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,014 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,014 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Settings/Models/InstanceContainersModel.py", line 60, in _update
2017-05-18 18:07:22,014 - CRITICAL - cura.CrashHandler.show [39]:     self._instance_containers = self._fetchInstanceContainers()
2017-05-18 18:07:22,014 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/UserProfilesModel.py", line 25, in _fetchInstanceContainers
2017-05-18 18:07:22,014 - CRITICAL - cura.CrashHandler.show [39]:     machine_definition = quality_manager.getParentMachineDefinition(global_container_stack.getBottom())
2017-05-18 18:07:22,015 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/QualityManager.py", line 251, in getParentMachineDefinition
2017-05-18 18:07:22,015 - CRITICAL - cura.CrashHandler.show [39]:     machine_entry = machine_definition.getMetaDataEntry("machine")
2017-05-18 18:07:22,015 - CRITICAL - cura.CrashHandler.show [39]: AttributeError: 'NoneType' object has no attribute 'getMetaDataEntry'
2017-05-18 18:07:22,015 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,015 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,015 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Settings/Models/InstanceContainersModel.py", line 60, in _update
2017-05-18 18:07:22,015 - CRITICAL - cura.CrashHandler.show [39]:     self._instance_containers = self._fetchInstanceContainers()
2017-05-18 18:07:22,016 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/UserProfilesModel.py", line 25, in _fetchInstanceContainers
2017-05-18 18:07:22,016 - CRITICAL - cura.CrashHandler.show [39]:     machine_definition = quality_manager.getParentMachineDefinition(global_container_stack.getBottom())
2017-05-18 18:07:22,016 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/QualityManager.py", line 251, in getParentMachineDefinition
2017-05-18 18:07:22,016 - CRITICAL - cura.CrashHandler.show [39]:     machine_entry = machine_definition.getMetaDataEntry("machine")
2017-05-18 18:07:22,016 - CRITICAL - cura.CrashHandler.show [39]: AttributeError: 'NoneType' object has no attribute 'getMetaDataEntry'
2017-05-18 18:07:22,016 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,016 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,016 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Settings/Models/InstanceContainersModel.py", line 60, in _update
2017-05-18 18:07:22,017 - CRITICAL - cura.CrashHandler.show [39]:     self._instance_containers = self._fetchInstanceContainers()
2017-05-18 18:07:22,017 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/ProfilesModel.py", line 54, in _fetchInstanceContainers
2017-05-18 18:07:22,017 - CRITICAL - cura.CrashHandler.show [39]:     extruder_stacks = extruder_manager.getActiveExtruderStacks()
2017-05-18 18:07:22,017 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/ExtruderManager.py", line 429, in getActiveExtruderStacks
2017-05-18 18:07:22,017 - CRITICAL - cura.CrashHandler.show [39]:     for extruder in sorted(self._extruder_trains[global_stack.getId()]):
2017-05-18 18:07:22,017 - CRITICAL - cura.CrashHandler.show [39]: KeyError: 'Ultimaker 2 Extended+'
2017-05-18 18:07:22,017 - WARNING - cura.Settings.ExtruderManager.getMachineExtruders [404]: Tried to get the extruder trains for machine Ultimaker 2 Extended+, which doesn't exist.
2017-05-18 18:07:22,018 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,018 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,018 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/BuildVolume.py", line 436, in _onStackChanged
2017-05-18 18:07:22,018 - CRITICAL - cura.CrashHandler.show [39]:     self._updateDisallowedAreas()
2017-05-18 18:07:22,018 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/BuildVolume.py", line 500, in _updateDisallowedAreas
2017-05-18 18:07:22,018 - CRITICAL - cura.CrashHandler.show [39]:     used_extruders = extruder_manager.getUsedExtruderStacks()
2017-05-18 18:07:22,018 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/ExtruderManager.py", line 347, in getUsedExtruderStacks
2017-05-18 18:07:22,019 - CRITICAL - cura.CrashHandler.show [39]:     if global_stack.getProperty("machine_extruder_count", "value") <= 1: #For single extrusion.
2017-05-18 18:07:22,019 - CRITICAL - cura.CrashHandler.show [39]: TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2017-05-18 18:07:22,019 - WARNING - cura.Settings.ExtruderManager.getMachineExtruders [404]: Tried to get the extruder trains for machine Ultimaker 2 Extended+, which doesn't exist.
2017-05-18 18:07:22,019 - WARNING - cura.Settings.ExtruderManager.getMachineExtruders [404]: Tried to get the extruder trains for machine Ultimaker 2 Extended+, which doesn't exist.
2017-05-18 18:07:22,019 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,019 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,020 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/BuildVolume.py", line 436, in _onStackChanged
2017-05-18 18:07:22,020 - CRITICAL - cura.CrashHandler.show [39]:     self._updateDisallowedAreas()
2017-05-18 18:07:22,020 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/BuildVolume.py", line 500, in _updateDisallowedAreas
2017-05-18 18:07:22,020 - CRITICAL - cura.CrashHandler.show [39]:     used_extruders = extruder_manager.getUsedExtruderStacks()
2017-05-18 18:07:22,020 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/ExtruderManager.py", line 347, in getUsedExtruderStacks
2017-05-18 18:07:22,020 - CRITICAL - cura.CrashHandler.show [39]:     if global_stack.getProperty("machine_extruder_count", "value") <= 1: #For single extrusion.
2017-05-18 18:07:22,020 - CRITICAL - cura.CrashHandler.show [39]: TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2017-05-18 18:07:22,020 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,021 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,021 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Settings/Models/InstanceContainersModel.py", line 60, in _update
2017-05-18 18:07:22,021 - CRITICAL - cura.CrashHandler.show [39]:     self._instance_containers = self._fetchInstanceContainers()
2017-05-18 18:07:22,021 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/UserProfilesModel.py", line 25, in _fetchInstanceContainers
2017-05-18 18:07:22,021 - CRITICAL - cura.CrashHandler.show [39]:     machine_definition = quality_manager.getParentMachineDefinition(global_container_stack.getBottom())
2017-05-18 18:07:22,021 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/QualityManager.py", line 251, in getParentMachineDefinition
2017-05-18 18:07:22,021 - CRITICAL - cura.CrashHandler.show [39]:     machine_entry = machine_definition.getMetaDataEntry("machine")
2017-05-18 18:07:22,021 - CRITICAL - cura.CrashHandler.show [39]: AttributeError: 'NoneType' object has no attribute 'getMetaDataEntry'
2017-05-18 18:07:22,022 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,022 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,022 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Settings/Models/InstanceContainersModel.py", line 60, in _update
2017-05-18 18:07:22,022 - CRITICAL - cura.CrashHandler.show [39]:     self._instance_containers = self._fetchInstanceContainers()
2017-05-18 18:07:22,022 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/UserProfilesModel.py", line 25, in _fetchInstanceContainers
2017-05-18 18:07:22,022 - CRITICAL - cura.CrashHandler.show [39]:     machine_definition = quality_manager.getParentMachineDefinition(global_container_stack.getBottom())
2017-05-18 18:07:22,022 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/QualityManager.py", line 251, in getParentMachineDefinition
2017-05-18 18:07:22,022 - CRITICAL - cura.CrashHandler.show [39]:     machine_entry = machine_definition.getMetaDataEntry("machine")
2017-05-18 18:07:22,023 - CRITICAL - cura.CrashHandler.show [39]: AttributeError: 'NoneType' object has no attribute 'getMetaDataEntry'
2017-05-18 18:07:22,023 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,023 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,023 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Settings/Models/InstanceContainersModel.py", line 60, in _update
2017-05-18 18:07:22,023 - CRITICAL - cura.CrashHandler.show [39]:     self._instance_containers = self._fetchInstanceContainers()
2017-05-18 18:07:22,023 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/ProfilesModel.py", line 54, in _fetchInstanceContainers
2017-05-18 18:07:22,023 - CRITICAL - cura.CrashHandler.show [39]:     extruder_stacks = extruder_manager.getActiveExtruderStacks()
2017-05-18 18:07:22,023 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/ExtruderManager.py", line 429, in getActiveExtruderStacks
2017-05-18 18:07:22,024 - CRITICAL - cura.CrashHandler.show [39]:     for extruder in sorted(self._extruder_trains[global_stack.getId()]):
2017-05-18 18:07:22,024 - CRITICAL - cura.CrashHandler.show [39]: KeyError: 'Ultimaker 2 Extended+'
2017-05-18 18:07:22,024 - WARNING - cura.Settings.ExtruderManager.getMachineExtruders [404]: Tried to get the extruder trains for machine Ultimaker 2 Extended+, which doesn't exist.
2017-05-18 18:07:22,024 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,025 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,025 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/MachineManager.py", line 321, in setActiveMachine
2017-05-18 18:07:22,025 - CRITICAL - cura.CrashHandler.show [39]:     Application.getInstance().setGlobalContainerStack(containers[0])
2017-05-18 18:07:22,025 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Application.py", line 144, in setGlobalContainerStack
2017-05-18 18:07:22,025 - CRITICAL - cura.CrashHandler.show [39]:     self.globalContainerStackChanged.emit()
2017-05-18 18:07:22,025 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Signal.py", line 201, in emit
2017-05-18 18:07:22,025 - CRITICAL - cura.CrashHandler.show [39]:     self.__performEmit(*args, **kwargs)
2017-05-18 18:07:22,025 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Signal.py", line 305, in __performEmit
2017-05-18 18:07:22,026 - CRITICAL - cura.CrashHandler.show [39]:     func(dest, *args, **kwargs)
2017-05-18 18:07:22,026 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/cura/plugins/PerObjectSettingsTool/PerObjectSettingsTool.py", line 81, in _onGlobalContainerChanged
2017-05-18 18:07:22,026 - CRITICAL - cura.CrashHandler.show [39]:     self._multi_extrusion = global_container_stack.getProperty("machine_extruder_count", "value") > 1
2017-05-18 18:07:22,026 - CRITICAL - cura.CrashHandler.show [39]: TypeError: '>' not supported between instances of 'NoneType' and 'int'
2017-05-18 18:07:22,027 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,027 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,027 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Qt/Bindings/MainWindow.py", line 183, in _render
2017-05-18 18:07:22,027 - CRITICAL - cura.CrashHandler.show [39]:     view.beginRendering()
2017-05-18 18:07:22,027 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/cura/plugins/SolidView/SolidView.py", line 53, in beginRendering
2017-05-18 18:07:22,028 - CRITICAL - cura.CrashHandler.show [39]:     multi_extrusion = global_container_stack.getProperty("machine_extruder_count", "value") > 1
2017-05-18 18:07:22,028 - CRITICAL - cura.CrashHandler.show [39]: TypeError: '>' not supported between instances of 'NoneType' and 'int'
2017-05-18 18:07:22,530 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:22,531 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:22,532 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/cura/plugins/CuraEngineBackend/CuraEngineBackend.py", line 190, in slice
2017-05-18 18:07:22,532 - CRITICAL - cura.CrashHandler.show [39]:     self.printDurationMessage.emit(0, [0])
2017-05-18 18:07:22,533 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Signal.py", line 201, in emit
2017-05-18 18:07:22,533 - CRITICAL - cura.CrashHandler.show [39]:     self.__performEmit(*args, **kwargs)
2017-05-18 18:07:22,534 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Signal.py", line 305, in __performEmit
2017-05-18 18:07:22,534 - CRITICAL - cura.CrashHandler.show [39]:     func(dest, *args, **kwargs)
2017-05-18 18:07:22,535 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/PrintInformation.py", line 124, in _onPrintDurationMessage
2017-05-18 18:07:22,535 - CRITICAL - cura.CrashHandler.show [39]:     self._calculateInformation()
2017-05-18 18:07:22,535 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/PrintInformation.py", line 131, in _calculateInformation
2017-05-18 18:07:22,536 - CRITICAL - cura.CrashHandler.show [39]:     radius = Application.getInstance().getGlobalContainerStack().getProperty("material_diameter", "value") / 2
2017-05-18 18:07:22,536 - CRITICAL - cura.CrashHandler.show [39]: TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2017-05-18 18:07:36,034 - WARNING - cura.Settings.ExtruderManager.getMachineExtruders [404]: Tried to get the extruder trains for machine Ultimaker 2 Extended+, which doesn't exist.
2017-05-18 18:07:36,036 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-18 18:07:36,037 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-18 18:07:36,038 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/QualityAndUserProfilesModel.py", line 13, in __init__
2017-05-18 18:07:36,038 - CRITICAL - cura.CrashHandler.show [39]:     super().__init__(parent)
2017-05-18 18:07:36,039 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/ProfilesModel.py", line 19, in __init__
2017-05-18 18:07:36,039 - CRITICAL - cura.CrashHandler.show [39]:     super().__init__(parent)
2017-05-18 18:07:36,039 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Settings/Models/InstanceContainersModel.py", line 46, in __init__
2017-05-18 18:07:36,040 - CRITICAL - cura.CrashHandler.show [39]:     self._update()
2017-05-18 18:07:36,040 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/UM/Settings/Models/InstanceContainersModel.py", line 60, in _update
2017-05-18 18:07:36,041 - CRITICAL - cura.CrashHandler.show [39]:     self._instance_containers = self._fetchInstanceContainers()
2017-05-18 18:07:36,041 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/Settings/QualityAndUserProfilesModel.py", line 25, in _fetchInstanceContainers
2017-05-18 18:07:36,041 - CRITICAL - cura.CrashHandler.show [39]:     machine_definition = quality_manager.getParentMachineDefinition(global_container_stack.getBottom())
2017-05-18 18:07:36,042 - CRITICAL - cura.CrashHandler.show [39]:   File "/usr/lib/python3.6/site-packages/cura/QualityManager.py", line 251, in getParentMachineDefinition
2017-05-18 18:07:36,042 - CRITICAL - cura.CrashHandler.show [39]:     machine_entry = machine_definition.getMetaDataEntry("machine")
2017-05-18 18:07:36,043 - CRITICAL - cura.CrashHandler.show [39]: AttributeError: 'NoneType' object has no attribute 'getMetaDataEntry'
Segmentation fault (core dumped)
```

Also, after selecting a printer, Cura does not appear to render a 3D representation of the printer like it does on OS X.  This is what I see:

![image](https://cloud.githubusercontent.com/assets/820984/26229238/47c2fbee-3bf5-11e7-8197-d8a9c991a27f.png)

**Comment by Ghostkeeper** [comment]
Thanks for the very clear reproduction steps, synthead! They don't reproduce the problem on my end though. At step 3 it's not yellow-highlighted already. The rest of the steps can be performed but it's not producing the problem you describe.

It sounds like your Cura instance can't even find the UM2+ quality profiles. Apparently that's giving trouble. Either that, or adding the printer broke down somewhere halfway...

**Comment by BagelOrb** [comment]
@dintid Are yous till experiencing this problem?
