### ISSUE TITLE
Changing Filament Cost causes fatal exception

### ISSUE THREAD

**Issue by pho1** [Ultimaker/Cura#1680]
Version: 2.5.0-BETA
Platform: Darwin-16.1.0-x86_64-i386-64bit
Qt: 5.7.0
PyQt: 5.7.1

Exception:
Traceback (most recent call last):
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Qt/Bindings/PreferencesProxy.py", line 22, in setValue
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Preferences.py", line 66, in setValue
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Signal.py", line 201, in emit
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Signal.py", line 305, in __performEmit
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/cura/PrintInformation.py", line 173, in _onPreferencesChanged
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/cura/PrintInformation.py", line 134, in _calculateInformation
AttributeError: 'PrintInformation' object has no attribute '_material_amounts'

Steps to Reproduce:
Using Cura 2.5 Beta on a UM3 that is currently printing with "Automatic: Black PLA" set as material in extruder 1, I go to Manage Materials and type in "60" for the Filament Cost and then this fatal exception appears

Actual Results:
Fatal Exception window appears. I copy and paste the exception and when I close the window, Cura closes.

Expected results:
Cost should just change and then nothing should crash

**Comment by nallath** [comment]
This is fixed in the beta-2
