### ISSUE TITLE
fatal exception, please help

### ISSUE THREAD

**Issue by 3DPrinterPoint** [Ultimaker/Cura#1697]
Version: 2.3.1
Platform: Windows-10-10.0.14393
Qt: 5.5.1
PyQt: 5.5.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 61, in <module>
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Application.py", line 310, in getInstance
  File "D:\2.3\build\inst\lib\python3.4\site-packages\cura\CuraApplication.py", line 173, in __init__
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\QtApplication.py", line 94, in __init__
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 107, in upgrade
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 281, in _upgradeFile
  File "C:\Python34\lib\codecs.py", line 319, in decode
MemoryError

**Comment by fieldOfView** [comment]
Try removing the log file in C:\Users\[your username]\AppData\local\cura and starting Cura again.

**Comment by LipuFei** [comment]
@3DPrinterPoint Could you remove the log files in `C:\Users\[your username]\AppData\local\cura` and try again? It was trying to read a log file (too big) and got out of memory.

**Comment by 3DPrinterPoint** [comment]
Hello Aldo and Lipu, thank you both for the tip. It worked, Cura is running again!

**Comment by fieldOfView** [comment]
Good to hear. AFAIK this was fixed in Cura 2.4

**Comment by Ghostkeeper** [comment]
Yes, we just caught the MemoryError and continued on our merry way with upgrading the next file.
