### ISSUE TITLE
Gcode reader fails when gcode line has trailing comment word that starts with X, Y, Z or E!

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#1739]
I am trying to load a gcode file (generated by Cura) into Cura 2.5 and it's failing like this:

> 2017-04-25 13:59:40,495 - ERROR - UM.Logger.logException [74]: Exception: Exception occurred while loading file /home/markb/smartavionics/projects/pb4-misc/misc/KM_capture-switch-housing.gcode
2017-04-25 13:59:40,496 - ERROR - UM.Logger.logException [78]: Traceback (most recent call last):
2017-04-25 13:59:40,496 - ERROR - UM.Logger.logException [78]:   File "/usr/local/lib/python3/dist-packages/UM/FileHandler/ReadFileJob.py", line 61, in run
2017-04-25 13:59:40,496 - ERROR - UM.Logger.logException [78]:     self.setResult(self._handler.readerRead(reader, self._filename))
2017-04-25 13:59:40,497 - ERROR - UM.Logger.logException [78]:   File "/usr/local/lib/python3/dist-packages/UM/Mesh/MeshFileHandler.py", line 28, in readerRead
2017-04-25 13:59:40,497 - ERROR - UM.Logger.logException [78]:     results = reader.read(file_name)
2017-04-25 13:59:40,497 - ERROR - UM.Logger.logException [78]:   File "/usr/local/lib/cura/plugins/GCodeReader/GCodeReader.py", line 301, in read
2017-04-25 13:59:40,500 - ERROR - UM.Logger.logException [78]:     current_position = self._processGCode(G, line, current_position, current_path)
2017-04-25 13:59:40,501 - ERROR - UM.Logger.logException [78]:   File "/usr/local/lib/cura/plugins/GCodeReader/GCodeReader.py", line 194, in _processGCode
2017-04-25 13:59:40,501 - ERROR - UM.Logger.logException [78]:     e = float(item[1:])
2017-04-25 13:59:40,501 - ERROR - UM.Logger.logException [78]: ValueError: could not convert string to float: 'XTRUDER'

The gcode file starts like this:
>;FLAVOR:RepRap
;TIME:2240
;Filament used: 1.84417m
;Layer height: 0.2
;Generated with Cura_SteamEngine master
M190 S60
M104 S205
M109 S205
G28 ; home all axes
G1 X0 Y0 Z25 F8000 ; descend
M82 ; extruder absolute mode

If you look in GCodeReader.py it's obvious why it fails because it just splits the gcode line at spaces and looks to see if it can find items that start with X, Y, Z or E and tries to extract a number that follows. Unfortunately, it doesn't strip the comment off the end of the line before doing this so it thinks the word extruder is part of the gcode!

**Comment by smartavionics** [comment]
I am using 2.5, what was the sha1 of the fix?

**Comment by smartavionics** [comment]
I found the fix but it's in the master branch and not the 2.5 branch. Closing...
