### ISSUE TITLE
Loggin Lost after wake up. Cura also crashes randomly (MAC OS). Computer reformatted still happening.

### ISSUE THREAD

**Issue by alnavasa** [Ultimaker/Cura#17508]
### Cura Version

5.6

### Operating System

Mac OS 13.6.1 (22G313)

### Printer

Ultimaker S5

### Reproduction steps

Sometimes I find Cura as not logged in to my ultimaker account. I kind of have the feeling that most times it is after reboot, or after wake from sleep. Log attached.

### Actual results

Sometimes I find Cura as not logged in to my ultimaker account. I kind of have the feeling that most times it is after reboot, or after wake from sleep. Log attached.

### Expected results

Sometimes I find Cura as not logged in to my ultimaker account. I kind of have the feeling that most times it is after reboot, or after wake from sleep. Log attached.

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/Ultimaker/Cura/files/13539636/cura.log)

**Comment by alnavasa** [comment]
Lost again, Log below:

[cura.log](https://github.com/Ultimaker/Cura/files/13550348/cura.log)

**Comment by alnavasa** [comment]
IT now suddenlty crashed while in background time 9:45

Log below time 9:45, re opened at 9:47

[cura.log](https://github.com/Ultimaker/Cura/files/13597623/cura.log)

**Comment by alnavasa** [comment]
And it crashes again,

It is incredible that a 6.000€ machine is bundled with this issues


MacBook Pro 17" i7 
Mac OS: 13.6.3 (22G436)

Cura: 5.6.0 (???)

Log file attached below, 

Snippet of the area causing it to crash below,
Also having issues syncing materiales from the computer to the printer.
`2024-01-02 11:28:05,333 - DEBUG - [MainThread] UM.TaskManagement.HttpRequestManager._onRequestError [369]: request[53c70cc2][get][PyQt6.QtCore.QUrl('https://api.ultimaker.com/connect/v1/clusters?status=active')][timeout=10][no-data] got an QNetworkReplyError Operation canceled. The server returned: None
2024-01-02 11:28:05,333 - DEBUG - [MainThread] UM.TaskManagement.HttpRequestManager._onRequestFinished [408]: request[53c70cc2][get][PyQt6.QtCore.QUrl('https://api.ultimaker.com/connect/v1/clusters?status=active')][timeout=10][no-data] was aborted, do nothing
2024-01-02 11:28:05,334 - ERROR - [MainThread] cura.API.Account.error_callback [373]: Request for user permissions list failed. Network error: NetworkError.OperationCanceledError
2024-01-02 11:28:06,331 - DEBUG - [MainThread] UM3NetworkPrinting.src.UltimakerNetworkedPrinterOutputDevice._checkStillConnected [264]: It has been 1220.7764253616333 seconds since the last response for outputdevice HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7, so assume a timeout
2024-01-02 11:28:08,331 - DEBUG - [MainThread] UM3NetworkPrinting.src.UltimakerNetworkedPrinterOutputDevice._checkStillConnected [264]: It has been 1222.776622056961 seconds since the last response for outputdevice HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7, so assume a timeout
2024-01-02 11:28:10,331 - DEBUG - [MainThread] UM3NetworkPrinting.src.UltimakerNetworkedPrinterOutputDevice._checkStillConnected [264]: It has been 1224.7765412330627 seconds since the last response for outputdevice HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7, so assume a timeout
2024-01-02 11:28:12,331 - DEBUG - [MainThread] UM3NetworkPrinting.src.UltimakerNetworkedPrinterOutputDevice._checkStillConnected [264]: It has been 1226.7761301994324 seconds since the last response for outputdevice HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7, so assume a timeout
2024-01-02 11:28:14,331 - DEBUG - [MainThread] UM.TaskManagement.HttpRequestManager._onRequestTimeout [295]: Request [<UM.TaskManagement.HttpRequestManager.HttpRequestManager object at 0x12612d750>] timeout.
2024-01-02 11:28:14,331 - DEBUG - [MainThread] UM3NetworkPrinting.src.UltimakerNetworkedPrinterOutputDevice._checkStillConnected [264]: It has been 1228.7768850326538 seconds since the last response for outputdevice HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7, so assume a timeout
2024-01-02 11:28:14,494 - WARNING - [MainThread] cura.OAuth2.AuthorizationService.refreshAccessToken [162]: Unable to refresh access token, since there is no refresh token.
2024-01-02 11:28:14,502 - DEBUG - [MainThread] cura.UltimakerCloud.UltimakerCloudScope.requestHook [30]: User is not logged in for Cloud API request to https://api.ultimaker.com/connect/v1/clusters/HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7/status
2024-01-02 11:28:14,503 - DEBUG - [MainThread] UM.TaskManagement.HttpRequestManager._onRequestError [369]: request[1749380a][get][PyQt6.QtCore.QUrl('https://api.ultimaker.com/cura-packages/v1/user/packages')][timeout=10][no-data] got an QNetworkReplyError Operation canceled. The server returned: None
2024-01-02 11:28:14,504 - DEBUG - [MainThread] UM.TaskManagement.HttpRequestManager._onRequestFinished [408]: request[1749380a][get][PyQt6.QtCore.QUrl('https://api.ultimaker.com/cura-packages/v1/user/packages')][timeout=10][no-data] was aborted, do nothing
2024-01-02 11:28:14,505 - WARNING - [MainThread] Marketplace.CloudSync.CloudPackageChecker._onUserPackagesRequestFinished [76]: Requesting user packages failed, response code -1 while trying to connect to PyQt6.QtCore.QUrl('https://api.ultimaker.com/cura-packages/v1/user/packages')
2024-01-02 11:28:14,507 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2024-01-02 11:28:14,507 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2024-01-02 11:28:14,508 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "UM/ColorImage.py", line 42, in setSource
2024-01-02 11:28:14,508 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "UM/ColorImage.py", line 29, in _updateSVG
2024-01-02 11:28:14,509 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: OSError: [Errno 24] Too many open files: '/Applications/UltiMaker Cura.app/Contents/MacOS/share/cura/resources/themes/cura-light/icons/default/Warning.svg'`



[cura.log](https://github.com/Ultimaker/Cura/files/13809204/cura.log)

**Comment by alnavasa** [comment]
Laptop reformatted, complete new OS and new cura

Cura 5.6.0
MAC OS 13.6.3 (22G436)

Log attached.
[cura.log](https://github.com/Ultimaker/Cura/files/13835835/cura.log)



Key part before crash at **2024-01-04 22:45:48,929**


`2024-01-04 22:45:32,577 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.refreshAccessToken [174]: Was already busy refreshing token. Do not start a new request.
2024-01-04 22:45:32,775 - DEBUG - [MainThread] UM.TaskManagement.HttpRequestManager._onRequestError [369]: request[6f6d1f4a][get][PyQt6.QtCore.QUrl('https://api.ultimaker.com/connect/v1/clusters/HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7/status')][timeout=10][no-data] got an QNetworkReplyError Error transferring https://api.ultimaker.com/connect/v1/clusters/HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7/status - server replied: . The server returned: b'{"errors": [{"id": "7348b34f-ddf8-4a35-b42a-1953c596bb16", "code": "tokenExpired", "http_status": "403", "title": "The given token has expired.", "detail": "Signature has expired", "meta": {"error_type": "AuthError", "url": "https://api.ultimaker.com/clusters/HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7/status"}}]}'
2024-01-04 22:45:34,374 - DEBUG - [MainThread] UM3NetworkPrinting.src.UltimakerNetworkedPrinterOutputDevice._checkStillConnected [264]: It has been 2888.835464954376 seconds since the last response for outputdevice HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7, so assume a timeout
2024-01-04 22:45:35,286 - DEBUG - [MainThread] UM3NetworkPrinting.src.UltimakerNetworkedPrinterOutputDevice._checkStillConnected [264]: It has been 2889.747220993042 seconds since the last response for outputdevice HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7, so assume a timeout
2024-01-04 22:45:37,286 - DEBUG - [MainThread] UM3NetworkPrinting.src.UltimakerNetworkedPrinterOutputDevice._checkStillConnected [264]: It has been 2891.747320175171 seconds since the last response for outputdevice HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7, so assume a timeout
2024-01-04 22:45:39,286 - DEBUG - [MainThread] UM3NetworkPrinting.src.UltimakerNetworkedPrinterOutputDevice._checkStillConnected [264]: It has been 2893.7471990585327 seconds since the last response for outputdevice HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7, so assume a timeout
2024-01-04 22:45:41,286 - DEBUG - [MainThread] UM3NetworkPrinting.src.UltimakerNetworkedPrinterOutputDevice._checkStillConnected [264]: It has been 2895.747339963913 seconds since the last response for outputdevice HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7, so assume a timeout
2024-01-04 22:45:47,575 - DEBUG - [MainThread] UM3NetworkPrinting.src.UltimakerNetworkedPrinterOutputDevice._checkStillConnected [264]: It has been 2902.036354780197 seconds since the last response for outputdevice HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7, so assume a timeout
2024-01-04 22:45:47,629 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.refreshAccessToken [174]: Was already busy refreshing token. Do not start a new request.
2024-01-04 22:45:47,830 - DEBUG - [MainThread] UM.TaskManagement.HttpRequestManager._onRequestError [369]: request[461cf9dd][get][PyQt6.QtCore.QUrl('https://api.ultimaker.com/connect/v1/clusters/HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7/status')][timeout=10][no-data] got an QNetworkReplyError Error transferring https://api.ultimaker.com/connect/v1/clusters/HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7/status - server replied: . The server returned: b'{"errors": [{"id": "118b192d-c008-49da-9326-fe829d048b46", "code": "tokenExpired", "http_status": "403", "title": "The given token has expired.", "detail": "Signature has expired", "meta": {"error_type": "AuthError", "url": "https://api.ultimaker.com/clusters/HPA4XDvAwHpIoA4W9p5fhLsaeHVCGuSQ6uH0rli-HzZ7/status"}}]}'
2024-01-04 22:45:48,830 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.refreshAccessToken [174]: Was already busy refreshing token. Do not start a new request.
2024-01-04 22:45:48,880 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.refreshAccessToken [174]: Was already busy refreshing token. Do not start a new request.
2024-01-04 22:45:48,929 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.refreshAccessToken [174]: Was already busy refreshing token. Do not start a new request.`

**Comment by cbagwell** [comment]
The prints in last comment combined with happening right after waking from sleep means this is likely a duplicate of #15161.

**Comment by rburema** [comment]
In addition to that the login issue (possibly not the crashes though) is likely solved in 5.7.x, since there's a good chance it's fixed with this: https://github.com/Ultimaker/Cura/pull/17967
