### ISSUE TITLE
Cura for Robo C2 Not Opening

### ISSUE THREAD

**Issue by Inspired03** [Ultimaker/Cura#1752]
Hello everyone,

I downloaded Cura for Robo on my windows computer about 2 weeks ago and it has been working just fine since then up until yesterday. When I tried to open it yesterday it kept giving me an error that said "A fatal exception has occurred that we could not recover from!" and gave me this info:

Version: 2.3.1
Platform: Windows-10-10.0.14393
Qt: 5.5.1
PyQt: 5.5.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 61, in <module>
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Application.py", line 310, in getInstance
  File "D:\2.3\build\inst\lib\python3.4\site-packages\cura\CuraApplication.py", line 173, in __init__
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\QtApplication.py", line 94, in __init__
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 107, in upgrade
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 281, in _upgradeFile
MemoryError

I have tried to uninstall the program and reinstall it 3 times now and nothing has made it work. Currently in dire need of the printer since I use it in a class but can not get it to work. Please if anyone knows anything, let me know so I Can try it.

Thank you

**Comment by fieldOfView** [comment]
Apparently Cura for Robo is based on an older version of Cura. This bug you are running in to has already been fixed for the normal Cura 2.x.

To fix your Cura, you have to open C:\Users\[your username]\AppData\Local\cura and remove cura.log.

Feel free to ask Robo for assistance when running into issues with their version of the software.
