### ISSUE TITLE
3mf files are causing Cura to crash

### ISSUE THREAD

**Issue by GregValiant** [Ultimaker/Cura#17550]
### Cura Version

5.6.0

### Operating System

Windows 10 Pro

### Printer

Ender 3 Pro with stock 8-bit board and Marlin 1.1.8

### Reproduction steps

In Cura 5.6 when I attempt to open a 3mf file created with 5.4.0 or 5.5.0 and get an immediate crash of Cura.  This is happening with increasing frequency.  It appears (to me) to be related to materials, specifically "Generic PLA 175"

### Actual results

Cura crashes and the "Report a Crash" dialog comes up.
From the top box of the dialog:
Traceback (most recent call last):
  File "cura\CuraApplication.py", line 1168, in event
    return super().event(event)
  File "UM\Qt\QtApplication.py", line 502, in event
    event._function_event.call()
  File "UM\Event.py", line 218, in call
    self._function(*self._args, **self._kwargs)
  File "cura\Utils\Threading.py", line 34, in _handle_call
    ico.result = func(*args, **kwargs)
  File "C:\Program Files\UltiMaker Cura 5.6.0\share\cura\plugins\3MFReader\ThreeMFWorkspaceReader.py", line 857, in read
    self._applyChangesToMachine(global_stack, extruder_stack_dict)
  File "C:\Program Files\UltiMaker Cura 5.6.0\share\cura\plugins\3MFReader\ThreeMFWorkspaceReader.py", line 1189, in _applyChangesToMachine
    self._applyMaterials(global_stack, extruder_stack_dict)
  File "C:\Program Files\UltiMaker Cura 5.6.0\share\cura\plugins\3MFReader\ThreeMFWorkspaceReader.py", line 1177, in _applyMaterials
    material_node = machine_node.variants[extruder_stack.variant.getName()].materials[root_material_id]
KeyError: 'generic_pla_175'

From the lower text box:
Thread 0x000001d8 (most recent call first):
  File "threading.py", line 324 in wait
  File "zeroconf\__init__.py", line 2534 in wait
  File "zeroconf\__init__.py", line 1715 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000009b4 (most recent call first):
  File "threading.py", line 324 in wait
  File "threading.py", line 600 in wait
  File "C:\Program Files\UltiMaker Cura 5.6.0\share\cura\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 81 in _handleOnServiceChangedRequests
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002cb0 (most recent call first):
  File "zeroconf\__init__.py", line 1369 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002e0c (most recent call first):
  File "C:\Program Files\UltiMaker Cura 5.6.0\share\cura\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001d38 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 600 in wait
  File "cura\Utils\Threading.py", line 39 in _call_on_qt_thread_wrapper
  File "UM\Workspace\WorkspaceFileHandler.py", line 42 in readerRead
  File "UM\FileHandler\ReadFileJob.py", line 78 in run
  File "UM\JobQueue.py", line 133 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001534 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000e7c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000038c4 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001748 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002968 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003010 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000108c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Current thread 0x000016d0 (most recent call first):
  File "cura\CrashHandler.py", line 397 in _logInfoWidget
  File "cura\CrashHandler.py", line 182 in _createDialog
  File "cura\CrashHandler.py", line 86 in __init__
  File "cura_app.py", line 165 in exceptHook
  File "UM\Qt\QtApplication.py", line 416 in exec
  File "cura\CuraApplication.py", line 930 in run
  File "cura_app.py", line 239 in <module>

### Expected results

Open the project.

### Add your .zip and screenshots here ⬇️

Here is the log and stderr file along with one of the project files.
[cura.zip](https://github.com/Ultimaker/Cura/files/13601445/cura.zip)

**Comment by GregValiant** [comment]
@MariMakes it's hard to triage things when I can't open the files.
