### ISSUE TITLE
Cura 2.50-beta suffered a fatal error after install on Mac 10.12.4

### ISSUE THREAD

**Issue by jerry7171** [Ultimaker/Cura#1763]
Mac Pro (Early 2009)
3.33 GHz 6-Core Intel Xeon
32 GB 1333 MHz DDR3
AMD Radeon HD 7000 2048 MB

Version: 2.5.0-BETA
Platform: Darwin-16.5.0-x86_64-i386-64bit
Qt: 5.7.0
PyQt: 5.7.1

Exception:
Traceback (most recent call last):
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Backend/Backend.py", line 58, in startEngine
  File "/Applications/Cura.app/Contents/MacOS/plugins/plugins/CuraEngineBackend/CuraEngineBackend.py", line 144, in getEngineCommand
    json_path = Resources.getPath(Resources.DefinitionContainers, "fdmprinter.def.json")
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Resources.py", line 71, in getPath
FileNotFoundError: Could not find resource ('fdmprinter.def.json',) in 8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 653, in event
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 216, in event
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Event.py", line 187, in call
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Signal.py", line 305, in __performEmit
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Backend/Backend.py", line 160, in _onSocketStateChanged
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Backend/Backend.py", line 81, in startEngine
  File "/Applications/Cura.app/Contents/MacOS/plugins/plugins/CuraEngineBackend/CuraEngineBackend.py", line 144, in getEngineCommand
    json_path = Resources.getPath(Resources.DefinitionContainers, "fdmprinter.def.json")
  File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/UM/Resources.py", line 71, in getPath
FileNotFoundError: Could not find resource ('fdmprinter.def.json',) in 8

**Comment by Ghostkeeper** [comment]
What did you do to get this error? Download it and start Cura?

I'm not reproducing this on my end.
