### ISSUE TITLE
Cura 2.5 freezes on startup Debian & Ubuntu

### ISSUE THREAD

**Issue by Schwarzdrossel** [Ultimaker/Cura#1836]
Hi,
I'm currently using debian sid and Cura hangs itself on startup,
the same happens on ubuntu 17.04 and 16.04 (via Virtualbox)

last terminal output is:
-05-17 08:41:37,401 - DEBUG - UM.Backend.Backend._logSocketState [172]: Socket state changed to Connected
2017-05-17 08:41:37,408 - DEBUG - UM.Backend.Backend._onSocketStateChanged [162]: Backend connected on port 49674
2017-05-17 08:41:37,415 - DEBUG - UM.Controller.setActiveView [81]: Setting active view to SolidView

**Comment by nallath** [comment]
Are you running it from PPA or appimage?

**Comment by Schwarzdrossel** [comment]
Appimage

**Comment by nallath** [comment]
Could you post the entire log?

**Comment by Schwarzdrossel** [comment]
./Cura-2.5.0.AppImage 
UM.View.GL.OpenGLContext.detectBestOpenGLVersion [103]: Trying OpenGL context 4.1...
UM.View.GL.OpenGLContext.detectBestOpenGLVersion [113]: Yay, we got at least OpenGL 4.1 core: 4.3 Core profile
UM.Qt.QtApplication.__init__ [75]: Detected most suitable OpenGL context version: 4.1 Core profile
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
UM.PluginRegistry.loadPlugin [102]: Loaded plugin 3MFReader
UM.PluginRegistry.loadPlugin [102]: Loaded plugin 3MFWriter
UM.PluginRegistry.loadPlugin [102]: Loaded plugin AutoSave
UM.PluginRegistry.loadPlugin [102]: Loaded plugin ChangeLogPlugin
2017-05-17 13:52:45,966 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin ConsoleLogger
2017-05-17 13:52:46,027 - INFO - CuraEngineBackend.CuraEngineBackend.__init__ [64]: Found CuraEngine at: /tmp/.mount_qOnPwU/usr/bin/CuraEngine
2017-05-17 13:52:46,031 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin CuraEngineBackend
2017-05-17 13:52:46,051 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin CuraProfileReader
2017-05-17 13:52:46,070 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin CuraProfileWriter
2017-05-17 13:52:46,246 - INFO - UM.PluginRegistry.loadPlugin [85]: Plugin Doodle3D uses an incompatible API version, ignoring
2017-05-17 13:52:46,266 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin OBJReader
2017-05-17 13:52:46,282 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin OBJWriter
2017-05-17 13:52:46,292 - WARNING - STLReader.STLReader.<module> [26]: Could not find numpy-stl, falling back to slower code.
2017-05-17 13:52:46,300 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin STLReader
2017-05-17 13:52:46,318 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin STLWriter
2017-05-17 13:52:46,329 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin FileLogger
2017-05-17 13:52:46,355 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin GCodeProfileReader
2017-05-17 13:52:46,390 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin GCodeReader
2017-05-17 13:52:46,410 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin GCodeWriter
2017-05-17 13:52:46,442 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin ImageReader
2017-05-17 13:52:46,516 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin LayerView
2017-05-17 13:52:46,539 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin LegacyProfileReader
2017-05-17 13:52:46,567 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin LocalFileOutputDevice
2017-05-17 13:52:46,594 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin MachineSettingsAction
2017-05-17 13:52:46,626 - WARNING - UM.Preferences.getValue [81]: Tried to get the value of non-existing setting cura/active_mode.
2017-05-17 13:52:46,630 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin PerObjectSettingsTool
2017-05-17 13:52:46,657 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin PostProcessingPlugin
2017-05-17 13:52:46,694 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin RemovableDriveOutputDevice
2017-05-17 13:52:46,722 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin SliceInfoPlugin
2017-05-17 13:52:46,745 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin SolidView
2017-05-17 13:52:46,766 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin CameraTool
2017-05-17 13:52:46,791 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin MirrorTool
2017-05-17 13:52:46,865 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin RotateTool
2017-05-17 13:52:46,894 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin ScaleTool
2017-05-17 13:52:46,911 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin SelectionTool
2017-05-17 13:52:46,935 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin TranslateTool
2017-05-17 13:52:46,967 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin UltimakerMachineActions
2017-05-17 13:52:47,322 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin UM3NetworkPrinting
2017-05-17 13:52:47,411 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin UpdateChecker
2017-05-17 13:52:47,413 - INFO - UpdateChecker.UpdateChecker.run [40]: Checking for new version of cura
2017-05-17 13:52:47,520 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin USBPrinting
2017-05-17 13:52:47,560 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin VersionUpgrade21to22
2017-05-17 13:52:47,580 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin VersionUpgrade22to24
2017-05-17 13:52:47,600 - ERROR - UM.PluginRegistry.loadPlugin [91]: Plugin VersionUpgrade24to25 did not return any objects to register
2017-05-17 13:52:47,614 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin SimpleView
2017-05-17 13:52:47,634 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin WireframeView
2017-05-17 13:52:47,676 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin X3DReader
2017-05-17 13:52:47,704 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin XmlMaterialProfile
2017-05-17 13:52:47,724 - INFO - UM.PluginRegistry.loadPlugin [102]: Loaded plugin XRayView
2017-05-17 13:52:47,734 - INFO - UM.Qt.QtApplication.__init__ [107]: Command line arguments: {'external-backend': False, 'single_instance': False, 'file': [], 'qmljsdebugger': None, 'disable-textures': False}
2017-05-17 13:52:47,792 - INFO - UM.VersionUpgradeManager.upgrade [100]: Looking for old configuration files to upgrade.
2017-05-17 13:52:47,882 - DEBUG - UM.Backend.Backend._logSocketState [168]: Socket state changed to Listening
2017-05-17 13:52:47,908 - INFO - UM.Backend.Backend.startEngine [72]: Started engine process: /tmp/.mount_qOnPwU/usr/bin/CuraEngine
2017-05-17 13:52:47,915 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] Calling engine with: ['/tmp/.mount_qOnPwU/usr/bin/CuraEngine', 'connect', '127.0.0.1:49674', '-j', '/tmp/.mount_qOnPwU/usr/bin/resources/definitions/fdmprinter.def.json', '']
2017-05-17 13:52:47,992 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] 
2017-05-17 13:52:48,005 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] Cura_SteamEngine version DEV
2017-05-17 13:52:48,016 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] Copyright (C) 2014 David Braam
2017-05-17 13:52:48,030 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] 
2017-05-17 13:52:48,040 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] This program is free software: you can redistribute it and/or modify
2017-05-17 13:52:48,054 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] it under the terms of the GNU Affero General Public License as published by
2017-05-17 13:52:48,061 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] the Free Software Foundation, either version 3 of the License, or
2017-05-17 13:52:48,067 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] (at your option) any later version.
2017-05-17 13:52:48,072 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] 
2017-05-17 13:52:48,075 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] This program is distributed in the hope that it will be useful,
2017-05-17 13:52:48,079 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] but WITHOUT ANY WARRANTY; without even the implied warranty of
2017-05-17 13:52:48,083 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
2017-05-17 13:52:48,089 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] GNU Affero General Public License for more details.
2017-05-17 13:52:48,099 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] 
2017-05-17 13:52:48,104 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] You should have received a copy of the GNU Affero General Public License
2017-05-17 13:52:48,108 - DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] along with this program.  If not, see <http://www.gnu.org/licenses/>.
2017-05-17 13:52:48,915 - DEBUG - MachineSettingsAction.MachineSettingsAction._onContainerAdded [72]: Not attaching MachineSettingsAction to vertex_k8400_dual; Multi-extrusion printers are not supported
2017-05-17 13:52:52,090 - DEBUG - MachineSettingsAction.MachineSettingsAction._onContainerAdded [72]: Not attaching MachineSettingsAction to ultimaker3_extended; Multi-extrusion printers are not supported
2017-05-17 13:52:53,203 - DEBUG - MachineSettingsAction.MachineSettingsAction._onContainerAdded [72]: Not attaching MachineSettingsAction to punchtec_connect_xl; Multi-extrusion printers are not supported
2017-05-17 13:52:58,371 - DEBUG - MachineSettingsAction.MachineSettingsAction._onContainerAdded [72]: Not attaching MachineSettingsAction to ultimaker3; Multi-extrusion printers are not supported
2017-05-17 13:53:00,505 - WARNING - UM.Settings.DefinitionContainer.deserialize [206]: Unable to override setting machine_nozzle_offset_x
2017-05-17 13:53:00,512 - WARNING - UM.Settings.DefinitionContainer.deserialize [206]: Unable to override setting machine_nozzle_offset_y
2017-05-17 13:53:02,353 - DEBUG - MachineSettingsAction.MachineSettingsAction._onContainerAdded [72]: Not attaching MachineSettingsAction to ord; Multi-extrusion printers are not supported
2017-05-17 13:53:04,821 - DEBUG - MachineSettingsAction.MachineSettingsAction._onContainerAdded [72]: Not attaching MachineSettingsAction to cartesio; Multi-extrusion printers are not supported
2017-05-17 13:53:16,782 - DEBUG - MachineSettingsAction.MachineSettingsAction._onContainerAdded [72]: Not attaching MachineSettingsAction to ultimaker_original_dual; Multi-extrusion printers are not supported
2017-05-17 13:53:19,024 - WARNING - UM.Settings.DefinitionContainer.deserialize [206]: Unable to override setting machine_nozzle_head_distance
2017-05-17 13:53:19,215 - WARNING - UM.Settings.DefinitionContainer.deserialize [206]: Unable to override setting machine_nozzle_head_distance
2017-05-17 13:53:19,285 - WARNING - UM.Settings.DefinitionContainer.deserialize [206]: Unable to override setting machine_nozzle_head_distance
2017-05-17 13:53:19,323 - WARNING - UM.Settings.DefinitionContainer.deserialize [206]: Unable to override setting machine_nozzle_head_distance
2017-05-17 13:53:20,217 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:20,241 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:20,314 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:20,338 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:20,500 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:20,524 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:20,602 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:20,628 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:20,895 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:20,930 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:21,063 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:21,096 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:21,326 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:21,365 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:21,389 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:21,422 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:21,450 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [457]: Unsupported material setting retraction prime speed
2017-05-17 13:53:21,451 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [457]: Unsupported material setting nozzle switch prime speed
2017-05-17 13:53:21,507 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:21,543 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:21,729 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:21,770 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:21,883 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:21,925 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:22,032 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:22,073 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:22,185 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:22,227 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:22,343 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:22,387 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:22,504 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:22,548 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:22,672 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:22,720 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:22,754 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:22,795 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:22,955 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:23,003 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:23,647 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:23,707 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:23,883 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:23,942 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:24,125 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:24,188 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:24,367 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:24,428 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:24,616 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:24,684 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:24,890 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:24,956 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:25,437 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:25,504 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:25,603 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [457]: Unsupported material setting retraction prime speed
2017-05-17 13:53:25,604 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [457]: Unsupported material setting nozzle switch prime speed
2017-05-17 13:53:25,841 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:25,917 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:26,139 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:26,213 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:26,423 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:26,500 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:26,946 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:27,021 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:27,053 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [457]: Unsupported material setting retraction prime speed
2017-05-17 13:53:27,054 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [457]: Unsupported material setting nozzle switch prime speed
2017-05-17 13:53:27,295 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:27,372 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:27,595 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:27,667 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:27,847 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:27,912 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:28,112 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:28,179 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:28,365 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:28,433 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:28,642 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:28,721 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:28,921 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:28,993 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:29,204 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:29,289 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:29,751 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:29,838 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:30,038 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:30,118 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:30,322 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:30,398 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:30,623 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3
2017-05-17 13:53:30,704 - DEBUG - XmlMaterialProfile.XmlMaterialProfile.deserialize [506]: No variants found with ID or name AA 0.25 for machine ultimaker3_extended
2017-05-17 13:53:30,751 - DEBUG - UM.Settings.ContainerRegistry.load [204]: Loading data into container registry took 42.5812668800354 seconds
2017-05-17 13:53:30,758 - DEBUG - UM.Backend.Backend._logSocketState [172]: Socket state changed to Connected
2017-05-17 13:53:30,764 - DEBUG - UM.Backend.Backend._onSocketStateChanged [162]: Backend connected on port 49674
2017-05-17 13:53:30,769 - DEBUG - UM.Controller.setActiveView [81]: Setting active view to SolidView

**Comment by nallath** [comment]
It's kind of odd; It does seem to be able to find the correct OpenGL drivers to function. 

It is rather weird that it fails to find numpy-stl, but I very much doubt that this causes the crash.

**Comment by Schwarzdrossel** [comment]
I run the programm a bit longer and I get this logs

2017-05-17 15:39:25,456 - DEBUG - UM.Controller.setActiveView [81]: Setting active view to SolidView
Exception in thread zeroconf-Engine:
Traceback (most recent call last):
  File "/build/env/inst/lib/python3.5/threading.py", line 914, in _bootstrap_inner
  File "/build/env/inst/lib/python3.5/site-packages/zeroconf.py", line 951, in run
  File "/build/env/inst/lib/python3.5/site-packages/zeroconf.py", line 988, in handle_read
  File "/build/env/inst/lib/python3.5/site-packages/zeroconf.py", line 563, in __init__
  File "/build/env/inst/lib/python3.5/site-packages/zeroconf.py", line 611, in read_others
  File "/build/env/inst/lib/python3.5/site-packages/zeroconf.py", line 665, in read_name
IndexError: index out of range

Exception in thread zeroconf-ServiceBrowser__ultimaker._tcp.local.:
Traceback (most recent call last):
  File "/build/env/inst/lib/python3.5/threading.py", line 914, in _bootstrap_inner
  File "/build/env/inst/lib/python3.5/site-packages/zeroconf.py", line 1164, in run
  File "/build/env/inst/lib/python3.5/site-packages/zeroconf.py", line 1853, in send
OSError: [Errno 22] Invalid argument

"Keine derartige Schnittstelle »org.freedesktop.DBus.Properties« des Objekts im Pfad /org/freedesktop/NetworkManager/ActiveConnection/2"

**Comment by nallath** [comment]
Could you try and remove the UM3NetworkingPlugin from the appimage? That is the one that does something with zeroconf.

**Comment by ianpaschal** [comment]
No more work will be done on versions 2.x. If this is still occurring in versions 3.2 or newer, we can re-open this issue.
