### ISSUE TITLE
Fatal exception

### ISSUE THREAD

**Issue by misalo1** [Ultimaker/Cura#1853]
Version: 2.3.1
Platform: Windows-Vista-6.0.6002-SP2
Qt: 5.5.1
PyQt: 5.5.1

Exception:
Traceback (most recent call last):
  File "D:\2.3\build\inst\lib\python3.4\site-packages\cura\CuraApplication.py", line 530, in event
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\QtApplication.py", line 192, in event
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Event.py", line 157, in call
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Signal.py", line 150, in emit
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Scene\SceneNode.py", line 120, in calculateBoundingBoxMesh
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Scene\SceneNode.py", line 576, in getBoundingBox
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Scene\SceneNode.py", line 643, in _calculateAABB
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Mesh\MeshData.py", line 146, in getExtents
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Mesh\MeshData.py", line 221, in getConvexHullVertices
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Mesh\MeshData.py", line 213, in getConvexHull
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Mesh\MeshData.py", line 205, in _computeConvexHull
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Mesh\MeshData.py", line 313, in approximateConvexHull
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Mesh\MeshData.py", line 288, in roundVertexArray
MemoryError

**Comment by Ghostkeeper** [comment]
Your computer seems to be running out of memory. Perhaps allocating more swap space could help?

See [this page](http://www.speedypc.com/articles/increase_virtual_memory_vista.aspx) for some instructions.
