### ISSUE TITLE
5.6.0 Cura Slow Z Crash? When Uploading To Octoprint.

### ISSUE THREAD

**Issue by NokEternal** [Ultimaker/Cura#18565]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality Ender 3 S1 Pro

### Reproduction steps

1. I tried to upload a calibrational cube stl, from Cura 5.6.0 into the Octoprint plugin, The very moment I go to upload said sliced file to the octoprint ip path, with correct IP it then crashes and gives me a crash report.. 

### Actual results

Cura Crashes with this report.

Error Traceback-

Traceback (most recent call last):
  File "C:\Users\RENT A CENTER\AppData\Roaming\cura\5.6\plugins\OctoPrintPlugin\OctoPrintPlugin\UploadOptions.py", line 73, in acceptOptionsDialog
    self._proceed_callback()
  File "C:\Users\RENT A CENTER\AppData\Roaming\cura\5.6\plugins\OctoPrintPlugin\OctoPrintPlugin\OctoPrintOutputDevice.py", line 564, in proceedRequestWrite
    self.writeStarted.emit(self)
  File "UM\Signal.py", line 216, in emit
    self.__handleEmitIndirect(*args, **kwargs)
  File "UM\Signal.py", line 323, in __handleEmitIndirect
    self.__performEmit(*args, **kwargs)
  File "UM\Signal.py", line 361, in __performEmit
    signal.emit(*args, **kwargs)
  File "UM\Signal.py", line 216, in emit
    self.__handleEmitIndirect(*args, **kwargs)
  File "UM\Signal.py", line 323, in __handleEmitIndirect
    self.__performEmit(*args, **kwargs)
  File "UM\Signal.py", line 357, in __performEmit
    func(dest, *args, **kwargs)
  File "C:\Users\RENT A CENTER\AppData\Roaming\cura\5.6\plugins\CuraSlowZ\CuraSlowZ\CuraSlowZ.py", line 149, in _filterGcode
    if slowz_percentage <= 0:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

### Expected results

Cura should just upload said stl to octoprint for printing.

### Add your .zip and screenshots here ⬇️

Logs-

Thread 0x0000079c (most recent call first):
  File "threading.py", line 324 in wait
  File "zeroconf\__init__.py", line 2534 in wait
  File "zeroconf\__init__.py", line 1715 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002128 (most recent call first):
  File "zeroconf\__init__.py", line 1369 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005830 (most recent call first):
  File "C:\Program Files\UltiMaker Cura 5.6.0\share\cura\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 90 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005dfc (most recent call first):
  File "threading.py", line 324 in wait
  File "zeroconf\__init__.py", line 2534 in wait
  File "zeroconf\__init__.py", line 1715 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000044e0 (most recent call first):
  File "threading.py", line 324 in wait
  File "threading.py", line 600 in wait
  File "C:\Program Files\UltiMaker Cura 5.6.0\share\cura\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 81 in _handleOnServiceChangedRequests
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005870 (most recent call first):
  File "zeroconf\__init__.py", line 1369 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001f48 (most recent call first):
  File "C:\Program Files\UltiMaker Cura 5.6.0\share\cura\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000e88 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000050e4 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002c80 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000024b8 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001d64 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005f7c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000056bc (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004460 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000004b8 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003b50 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000047d8 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001a48 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Current thread 0x00001f9c (most recent call first):
  File "cura\CrashHandler.py", line 397 in _logInfoWidget
  File "cura\CrashHandler.py", line 182 in _createDialog
  File "cura\CrashHandler.py", line 86 in __init__
  File "cura_app.py", line 165 in exceptHook
  File "UM\Qt\QtApplication.py", line 416 in exec
  File "cura\CuraApplication.py", line 930 in run
  File "cura_app.py", line 239 in <module>

**Comment by Asterchades** [comment]
Neither Cura Slow Z nor the OctoPrint Connection plugin are part of the base Cura package. An issue with one or both of these would need to be addressed on their respective repository: [Cura Slow Z](https://github.com/5axes/Cura-Slow-Z?tab=readme-ov-file) or [OctoPrint Connection](https://github.com/fieldOfView/Cura-OctoPrintPlugin).
