### ISSUE TITLE
Cura "uncaught exception"

### ISSUE THREAD

**Issue by 5macksmobile** [Ultimaker/Cura#199]
I am running the latest versions of Cura on a machine running windows 8.1 and was working fine until today when I received this error any ideas on how to fix this?

Thanks
Mark
Ooops

Version: 15.06.02
Platform: Windows-8-6.2.9200
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 9, in <module>
  File "c:\dev\uranium\UM\Application.py", line 329, in getInstance
  File "c:\dev\cura\cura\CuraApplication.py", line 56, in __init__
  File "c:\dev\uranium\UM\Qt\QtApplication.py", line 48, in __init__
  File "c:\dev\uranium\UM\Application.py", line 67, in __init__
  File "c:\dev\uranium\UM\Preferences.py", line 56, in readFromFile
  File "c:\dev\uranium\UM\Preferences.py", line 124, in _loadFile
  File "c:\dev\python34\lib\configparser.py", line 937, in __getitem__
KeyError: 'general'

**Comment by nallath** [comment]
This doesn't look like the latest version, as this was an issue with the first version that we release. This issue was patched in 15.06.01
You could try to remove the .cfg file in $User/AppData/Local/cura/ and try again.

**Comment by ripper121** [comment]
Version: 15.06.02
Platform: Windows-7-6.1.7601-SP1
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 9, in <module>
  File "c:\dev\uranium\UM\Application.py", line 329, in getInstance
  File "c:\dev\cura\cura\CuraApplication.py", line 56, in __init__
  File "c:\dev\uranium\UM\Qt\QtApplication.py", line 48, in __init__
  File "c:\dev\uranium\UM\Application.py", line 67, in __init__
  File "c:\dev\uranium\UM\Preferences.py", line 56, in readFromFile
  File "c:\dev\uranium\UM\Preferences.py", line 122, in _loadFile
  File "c:\dev\python34\lib\configparser.py", line 672, in read
  File "c:\dev\python34\lib\configparser.py", line 1044, in _read
configparser.DuplicateSectionError: While reading from 'C:\\Users\\STS/AppData/Local/cura\\cura.cfg' [line 20]: section 'view' already exists

**Comment by ripper121** [comment]
Version: 15.06.03
Platform: Windows-7-6.1.7601-SP1
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 9, in <module>
  File "c:\dev\uranium\UM\Application.py", line 329, in getInstance
  File "c:\dev\cura\cura\CuraApplication.py", line 56, in __init__
  File "c:\dev\uranium\UM\Qt\QtApplication.py", line 48, in __init__
  File "c:\dev\uranium\UM\Application.py", line 67, in __init__
  File "c:\dev\uranium\UM\Preferences.py", line 56, in readFromFile
  File "c:\dev\uranium\UM\Preferences.py", line 122, in _loadFile
  File "c:\dev\python34\lib\configparser.py", line 672, in read
  File "c:\dev\python34\lib\configparser.py", line 1044, in _read
configparser.DuplicateSectionError: While reading from 'C:\\Users\\STS/AppData/Local/cura\\cura.cfg' [line 20]: section 'view' already exists

**Comment by ripper121** [comment]
I delete my Settings under : C:\Users\User\AppData\Local\cura
Then it works.

**Comment by nallath** [comment]
I believe this is an error caused because you had an old version installed before. Did you instal 15.06.00 (or a beta) by any chance?

**Comment by ripper121** [comment]
No is started with the 15.06.01

**Comment by nallath** [comment]
Odd. Well, it's fixed now and doesn't happen with a clean install.

**Comment by 5macksmobile** [comment]
Thanks Jaime, that sorted it out :-)

On Wed, Jul 29, 2015 at 11:34 PM, Jaime van Kessel <notifications@github.com
