### ISSUE TITLE
Display corruption after resizing the window

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#204]
After loading two objects, playing around with their scale and rotation, all while in Layer viewmode, I maximised the window. This led to the following display corruption:

![untitled-1](https://cloud.githubusercontent.com/assets/143551/9022876/024e809c-3887-11e5-857b-0c4c6781437a.jpg)
It started more subtle (the 3d view showing through the settings panel), but in the screenshot I tried rotating the view for "extra effect".

Crash Handler did not catch the errors, but fortunately I was running Cura outside of Program Files so Cura.log could be written:
```
Traceback (most recent call last):
  File "c:\dev\uranium\UM\Qt\Bindings\MainWindow.py", line 90, in mouseReleaseEvent
  File "c:\dev\uranium\UM\Qt\QtMouseDevice.py", line 36, in handleEvent
  File "c:\dev\uranium\UM\Signal.py", line 96, in emit
  File "c:\dev\uranium\UM\Controller.py", line 211, in event
  File "C:\Users\Aldo\Desktop\Cura\Cura_15.06.03\plugins\Tools\RotateTool\RotateTool.py", line 122, in event
    self.operationStopped.emit(self)
  File "c:\dev\uranium\UM\Signal.py", line 100, in emit
  File "c:\dev\uranium\UM\Signal.py", line 96, in emit
  File "c:\dev\cura\cura\PlatformPhysics.py", line 115, in _onToolOperationStopped
  File "c:\dev\cura\cura\PlatformPhysics.py", line 108, in _onChangeTimerFinished
  File "c:\dev\uranium\UM\Operations\Operation.py", line 49, in push
  File "c:\dev\uranium\UM\Operations\OperationStack.py", line 34, in push
  File "c:\dev\cura\cura\PlatformPhysicsOperation.py", line 22, in redo
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 310, in setPosition
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 427, in _transformChanged
  File "c:\dev\uranium\UM\Signal.py", line 94, in emit
  File "c:\dev\python34\lib\weakref.py", line 387, in items
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "c:\dev\uranium\UM\Qt\Bindings\MainWindow.py", line 90, in mouseReleaseEvent
  File "c:\dev\uranium\UM\Qt\QtMouseDevice.py", line 36, in handleEvent
  File "c:\dev\uranium\UM\Signal.py", line 96, in emit
  File "c:\dev\uranium\UM\Controller.py", line 211, in event
  File "C:\Users\Aldo\Desktop\Cura\Cura_15.06.03\plugins\Tools\RotateTool\RotateTool.py", line 122, in event
    self.operationStopped.emit(self)
  File "c:\dev\uranium\UM\Signal.py", line 100, in emit
  File "c:\dev\uranium\UM\Signal.py", line 96, in emit
  File "c:\dev\cura\cura\PlatformPhysics.py", line 115, in _onToolOperationStopped
  File "c:\dev\cura\cura\PlatformPhysics.py", line 108, in _onChangeTimerFinished
  File "c:\dev\uranium\UM\Operations\Operation.py", line 49, in push
  File "c:\dev\uranium\UM\Operations\OperationStack.py", line 34, in push
  File "c:\dev\cura\cura\PlatformPhysicsOperation.py", line 22, in redo
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 310, in setPosition
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 427, in _transformChanged
  File "c:\dev\uranium\UM\Signal.py", line 94, in emit
  File "c:\dev\python34\lib\weakref.py", line 387, in items
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "c:\dev\cura\cura\PlatformPhysics.py", line 108, in _onChangeTimerFinished
  File "c:\dev\uranium\UM\Operations\Operation.py", line 49, in push
  File "c:\dev\uranium\UM\Operations\OperationStack.py", line 34, in push
  File "c:\dev\cura\cura\PlatformPhysicsOperation.py", line 22, in redo
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 310, in setPosition
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 427, in _transformChanged
  File "c:\dev\uranium\UM\Signal.py", line 94, in emit
  File "c:\dev\python34\lib\weakref.py", line 387, in items
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "c:\dev\cura\cura\PlatformPhysics.py", line 108, in _onChangeTimerFinished
  File "c:\dev\uranium\UM\Operations\Operation.py", line 49, in push
  File "c:\dev\uranium\UM\Operations\OperationStack.py", line 34, in push
  File "c:\dev\cura\cura\PlatformPhysicsOperation.py", line 22, in redo
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 310, in setPosition
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 427, in _transformChanged
  File "c:\dev\uranium\UM\Signal.py", line 94, in emit
  File "c:\dev\python34\lib\weakref.py", line 387, in items
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "c:\dev\uranium\UM\Qt\Bindings\ActiveToolProxy.py", line 59, in setProperty
AttributeError: 'RotateTool' object has no attribute 'setScaleZ'
Traceback (most recent call last):
  File "c:\dev\uranium\UM\Qt\Bindings\MainWindow.py", line 90, in mouseReleaseEvent
  File "c:\dev\uranium\UM\Qt\QtMouseDevice.py", line 36, in handleEvent
  File "c:\dev\uranium\UM\Signal.py", line 96, in emit
  File "c:\dev\uranium\UM\Controller.py", line 211, in event
  File "C:\Users\Aldo\Desktop\Cura\Cura_15.06.03\plugins\Tools\RotateTool\RotateTool.py", line 122, in event
    self.operationStopped.emit(self)
  File "c:\dev\uranium\UM\Signal.py", line 100, in emit
  File "c:\dev\uranium\UM\Signal.py", line 96, in emit
  File "c:\dev\cura\cura\PlatformPhysics.py", line 115, in _onToolOperationStopped
  File "c:\dev\cura\cura\PlatformPhysics.py", line 108, in _onChangeTimerFinished
  File "c:\dev\uranium\UM\Operations\Operation.py", line 49, in push
  File "c:\dev\uranium\UM\Operations\OperationStack.py", line 34, in push
  File "c:\dev\cura\cura\PlatformPhysicsOperation.py", line 22, in redo
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 310, in setPosition
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 427, in _transformChanged
  File "c:\dev\uranium\UM\Signal.py", line 94, in emit
  File "c:\dev\python34\lib\weakref.py", line 387, in items
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "c:\dev\cura\cura\PlatformPhysics.py", line 108, in _onChangeTimerFinished
  File "c:\dev\uranium\UM\Operations\Operation.py", line 49, in push
  File "c:\dev\uranium\UM\Operations\OperationStack.py", line 34, in push
  File "c:\dev\cura\cura\PlatformPhysicsOperation.py", line 22, in redo
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 310, in setPosition
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 427, in _transformChanged
  File "c:\dev\uranium\UM\Signal.py", line 94, in emit
  File "c:\dev\python34\lib\weakref.py", line 387, in items
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "c:\dev\cura\cura\PlatformPhysics.py", line 108, in _onChangeTimerFinished
  File "c:\dev\uranium\UM\Operations\Operation.py", line 49, in push
  File "c:\dev\uranium\UM\Operations\OperationStack.py", line 34, in push
  File "c:\dev\cura\cura\PlatformPhysicsOperation.py", line 22, in redo
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 310, in setPosition
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 427, in _transformChanged
  File "c:\dev\uranium\UM\Signal.py", line 94, in emit
  File "c:\dev\python34\lib\weakref.py", line 387, in items
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "c:\dev\cura\cura\PlatformPhysics.py", line 108, in _onChangeTimerFinished
  File "c:\dev\uranium\UM\Operations\Operation.py", line 49, in push
  File "c:\dev\uranium\UM\Operations\OperationStack.py", line 34, in push
  File "c:\dev\cura\cura\PlatformPhysicsOperation.py", line 22, in redo
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 310, in setPosition
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 427, in _transformChanged
  File "c:\dev\uranium\UM\Signal.py", line 94, in emit
  File "c:\dev\python34\lib\weakref.py", line 387, in items
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "c:\dev\uranium\UM\Qt\Bindings\MainWindow.py", line 138, in _render
  File "C:\Users\Aldo\Desktop\Cura\Cura_15.06.03\plugins\LayerView\LayerView.py", line 98, in beginRendering
    layer_mesh = layer_data.getLayer(layer).createMesh()
  File "C:\Users\Aldo\Desktop\Cura\Cura_15.06.03\plugins\CuraEngineBackend\LayerData.py", line 31, in getLayer
    return self._layers[layer]
KeyError: 1424
Traceback (most recent call last):
  File "c:\dev\cura\cura\PlatformPhysics.py", line 108, in _onChangeTimerFinished
  File "c:\dev\uranium\UM\Operations\Operation.py", line 49, in push
  File "c:\dev\uranium\UM\Operations\OperationStack.py", line 34, in push
  File "c:\dev\cura\cura\PlatformPhysicsOperation.py", line 22, in redo
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 310, in setPosition
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 427, in _transformChanged
  File "c:\dev\uranium\UM\Signal.py", line 94, in emit
  File "c:\dev\python34\lib\weakref.py", line 387, in items
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "c:\dev\cura\cura\PlatformPhysics.py", line 108, in _onChangeTimerFinished
  File "c:\dev\uranium\UM\Operations\Operation.py", line 49, in push
  File "c:\dev\uranium\UM\Operations\OperationStack.py", line 34, in push
  File "c:\dev\cura\cura\PlatformPhysicsOperation.py", line 22, in redo
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 310, in setPosition
  File "c:\dev\uranium\UM\Scene\SceneNode.py", line 427, in _transformChanged
  File "c:\dev\uranium\UM\Signal.py", line 94, in emit
  File "c:\dev\python34\lib\weakref.py", line 387, in items
RuntimeError: dictionary changed size during iteration
```

**Comment by fieldOfView** [comment]
The errors in the above Cura.log may be caused by using the slider in Layers viewmode while the slicer is running and/or while the layers are loading.

**Comment by awhiemstra** [comment]
Looks to me like your graphics driver gave up and stopped rendering properly. Unfortunately there is not much we can do about that. The other log errors are indeed related to event processing and should not lead to this kind of graphics corruption.

**Comment by nickthetait** [comment]
The windows toolbar at the bottom is still rendering fine. So I would find it hard to blame the graphics driver.

**Comment by fieldOfView** [comment]
I think @awhiemstra meant the opengl stack for the app, which is basically a part of the driver.

The computer this happened on is an otherwise well-behaving Core i5 with integrated HD Graphics 3000, and up-to-date drivers. I'll try to push my other computer, which has an nVidia card, to see if the same happens. If it does, we know it is not the driver.

**Comment by nickthetait** [comment]
Aha! Thanks for doing more testing. :smile:

**Comment by fieldOfView** [comment]
I have not yet reproduced this on other hardware. Then again, I can't reproduce it consistently on the Intel HD Graphics hw either.

What I do get on the nVidia hardware is that the shader for the UMO mesh doesn't work for a frame; I see a flash of black, but after that the rendering restores. So it seems that "something" fishy is going on during resize.

**Comment by awhiemstra** [comment]
I was indeed referring to the OpenGL stack for the application.

I have seen this once with a colleague of mine, who also uses HD Graphics 3000 iirc. We also could never reproduce it since a restart of the application made things work normally again.

Unfortunately I have no NVidia hardware to test on so cannot easily reproduce the NVidia error. But maybe you can open a seperate issue for that?
