### ISSUE TITLE
AttributeError: 'CuraApplication' object has no attribute 'getStorageDevice'

### ISSUE THREAD

**Issue by supergis** [Ultimaker/Cura#213]
On Ubuntu15.04, run python3 cura_app.py.
I got errors as follow:
```
Version: master
Platform: Linux-3.19.0-25-generic-x86_64-with-Ubuntu-15.04-vivid
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 10, in <module>
    app.run()
  File "/home/supermap/dev/Cura/cura/CuraApplication.py", line 169, in run
    self.getStorageDevice("LocalFileStorage").removableDrivesChanged.connect(self._removableDrivesChanged)
AttributeError: 'CuraApplication' object has no attribute 'getStorageDevice'
```

**Comment by awhiemstra** [comment]
Please check if you have the most recent version both of Cura and Uranium. CuraApplication master has no lines relating to storage device as all that API was removed.
