### ISSUE TITLE
Cura master not building

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#236]
Version: master
Platform: Linux-3.19.0-25-generic-x86_64-with-Ubuntu-15.04-vivid
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 17, in <module>
    app.run()
  File "/home/tim/Development/Cura/cura/CuraApplication.py", line 162, in run
    self.setActiveMachine(machine)
  File "/home/tim/Development/Uranium/UM/Application.py", line 244, in setActiveMachine
    self.activeMachineChanged.emit()
  File "/home/tim/Development/Uranium/UM/Signal.py", line 96, in emit
    func(dest, *args, **kargs)
  File "/home/tim/Development/Cura/cura/CuraApplication.py", line 473, in _onActiveMachineChanged
    self._volume.rebuild()
  File "/home/tim/Development/Cura/cura/BuildVolume.py", line 78, in rebuild
    minW = -self._width / 2
TypeError: bad operand type for unary -: 'NoneType'

PS:
all repos are up to date, compiled and installed on the master branch...

**Comment by BagelOrb** [comment]
Solution:
remove contents of:
/home/tim/.local/share/cura/settings
/home/tim/.config/cura
