### ISSUE TITLE
On close: Cannot join thread that hasn't started

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#251]
Version: master
Platform: Linux-3.19.0-25-generic-x86_64-with-Ubuntu-15.04-vivid
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "/home/tim/Development/Uranium/UM/Qt/Bindings/MainWindow.py", line 131, in hideEvent
    Application.getInstance().windowClosed()
  File "/home/tim/Development/Uranium/UM/Qt/QtApplication.py", line 170, in windowClosed
    self.applicationShuttingDown.emit()
  File "/home/tim/Development/Uranium/UM/Signal.py", line 96, in emit
    func(dest, *args, **kargs)
  File "/home/tim/Development/Cura/cura/../plugins/USBPrinting/USBPrinterManager.py", line 59, in stop
    self._update_thread.join()
  File "/usr/lib/python3.4/threading.py", line 1055, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started

**Comment by nallath** [comment]
Fixed
