### ISSUE TITLE
Cura stopped working. Uninstall/reinstall produced error

### ISSUE THREAD

**Issue by johncasiello1337** [Ultimaker/Cura#256]
Cura stopped working. I uninstalled and reinstalled it.  Upon opening, this is the error I received:

Version: 15.06.03
Platform: Windows-8-6.2.9200
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 9, in <module>
  File "c:\dev\uranium\UM\Application.py", line 329, in getInstance
  File "c:\dev\cura\cura\CuraApplication.py", line 56, in __init__
  File "c:\dev\uranium\UM\Qt\QtApplication.py", line 48, in __init__
  File "c:\dev\uranium\UM\Application.py", line 67, in __init__
  File "c:\dev\uranium\UM\Preferences.py", line 56, in readFromFile
  File "c:\dev\uranium\UM\Preferences.py", line 122, in _loadFile
  File "c:\dev\python34\lib\configparser.py", line 672, in read
  File "c:\dev\python34\lib\configparser.py", line 1044, in _read
configparser.DuplicateSectionError: While reading from 'C:\\Users\\John/AppData/Local/cura\\cura.cfg' [line 18]: section 'general' already exists

**Comment by nallath** [comment]
Delete the .cfg file. This is fixed for the next release.
