### ISSUE TITLE
Crash. An uncaught exception has ocurred...

### ISSUE THREAD

**Issue by marianmoldovan** [Ultimaker/Cura#257]
Here is the error trace. It seem to happen when I copied the profiles for the BQ Hephestos i3 to the settings folder

Version: 15.06.03
Platform: Windows-8-6.2.9200
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 10, in <module>
  File "c:\dev\cura\cura\CuraApplication.py", line 179, in run
  File "c:\dev\uranium\UM\Application.py", line 246, in setActiveMachine
  File "c:\dev\uranium\UM\Signal.py", line 96, in emit
  File "c:\dev\uranium\UM\Scene\Platform.py", line 48, in _onActiveMachineChanged
  File "c:\dev\uranium\UM\Resources.py", line 50, in getPath
FileNotFoundError: Could not find resource ('hephestos_platform.stl',) in 4

**Comment by nallath** [comment]
You haven't copied everything. As it states in the error log, it also needs hephestos_platform.stl.
