### ISSUE TITLE
A fatal exception has occurred...

### ISSUE THREAD

**Issue by misalo1** [Ultimaker/Cura#3035]
Just stop working / re-installed and it give the same error.

Error Message:
Version: 2.3.1
Platform: Windows-Vista-6.0.6002-SP2
Qt: 5.5.1
PyQt: 5.5.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 61, in <module>
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Application.py", line 310, in getInstance
  File "D:\2.3\build\inst\lib\python3.4\site-packages\cura\CuraApplication.py", line 173, in __init__
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\QtApplication.py", line 94, in __init__
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 107, in upgrade
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 281, in _upgradeFile
MemoryError

**Comment by Ghostkeeper** [comment]
This was fixed in Cura 2.4. The workaround for 2.3 is to delete your `C:\Users\<you>\AppData\Local\cura\cura.log` file, which has gotten to big to open.
