### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Youness-e** [Ultimaker/Cura#3081]
Hello, 

I want to report a crash at initialization phase.

**Application Version**
3.1.0-1

**Platform**
Archlinux (cura installed from pacman)

**Qt**
5.10.0-2

**PyQt**
5.9.2-2

`Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.6/site-packages/cura/CrashHandler.py", line 20, in <module>
    from UM.Application import Application
  File "/usr/lib/python3.6/site-packages/UM/Application.py", line 15, in <module>
    from UM.Settings.ContainerRegistry import ContainerRegistry
  File "/usr/lib/python3.6/site-packages/UM/Settings/ContainerRegistry.py", line 36, in <module>
    import UM.Qt.QtApplication
  File "/usr/lib/python3.6/site-packages/UM/Qt/QtApplication.py", line 15, in <module>
    from UM.FileHandler.ReadFileJob import ReadFileJob
  File "/usr/lib/python3.6/site-packages/UM/FileHandler/ReadFileJob.py", line 5, in <module>
    from UM.Application import Application
ImportError: cannot import name 'Application'

Original exception was:
Traceback (most recent call last):
  File "/bin/cura", line 54, in <module>
    import Arcus #@UnusedImport
ImportError: libprotobuf.so.14: cannot open shared object file: No such file or directory
`

**Comment by Ghostkeeper** [comment]
You're missing Protobuf. Could you try using the AppImage from Ultimaker's website? That contains all necessary dependencies. It's also the only official release we make.
