### ISSUE TITLE
Get NoneType from self.getStorageDevice("LocalFileStorage")

### ISSUE THREAD

**Issue by derekhe** [Ultimaker/Cura#31]
ENV: Mac OS Yosemite, also Ubuntu 15.04 in virtualbox
When starting cura_app.py, CuraApplication.py line 145:

self.getStorageDevice("LocalFileStorage").removableDrivesChanged.connect(self._removableDrivesChanged)

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 2357, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1777, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "/Users/sche/dev/cura/Cura/cura_app.py", line 9, in <module>
    app.run()
  File "/Users/sche/dev/cura/Cura/cura/CuraApplication.py", line 145, in run
    self.getStorageDevice("LocalFileStorage").removableDrivesChanged.connect(self._removableDrivesChanged)
AttributeError: 'NoneType' object has no attribute 'removableDrivesChanged'
Traceback (most recent call last):

**Comment by derekhe** [comment]
I can disable this line and other lines about _removableDrivesChanged to get it working but I'm curious how other guys get it working. Is there anything missing?

**Comment by derekhe** [comment]
Fixed. The problem is Uranium's plugin is not installed correctly. Now fixed.
