### ISSUE TITLE
[3.2.1] Crash after startup: AttributeError: 'NoneType' object has no attribute in OpenGLContext.py

### ISSUE THREAD

**Issue by kuc** [Ultimaker/Cura#3432]
**Application Version**
3.2.1

**Platform**
Windows 10

**Display Driver**

- Intel HD Graphics 4000
- NVIDIA GeForce GT 630M

After selecting Intel graphics:
```
2018-03-03 19:18:26,453 - DEBUG - [(19652)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.65 s
2018-03-03 19:18:27,272 - DEBUG - [(19652)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.64 s
2018-03-03 19:18:27,636 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [64]: An uncaught error has occurred!
2018-03-03 19:18:27,639 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]: Traceback (most recent call last):
2018-03-03 19:18:27,642 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\Bindings\MainWindow.py", line 215, in _render
2018-03-03 19:18:27,644 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\QtRenderer.py", line 121, in beginRendering
2018-03-03 19:18:27,646 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\QtRenderer.py", line 183, in _initialize
2018-03-03 19:18:27,648 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\View\GL\OpenGLContext.py", line 60, in supportsVertexArrayObjects
2018-03-03 19:18:27,650 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\View\GL\OpenGLContext.py", line 46, in hasExtension
2018-03-03 19:18:27,652 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]: AttributeError: 'NoneType' object has no attribute 'hasExtension'
2018-03-03 19:18:28,422 - DEBUG - [(19652)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.63 s
2018-03-03 19:18:28,443 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [64]: An uncaught error has occurred!
2018-03-03 19:18:28,446 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]: Traceback (most recent call last):
2018-03-03 19:18:28,447 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\Bindings\MainWindow.py", line 215, in _render
2018-03-03 19:18:28,449 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\QtRenderer.py", line 121, in beginRendering
2018-03-03 19:18:28,451 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\QtRenderer.py", line 183, in _initialize
2018-03-03 19:18:28,453 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\View\GL\OpenGLContext.py", line 60, in supportsVertexArrayObjects
2018-03-03 19:18:28,456 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\View\GL\OpenGLContext.py", line 46, in hasExtension
2018-03-03 19:18:28,458 - CRITICAL - [(19652)-MainThread] cura.CrashHandler.__init__ [67]: AttributeError: 'NoneType' object has no attribute 'hasExtension'
```

After selecting NVIDIA graphics:
```
2018-03-03 19:10:59,307 - DEBUG - [(12644)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.64 s
2018-03-03 19:11:00,157 - DEBUG - [(12644)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.68 s
2018-03-03 19:11:00,510 - DEBUG - [(12644)-MainThread] UM.Qt.QtRenderer._initialize [184]: Support for Vertex Array Objects: True
2018-03-03 19:11:00,539 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [64]: An uncaught error has occurred!
2018-03-03 19:11:00,544 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]: Traceback (most recent call last):
2018-03-03 19:11:00,548 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\Bindings\MainWindow.py", line 215, in _render
2018-03-03 19:11:00,552 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\QtRenderer.py", line 121, in beginRendering
2018-03-03 19:11:00,554 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\QtRenderer.py", line 186, in _initialize
2018-03-03 19:11:00,556 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\View\GL\OpenGL.py", line 47, in __init__
2018-03-03 19:11:00,558 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]: AttributeError: 'NoneType' object has no attribute 'versionFunctions'
2018-03-03 19:11:01,334 - DEBUG - [(12644)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.64 s
2018-03-03 19:11:01,355 - DEBUG - [(12644)-MainThread] UM.Qt.QtRenderer._initialize [184]: Support for Vertex Array Objects: True
2018-03-03 19:11:01,358 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [64]: An uncaught error has occurred!
2018-03-03 19:11:01,360 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]: Traceback (most recent call last):
2018-03-03 19:11:01,362 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\Bindings\MainWindow.py", line 215, in _render
2018-03-03 19:11:01,364 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\QtRenderer.py", line 121, in beginRendering
2018-03-03 19:11:01,366 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\Qt\QtRenderer.py", line 186, in _initialize
2018-03-03 19:11:01,370 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]:   File "X:\3.2\build\inst\lib\python3.5\site-packages\UM\View\GL\OpenGL.py", line 47, in __init__
2018-03-03 19:11:01,372 - CRITICAL - [(12644)-MainThread] cura.CrashHandler.__init__ [67]: AttributeError: 'NoneType' object has no attribute 'versionFunctions'
```

Already tried https://github.com/Ultimaker/Cura/issues/2655#issuecomment-338460699 but it changes nothing for me.

**Comment by kuc** [comment]
Seems to be working after NVIDIA driver update.
