### ISSUE TITLE
Definitions version 2 crash Cura

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3478]
**Application Version**

master

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

Hi, I just merged the latest master branch and I now get this crash on startup, I can supply more info if you need but I'll just show you the console messages here...

````
2018-03-12 08:35:53,336 - DEBUG - [(140282623735552)-MainThread] cura.Machines.VariantManager.initialize [61]: Exclude variant [empty_variant]
2018-03-12 08:35:53,410 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2018-03-12 08:35:53,411 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2018-03-12 08:35:53,411 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/bin/cura", line 141, in <module>
2018-03-12 08:35:53,412 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]:     app.run()
2018-03-12 08:35:53,412 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/CuraApplication.py", line 755, in run
2018-03-12 08:35:53,412 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]:     self._quality_manager.initialize()
2018-03-12 08:35:53,412 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/Machines/QualityManager.py", line 140, in initialize
2018-03-12 08:35:53,412 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]:     machine_node.addQualityChangesMetadata(quality_type, metadata)
2018-03-12 08:35:53,413 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/Machines/QualityNode.py", line 35, in addQualityChangesMetadata
2018-03-12 08:35:53,413 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]:     quality_changes_group.addNode(QualityNode(metadata))
2018-03-12 08:35:53,413 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/Machines/QualityChangesGroup.py", line 18, in addNode
2018-03-12 08:35:53,413 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]:     raise RuntimeError("{group} tries to overwrite the existing node_for_global {original_global} with {new_global}".format(group = self, original_global = self.node_for_global, new_global = node))
2018-03-12 08:35:53,413 - CRITICAL - [(140282623735552)-MainThread] cura.CrashHandler.__init__ [69]: RuntimeError: QualityChangesGroup[<capture-switch-housing XL>, available = False] tries to overwrite the existing node_for_global QualityNode[kossel xl #2_capture-switch-housing xl] with QualityNode[kossel+xl+%232_fdmextruder_capture-switch-housing+xl]
2018-03-12 08:36:32,660 - INFO - [(140282623735552)-MainThread] cura.CrashHandler._sendCrashReport [418]: Sending crash report info to [https://stats.ultimaker.com/api/cura]...
Sending crash report info to [https://stats.ultimaker.com/api/cura]...
````

**Comment by smartavionics** [comment]
Here's the complete log file:

````
2018-03-12 10:09:29,866 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin FileLogger
2018-03-12 10:09:29,921 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin UpdateChecker
2018-03-12 10:09:29,929 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin ZOffsetPlugin
2018-03-12 10:09:29,935 - INFO - [(139759749388032)-Thread-1] UpdateChecker.UpdateCheckerJob.run [34]: Checking for new version of cura
2018-03-12 10:09:29,941 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin SliceInfoPlugin
2018-03-12 10:09:29,944 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin SolidView
2018-03-12 10:09:29,947 - WARNING - [(139760013985536)-MainThread] UFPWriter.<module> [10]: Could not import UFPWriter; libCharon may be missing
2018-03-12 10:09:29,949 - WARNING - [(139760013985536)-MainThread] UFPWriter.<module> [10]: Could not import UFPWriter; libCharon may be missing
2018-03-12 10:09:29,950 - ERROR - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [357]: Plugin UFPWriter did not return any objects to register
2018-03-12 10:09:29,954 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin ImageReader
2018-03-12 10:09:29,958 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin PerObjectSettingsTool
2018-03-12 10:09:29,963 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin RemovableDriveOutputDevice
2018-03-12 10:09:29,970 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin PostProcessingPlugin
2018-03-12 10:09:29,972 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin UserAgreementPlugin
2018-03-12 10:09:29,975 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin GCodeProfileReader
2018-03-12 10:09:29,983 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin PluginBrowser
2018-03-12 10:09:29,987 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin VersionUpgrade30to31
2018-03-12 10:09:29,990 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin VersionUpgrade22to24
2018-03-12 10:09:29,995 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin VersionUpgrade21to22
2018-03-12 10:09:29,998 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin VersionUpgrade27to30
2018-03-12 10:09:30,002 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin VersionUpgrade26to27
2018-03-12 10:09:30,006 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin VersionUpgrade25to26
2018-03-12 10:09:30,008 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin VersionUpgrade32to33
2018-03-12 10:09:30,023 - DEBUG - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [335]: Plugin USBPrinting was disabled
2018-03-12 10:09:30,027 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin PrepareStage
2018-03-12 10:09:30,028 - WARNING - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [325]: Plugin CuraEngineBackend was already loaded
2018-03-12 10:09:30,037 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin X3DReader
2018-03-12 10:09:30,040 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin AutoSave
2018-03-12 10:09:30,044 - DEBUG - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [335]: Plugin FirmwareUpdateChecker was disabled
2018-03-12 10:09:30,048 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin UCPWriter
2018-03-12 10:09:30,055 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin SimulationView
2018-03-12 10:09:30,061 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin XRayView
2018-03-12 10:09:30,065 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin MonitorStage
2018-03-12 10:09:30,071 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin XmlMaterialProfile
2018-03-12 10:09:30,127 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin UM3NetworkPrinting
2018-03-12 10:09:30,131 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin CuraProfileWriter
2018-03-12 10:09:30,139 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin 3MFReader
2018-03-12 10:09:30,143 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin GCodeWriter
2018-03-12 10:09:30,148 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin MachineSettingsAction
2018-03-12 10:09:30,155 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin UltimakerMachineActions
2018-03-12 10:09:30,165 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin GCodeReader
2018-03-12 10:09:30,169 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin LegacyProfileReader
2018-03-12 10:09:30,175 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin 3MFWriter
2018-03-12 10:09:30,180 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin ChangeLogPlugin
2018-03-12 10:09:30,184 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin SupportEraser
2018-03-12 10:09:30,188 - INFO - [(139760013985536)-MainThread] UM.PluginRegistry.loadPlugin [368]: Loaded plugin CuraProfileReader
2018-03-12 10:09:30,196 - INFO - [(139760013985536)-MainThread] UM.VersionUpgradeManager.upgrade [113]: Looking for old configuration files to upgrade.
2018-03-12 10:09:30,381 - DEBUG - [(139760013985536)-MainThread] UM.Backend.Backend._logSocketState [173]: Socket state changed to Listening
2018-03-12 10:09:30,386 - INFO - [(139760013985536)-MainThread] UM.Backend.Backend.startEngine [74]: Started engine process: /opt/cura/bin/CuraEngine
2018-03-12 10:09:30,386 - DEBUG - [(139760013985536)-MainThread] UM.Backend.Backend._backendLog [90]: [Backend] Calling engine with: ['/opt/cura/bin/CuraEngine', 'connect', '127.0.0.1:49674', '-j', '/opt/cura/share/cura/resources/definitions/fdmprinter.def.json', '']
2018-03-12 10:09:30,394 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] 
2018-03-12 10:09:30,395 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] Cura_SteamEngine version master
2018-03-12 10:09:30,397 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] Copyright (C) 2018 Ultimaker
2018-03-12 10:09:30,399 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] 
2018-03-12 10:09:30,400 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] This program is free software: you can redistribute it and/or modify
2018-03-12 10:09:30,400 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] it under the terms of the GNU Affero General Public License as published by
2018-03-12 10:09:30,401 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] the Free Software Foundation, either version 3 of the License, or
2018-03-12 10:09:30,401 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] (at your option) any later version.
2018-03-12 10:09:30,404 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] 
2018-03-12 10:09:30,404 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] This program is distributed in the hope that it will be useful,
2018-03-12 10:09:30,405 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] but WITHOUT ANY WARRANTY; without even the implied warranty of
2018-03-12 10:09:30,405 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
2018-03-12 10:09:30,405 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] GNU Affero General Public License for more details.
2018-03-12 10:09:30,406 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] 
2018-03-12 10:09:30,406 - DEBUG - [(139760013985536)-MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [empty_definition_changes] added.
2018-03-12 10:09:30,407 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] You should have received a copy of the GNU Affero General Public License
2018-03-12 10:09:30,407 - DEBUG - [(139758680393472)-Thread-9] UM.Backend.Backend._backendLog [90]: [Backend] along with this program.  If not, see <http://www.gnu.org/licenses/>.
2018-03-12 10:09:30,407 - DEBUG - [(139760013985536)-MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [empty_variant] added.
2018-03-12 10:09:30,408 - DEBUG - [(139760013985536)-MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [empty_material] added.
2018-03-12 10:09:30,409 - DEBUG - [(139760013985536)-MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [empty_quality] added.
2018-03-12 10:09:30,410 - DEBUG - [(139760013985536)-MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [empty_quality_changes] added.
2018-03-12 10:09:30,465 - WARNING - [(139760013985536)-MainThread] LocalContainerProvider.LocalContainerProvider._pathToMime [280]: MIME type could not be found for file: /opt/cura/share/cura/resources/definitions/fdmprinter.def.json.orig, ignoring it.
2018-03-12 10:09:30,615 - DEBUG - [(139760013985536)-MainThread] UM.Backend.Backend._logSocketState [177]: Socket state changed to Connected
2018-03-12 10:09:30,615 - DEBUG - [(139760013985536)-MainThread] UM.Backend.Backend._onSocketStateChanged [167]: Backend connected on port 49674
2018-03-12 10:09:32,499 - WARNING - [(139760013985536)-MainThread] UM.Preferences.getValue [81]: Tried to get the value of non-existing setting view/filter_current_build_plate.
2018-03-12 10:09:32,515 - DEBUG - [(139760013985536)-MainThread] cura.Scene.CuraSceneController.setActiveBuildPlate [103]: Select build plate: 0
2018-03-12 10:09:32,519 - DEBUG - [(139760013985536)-MainThread] cura.Machines.VariantManager.initialize [61]: Exclude variant [empty_variant]
2018-03-12 10:09:32,591 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2018-03-12 10:09:32,592 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2018-03-12 10:09:32,592 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/bin/cura", line 141, in <module>
2018-03-12 10:09:32,593 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]:     app.run()
2018-03-12 10:09:32,593 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/CuraApplication.py", line 755, in run
2018-03-12 10:09:32,593 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]:     self._quality_manager.initialize()
2018-03-12 10:09:32,593 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/Machines/QualityManager.py", line 140, in initialize
2018-03-12 10:09:32,593 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]:     machine_node.addQualityChangesMetadata(quality_type, metadata)
2018-03-12 10:09:32,594 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/Machines/QualityNode.py", line 35, in addQualityChangesMetadata
2018-03-12 10:09:32,594 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]:     quality_changes_group.addNode(QualityNode(metadata))
2018-03-12 10:09:32,594 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/Machines/QualityChangesGroup.py", line 18, in addNode
2018-03-12 10:09:32,594 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]:     raise RuntimeError("{group} tries to overwrite the existing node_for_global {original_global} with {new_global}".format(group = self, original_global = self.node_for_global, new_global = node))
2018-03-12 10:09:32,594 - CRITICAL - [(139760013985536)-MainThread] cura.CrashHandler.__init__ [69]: RuntimeError: QualityChangesGroup[<Kossel Mini (cold bed)>, available = False] tries to overwrite the existing node_for_global QualityNode[kossel_mini_mb_fdmextruder_kossel+mini+%28cold+bed%29] with QualityNode[kossel_mini_mb_kossel mini (cold bed)]
2018-03-12 10:09:52,353 - INFO - [(139760013985536)-MainThread] cura.CrashHandler._sendCrashReport [418]: Sending crash report info to [https://stats.ultimaker.com/api/cura]...
2018-03-12 10:09:52,613 - INFO - [(139760013985536)-MainThread] cura.CrashHandler._sendCrashReport [424]: Sent crash report info.
````

**Comment by smartavionics** [comment]
I updated Cura and Uranium repos again (at 1600 GMT 12th March) and I am now getting this on the console:
````
2018-03-12 15:58:46,662 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [51]: Loading container low
FAILED TO LOG:  e Exception: Error when loading container low not all arguments converted during string formatting
2018-03-12 15:58:46,666 - ERROR - [MainThread] UM.Logger.logException [85]: Traceback (most recent call last):
2018-03-12 15:58:46,666 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/opt/cura/lib/python3/dist-packages/UM/Settings/ContainerRegistry.py", line 178, in findContainers
2018-03-12 15:58:46,666 - ERROR - [MainThread] UM.Logger.logException [85]:     new_container = provider.loadContainer(metadata["id"])
2018-03-12 15:58:46,667 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/opt/cura/lib/uranium/plugins/LocalContainerProvider/LocalContainerProvider.py", line 61, in loadContainer
2018-03-12 15:58:46,667 - ERROR - [MainThread] UM.Logger.logException [85]:     container.deserialize(f.read())
2018-03-12 15:58:46,667 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/opt/cura/lib/python3/dist-packages/UM/Settings/InstanceContainer.py", line 496, in deserialize
2018-03-12 15:58:46,667 - ERROR - [MainThread] UM.Logger.logException [85]:     raise IncorrectInstanceVersionError("Reported version {0} but expected version {1}".format(str(parser_version), self.Version))
2018-03-12 15:58:46,668 - ERROR - [MainThread] UM.Logger.logException [85]: UM.Settings.InstanceContainer.IncorrectInstanceVersionError: Reported version 2 but expected version 3
2018-03-12 15:58:46,678 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2018-03-12 15:58:46,678 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2018-03-12 15:58:46,679 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/CuraApplication.py", line 925, in getQualityProfilesDropDownMenuModel
2018-03-12 15:58:46,679 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self._quality_profile_drop_down_menu_model = QualityProfilesDropDownMenuModel(self)
2018-03-12 15:58:46,679 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/Machines/Models/QualityProfilesDropDownMenuModel.py", line 47, in __init__
2018-03-12 15:58:46,679 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self._update()
2018-03-12 15:58:46,680 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/Machines/Models/QualityProfilesDropDownMenuModel.py", line 70, in _update
2018-03-12 15:58:46,680 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     layer_height = self._fetchLayerHeight(quality_group)
2018-03-12 15:58:46,680 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/Machines/Models/QualityProfilesDropDownMenuModel.py", line 97, in _fetchLayerHeight
2018-03-12 15:58:46,681 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     container = quality_group.node_for_global.getContainer()
2018-03-12 15:58:46,681 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/Machines/ContainerNode.py", line 43, in getContainer
2018-03-12 15:58:46,682 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     raise RuntimeError("Failed to lazy-load container [%s], cannot find it" % container_id)
2018-03-12 15:58:46,682 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: RuntimeError: Failed to lazy-load container [low], cannot find it
2018-03-12 15:58:47,169 - DEBUG - [MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [353]: Checking 2 stacks for errors took 0.45 s
2018-03-12 15:58:47,170 - INFO - [MainThread] cura.Machines.MaterialManager._updateMaps [218]: Updating material lookup data ...
2018-03-12 15:58:47,228 - DEBUG - [MainThread] cura.Machines.QualityManager.initialize [142]: Lookup tables updated.
2018-03-12 15:58:47,228 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [15]: Updating CustomQualityProfilesDropDownMenuModel.
2018-03-12 15:58:47,229 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [50]: Updating QualityProfilesDropDownMenuModel.
2018-03-12 15:58:47,229 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [coarse]
2018-03-12 15:58:47,230 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [draft]
2018-03-12 15:58:47,230 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [extra_coarse]
2018-03-12 15:58:47,231 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [fast]
2018-03-12 15:58:47,231 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [high]
2018-03-12 15:58:47,232 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [low]
2018-03-12 15:58:47,232 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [51]: Loading container low
FAILED TO LOG:  e Exception: Error when loading container low not all arguments converted during string formatting
2018-03-12 15:58:47,235 - ERROR - [MainThread] UM.Logger.logException [85]: Traceback (most recent call last):
2018-03-12 15:58:47,235 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/opt/cura/lib/python3/dist-packages/UM/Settings/ContainerRegistry.py", line 178, in findContainers
2018-03-12 15:58:47,235 - ERROR - [MainThread] UM.Logger.logException [85]:     new_container = provider.loadContainer(metadata["id"])
2018-03-12 15:58:47,235 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/opt/cura/lib/uranium/plugins/LocalContainerProvider/LocalContainerProvider.py", line 61, in loadContainer
2018-03-12 15:58:47,235 - ERROR - [MainThread] UM.Logger.logException [85]:     container.deserialize(f.read())
2018-03-12 15:58:47,235 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/opt/cura/lib/python3/dist-packages/UM/Settings/InstanceContainer.py", line 496, in deserialize
2018-03-12 15:58:47,236 - ERROR - [MainThread] UM.Logger.logException [85]:     raise IncorrectInstanceVersionError("Reported version {0} but expected version {1}".format(str(parser_version), self.Version))
2018-03-12 15:58:47,236 - ERROR - [MainThread] UM.Logger.logException [85]: UM.Settings.InstanceContainer.IncorrectInstanceVersionError: Reported version 2 but expected version 3
2018-03-12 15:59:51,535 - INFO - [MainThread] cura.CrashHandler._sendCrashReport [418]: Sending crash report info to [https://stats.ultimaker.com/api/cura]...
Sending crash report info to [https://stats.ultimaker.com/api/cura]...

2018-03-12 15:59:51,783 - INFO - [MainThread] cura.CrashHandler._sendCrashReport [424]: Sent crash report info.
Sent crash report info.

````

**Comment by ianpaschal** [comment]
This is because some of your printer definitions are version 2 but we've upgraded to version 3.

If you search for:
```
[general]
version = 2
```

And find any version 2s, they should be changed to:
```
[general]
version = 3
```

**Comment by smartavionics** [comment]
Hi Ian, thanks for that. I can see that files in definition_changes, quality and user have version = 2 right now. Do I change all of those to have 3? Thanks.

**Comment by ianpaschal** [comment]
Hmm I believe so. The person who would know for sure is @diegopradogesto because this is related to the new feature he was working on for the last 2 weeks.

I encountered the same yesterday afternoon and just manually changed my files but we should really make the change in the repo I guess. Sooooooo.... bug label!

**Comment by ianpaschal** [comment]
Evidently they are updated in Uranium so your crash is probably coming from some custom files?

**Comment by diegopradogesto** [comment]
It's not because of the new feature I'm working on but on Friday the version of the instance containers were changed. We realize today that we miss one version number in the empty container but @Ghostkeeper just fix it in d4688fd84c8a9f13e0155c643c58d3e5065aac26.

Try to pull again and try. @smartavionics also remember to check if you have any custom instance container with version number 2 and change them into version number 3.

**Comment by ianpaschal** [comment]
Ah my mistake! Thanks Diego!

**Comment by fieldOfView** [comment]
But there will be a VersionUpgrade to update custom files (as long as they are not read-only), right?

**Comment by smartavionics** [comment]
OK, I've got it running again. What was causing the crash was one (or both) of these files:

cura/resources/quality/ultimaker2/um2_low.inst.cfg 

cura/resources/quality/low.inst.cfg 

I removed them and it worked again.

**Comment by Ghostkeeper** [comment]
> But there will be a VersionUpgrade to update custom files (as long as they are not read-only), right?

We upgrade everything except quality profiles and definition files at the moment.
