### ISSUE TITLE
Run Cura from source on Mac error

### ISSUE THREAD

**Issue by kirilledelman** [Ultimaker/Cura#3565]
Tried running Cura from source by following instructions exactly in
[https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source-on-macOS](https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source-on-macOS)

first run got 
```
$ python cura_app.py

Traceback (most recent call last):
  File "cura_app.py", line 10, in <module>
    from UM.Platform import Platform
  File "/Users/kirilledelman/Uranium/UM/Platform.py", line 17
    def isOSX(cls) -> bool:
                   ^
SyntaxError: invalid syntax
```
Looks like the instructions to make python 3.6.4 default didn't take.
Running 
```
$ python3.6 cura_app.py

Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/kirilledelman/Cura/cura/CrashHandler.py", line 22, in <module>
    from UM.Application import Application
  File "/Users/kirilledelman/Uranium/UM/Application.py", line 15, in <module>
    from UM.Settings.ContainerRegistry import ContainerRegistry
  File "/Users/kirilledelman/Uranium/UM/Settings/ContainerRegistry.py", line 37, in <module>
    import UM.Qt.QtApplication
  File "/Users/kirilledelman/Uranium/UM/Qt/QtApplication.py", line 17, in <module>
    from UM.Application import Application
ImportError: cannot import name 'Application'

Original exception was:
Traceback (most recent call last):
  File "cura_app.py", line 127, in <module>
    import Arcus #@UnusedImport
ModuleNotFoundError: No module named 'Arcus'
```
I followed setup directions exactly, and got no errors up to this point.

**Comment by ianpaschal** [comment]
Hey, cool that you're looking to run from source!

Sorry the wiki instructions aren't working quite right. I need to add a disclaimer that with everyone's different system configurations it's always possible that stuff doesn't work.

My guess is that actually the whole virtual environments thing didn't take (for whatever reason) and therefore libArcus is built for Python 2.7 instead of 3.6.4.

So I would review those steps actually. Also, did you run `workon [virtualenv name]` before building libArcus to ensure it's built for the right version?

**Comment by kirilledelman** [comment]
@ianpaschal 
Thanks for your reply.
To be honest, I was looking to run from source because I couldn't get it to compile:
https://github.com/Ultimaker/cura-build/issues/176

I did run `workon Python_3.6.4-PyQt_5.8.2` before Arcus, and remember that name becoming part of the prompt for the duration of the process.

**Comment by GregValiant** [comment]
Hello
This likely much out of date.  Can this be closed?
