### ISSUE TITLE
Cura 3.2.1 doesn't keep settings from 3.1

### ISSUE THREAD

**Issue by Zer0t3ch** [Ultimaker/Cura#3581]
**Application Version**
3.2.1

**Platform**
Windows 10 (build 1709)

**Display Driver**
NVidia 3.9.1.35 (GTX 970)

**Printer**
Not relevant, I think. But I can figure out how to get it if it's really necessary.

**Steps to Reproduce**
1. Install Cura 3.1
2. Modify program settings and/or configure a printer with profiles
3. Install Cura 3.2.1

**Actual Results**
Cura 3.2.1 launches with seemingly factory presets

**Expected results**
Cura 3.2.1 should launch with the changes made in 3.1

**Comment by jackha** [comment]
Could you try this with 3.3 Beta? And it is actually handy to know what settings / profiles are not transferred. Ideally provide us with your 3.1 folder so we can debug more easily.

**Comment by Zer0t3ch** [comment]
Settings also weren't brought in when installing 3.3b.

[Here's my 3.1 folder](https://www.amazon.com/clouddrive/share/giHHSt2M54LakYemqNtLwSxIFpSVbhWOxO8OSOlzkyZ)

**Comment by Zer0t3ch** [comment]
@jackha Dunno if you saw I commented. Any clue what the issue could be?

**Comment by Ghostkeeper** [comment]
Yeah, opening Cura 3.3 using that folder results in the following error:

    2018-05-01 15:20:35,110 - ERROR - [MainThread] UM.Settings.ContainerStack.getConfigurationTypeFromSerialized [328]: Could not get configuration type: File contains no section headers.
    file: '<string>', line: 1
    '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
    2018-05-01 15:20:35,113 - ERROR - [MainThread] UM.Settings.ContainerStack.getConfigurationTypeFromSerialized [328]: Could not get configuration type: File contains no section headers.
    file: '<string>', line: 1
    '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
    2018-05-01 15:20:35,116 - DEBUG - [MainThread] UM.Settings.ContainerStack.getVersionFromSerialized [341]: Could not get version from serialized: None
    2018-05-01 15:20:35,136 - ERROR - [MainThread] UM.Logger.logException [81]: Exception: Unable to deserialize metadata for container /home/ruben/.local/share/cura/3.3/machine_instances/Anet+A8.global.cfg: Anet A8: File contains no section headers.
    file: '<string>', line: 1
    '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
    2018-05-01 15:20:35,142 - ERROR - [MainThread] UM.Logger.logException [85]: Traceback (most recent call last):
    2018-05-01 15:20:35,145 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/tmp/.mount_AYi3kt/usr/bin/plugins/plugins/LocalContainerProvider/LocalContainerProvider.py", line 120, in loadMetadata
    2018-05-01 15:20:35,148 - ERROR - [MainThread] UM.Logger.logException [85]:     result_metadatas = clazz.deserializeMetadata(f.read(), container_id) #pylint: disable=no-member
    2018-05-01 15:20:35,151 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/build/3.3/build/inst/lib/python3.5/site-packages/UM/Settings/ContainerStack.py", line 413, in deserializeMetadata
    2018-05-01 15:20:35,157 - DEBUG - [Thread-2] UM3NetworkPrinting.UM3OutputDevicePlugin._onServiceChanged [306]: Bonjour service added: ultimakersystem-ccbdd3002f37._ultimaker._tcp.local.
    2018-05-01 15:20:35,168 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/build/env/3.3/inst/lib/python3.5/configparser.py", line 720, in read_string
    2018-05-01 15:20:35,171 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/build/env/3.3/inst/lib/python3.5/configparser.py", line 715, in read_file
    2018-05-01 15:20:35,183 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/build/env/3.3/inst/lib/python3.5/configparser.py", line 1077, in _read
    2018-05-01 15:20:35,186 - ERROR - [MainThread] UM.Logger.logException [85]: configparser.MissingSectionHeaderError: File contains no section headers.
    2018-05-01 15:20:35,189 - ERROR - [MainThread] UM.Logger.logException [85]: file: '<string>', line: 1
    2018-05-01 15:20:35,203 - ERROR - [MainThread] UM.Logger.logException [85]: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
    2018-05-01 15:20:35,378 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
    2018-05-01 15:20:35,382 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
    2018-05-01 15:20:35,385 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/tmp/.mount_AYi3kt/usr/bin/plugins/plugins/LocalContainerProvider/LocalContainerProvider.py", line 120, in loadMetadata
    2018-05-01 15:20:35,392 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     result_metadatas = clazz.deserializeMetadata(f.read(), container_id) #pylint: disable=no-member
    2018-05-01 15:20:35,395 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/build/3.3/build/inst/lib/python3.5/site-packages/UM/Settings/ContainerStack.py", line 413, in deserializeMetadata
    2018-05-01 15:20:35,398 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/build/env/3.3/inst/lib/python3.5/configparser.py", line 720, in read_string
    2018-05-01 15:20:35,401 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/build/env/3.3/inst/lib/python3.5/configparser.py", line 715, in read_file
    2018-05-01 15:20:35,407 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/build/env/3.3/inst/lib/python3.5/configparser.py", line 1077, in _read
    2018-05-01 15:20:35,410 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: configparser.MissingSectionHeaderError: File contains no section headers.
    2018-05-01 15:20:35,413 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: file: '<string>', line: 1
    2018-05-01 15:20:35,416 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
    2018-05-01 15:20:35,419 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: 
    2018-05-01 15:20:35,422 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: During handling of the above exception, another exception occurred:
    2018-05-01 15:20:35,425 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
    2018-05-01 15:20:35,428 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
    2018-05-01 15:20:35,431 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
    2018-05-01 15:20:35,434 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
    2018-05-01 15:20:35,441 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
    2018-05-01 15:20:35,444 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/build/env/3.3/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
    2018-05-01 15:20:35,447 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
    2018-05-01 15:20:35,450 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
    2018-05-01 15:20:35,453 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
    2018-05-01 15:20:35,456 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
    2018-05-01 15:20:35,477 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/build/env/3.3/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
    2018-05-01 15:20:35,480 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
    2018-05-01 15:20:35,483 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
    2018-05-01 15:20:35,486 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
    2018-05-01 15:20:35,489 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
    2018-05-01 15:20:35,491 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/build/3.3/build/inst/bin/cura", line 140, in <module>
    2018-05-01 15:20:35,494 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/build/3.3/build/inst/lib/python3.5/site-packages/UM/Application.py", line 340, in getInstance
    2018-05-01 15:20:35,497 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/build/3.3/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 346, in __init__
    2018-05-01 15:20:35,500 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/build/3.3/build/inst/lib/python3.5/site-packages/UM/Settings/ContainerRegistry.py", line 309, in loadAllMetadata
    2018-05-01 15:20:35,504 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/tmp/.mount_AYi3kt/usr/bin/plugins/plugins/LocalContainerProvider/LocalContainerProvider.py", line 126, in loadMetadata
    2018-05-01 15:20:35,506 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     raise RuntimeError("Unable to deserialize metadata for container {filename}: {container_id}: {error_msg}".format(filename = filename, container_id = container_id, error_msg = str(e)))
    2018-05-01 15:20:35,509 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: RuntimeError: Unable to deserialize metadata for container /home/ruben/.local/share/cura/3.3/machine_instances/Anet+A8.global.cfg: Anet A8: File contains no section headers.
    2018-05-01 15:20:35,512 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: file: '<string>', line: 1
    2018-05-01 15:20:35,515 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

This indicates that your files are corrupt. We've seen a lot of crash reports regarding this, but we still haven't been able to reproduce this bug ourselves.

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/3561
