### ISSUE TITLE
[3.3.0] Crash when selecting Velleman materials

### ISSUE THREAD

**Issue by velbn** [Ultimaker/Cura#3712]
**Application Version**
3.3.0

**Platform**
Windows 7

**Printer**
Vertex Delta

**Steps to Reproduce**
Selecting any Velleman material

**Actual Results**
Crash with no error

**Expected results**
The material loaded

**Additional Information**
[cura_log_crash.zip](https://github.com/Ultimaker/Cura/files/1946116/cura_log_crash.zip)

**Comment by velbn** [comment]
Yeah
I accidently hitted the wrong button will fill in the info ;)

**Comment by Vandrasc** [comment]
Confirmed, Cura crashes when Velleman material is being selected when the Vertex Delta is active.

2018-04-25 10:40:32,175 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2018-04-25 10:40:32,187 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2018-04-25 10:40:32,197 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "X:\3.3\build\inst\lib\python3.5\site-packages\cura\Machines\Models\QualityProfilesDropDownMenuModel.py", line 70, in _update
2018-04-25 10:40:32,222 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "X:\3.3\build\inst\lib\python3.5\site-packages\cura\Machines\Models\QualityProfilesDropDownMenuModel.py", line 97, in _fetchLayerHeight
2018-04-25 10:40:32,233 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: AttributeError: 'NoneType' object has no attribute 'getContainer'

**Comment by Vandrasc** [comment]
Hi @velbn, it seems that the quality_type extreme gives some issues, but if you change the quality_type from extreme to draft it should fix the problem. 

![1](https://user-images.githubusercontent.com/26549794/39236419-2c2306c2-4879-11e8-82d7-3147e9dc4937.png)

Could you please make a PR? 

Thank you!

**Comment by velbn** [comment]
@Vandrasc by changing the quality_type parameter it should be fixed? Is there maybe a list of names you can only use for that parameter?

**Comment by LipuFei** [comment]
For Dev, JIRA ticket: CURA-5284

**Comment by LipuFei** [comment]
Hi @velbn , it's not correct with the builtin qualities for Vertex Delta K8800 with Velleman materials. I'm working on a fix now.

**Comment by LipuFei** [comment]
Should be fixed by a6b62656c797b07adadf3ade9e341782310d465f

**Comment by Vandrasc** [comment]
Fixed :)
