### ISSUE TITLE
Unable to update firmware

### ISSUE THREAD

**Issue by iakapulko** [Ultimaker/Cura#390]
Version: 15.09.81
Platform: Windows-7-6.1.7601-SP1
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "c:\dev\uranium\UM\Qt\Bindings\ExtensionModel.py", line 47, in subMenuTriggered
  File "c:\dev\uranium\UM\Extension.py", line 34, in activateMenuItem
  File "C:\Program Files (x86)\Cura_15.09.81\plugins\USBPrinting\USBPrinterManager.py", line 89, in updateAllFirmware
    self._printer_connections[printer_connection].updateFirmware(Resources.getPath(Application.ResourceTypes.Firmware, self._getDefaultFirmwareName()))
AttributeError: type object 'Application' has no attribute 'ResourceTypes'
![error](https://cloud.githubusercontent.com/assets/14235058/9837597/5d46e984-5a66-11e5-9dd0-be70de2071f4.jpg)

**Comment by nallath** [comment]
Should be fixed for next release.
