### ISSUE TITLE
cura crashes while adding fdm printer or printer based on it

### ISSUE THREAD

**Issue by bzed** [Ultimaker/Cura#3932]
**Application Version**
3.2, 3.4, master

**Platform**
debian testing/unstable

**Printer**
custom fdm, cr10 S4 and some other random picked printers based on fdm

**Steps to Reproduce**
Add new printer -> choose a non-ultimaker one -. OK

**Actual Results**
cura crashes, output is pasted below

**Expected results**
cura should not crash and add the printer :) Adding Ultimaker printers works just fine.

**Additional Information**

```
2018-06-13 21:47:14,500 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container custom_extruder_1
2018-06-13 21:47:14,527 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_1] added.
2018-06-13 21:47:14,549 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_1 #2_settings] added.
2018-06-13 21:47:14,549 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_1 #2_user] added.
2018-06-13 21:47:14,550 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [74]: Extruder[custom_extruder_1 #2] added to [Custom FDM printer] at position [0]
2018-06-13 21:47:14,550 - WARNING - [MainThread] cura.Settings.GlobalStack.addExtruder [70]: Extruder [custom_extruder_1 #2] has already been added to this stack [Custom FDM printer]
2018-06-13 21:47:14,554 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_1 #2] added.
2018-06-13 21:47:14,554 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container custom_extruder_2
2018-06-13 21:47:14,583 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_2] added.
2018-06-13 21:47:14,605 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_2 #2_settings] added.
2018-06-13 21:47:14,605 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_2 #2_user] added.
2018-06-13 21:47:14,606 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [74]: Extruder[custom_extruder_2 #2] added to [Custom FDM printer] at position [1]
2018-06-13 21:47:14,606 - WARNING - [MainThread] cura.Settings.GlobalStack.addExtruder [70]: Extruder [custom_extruder_2 #2] has already been added to this stack [Custom FDM printer]
2018-06-13 21:47:14,610 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_2 #2] added.
2018-06-13 21:47:14,610 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container custom_extruder_3
2018-06-13 21:47:14,639 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_3] added.
2018-06-13 21:47:14,661 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_3 #2_settings] added.
2018-06-13 21:47:14,662 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_3 #2_user] added.
2018-06-13 21:47:14,662 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [74]: Extruder[custom_extruder_3 #2] added to [Custom FDM printer] at position [2]
2018-06-13 21:47:14,662 - WARNING - [MainThread] cura.Settings.GlobalStack.addExtruder [70]: Extruder [custom_extruder_3 #2] has already been added to this stack [Custom FDM printer]
2018-06-13 21:47:14,666 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_3 #2] added.
2018-06-13 21:47:14,666 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container custom_extruder_4
2018-06-13 21:47:14,698 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_4] added.
2018-06-13 21:47:14,723 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_4 #2_settings] added.
2018-06-13 21:47:14,724 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_4 #2_user] added.
2018-06-13 21:47:14,724 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [74]: Extruder[custom_extruder_4 #2] added to [Custom FDM printer] at position [3]
2018-06-13 21:47:14,724 - WARNING - [MainThread] cura.Settings.GlobalStack.addExtruder [70]: Extruder [custom_extruder_4 #2] has already been added to this stack [Custom FDM printer]
2018-06-13 21:47:14,728 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_4 #2] added.
2018-06-13 21:47:14,728 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container custom_extruder_5
2018-06-13 21:47:14,759 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_5] added.
2018-06-13 21:47:14,779 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_5 #2_settings] added.
2018-06-13 21:47:14,780 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_5 #2_user] added.
2018-06-13 21:47:14,781 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [74]: Extruder[custom_extruder_5 #2] added to [Custom FDM printer] at position [4]
2018-06-13 21:47:14,781 - WARNING - [MainThread] cura.Settings.GlobalStack.addExtruder [70]: Extruder [custom_extruder_5 #2] has already been added to this stack [Custom FDM printer]
2018-06-13 21:47:14,785 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_5 #2] added.
2018-06-13 21:47:14,785 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container custom_extruder_6
2018-06-13 21:47:14,812 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_6] added.
2018-06-13 21:47:14,832 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_6 #2_settings] added.
2018-06-13 21:47:14,833 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_6 #2_user] added.
2018-06-13 21:47:14,833 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [74]: Extruder[custom_extruder_6 #2] added to [Custom FDM printer] at position [5]
2018-06-13 21:47:14,834 - WARNING - [MainThread] cura.Settings.GlobalStack.addExtruder [70]: Extruder [custom_extruder_6 #2] has already been added to this stack [Custom FDM printer]
2018-06-13 21:47:14,838 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_6 #2] added.
2018-06-13 21:47:14,838 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container custom_extruder_7
2018-06-13 21:47:14,865 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_7] added.
2018-06-13 21:47:14,885 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_7 #2_settings] added.
2018-06-13 21:47:14,886 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_7 #2_user] added.
2018-06-13 21:47:14,886 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [74]: Extruder[custom_extruder_7 #2] added to [Custom FDM printer] at position [6]
2018-06-13 21:47:14,887 - WARNING - [MainThread] cura.Settings.GlobalStack.addExtruder [70]: Extruder [custom_extruder_7 #2] has already been added to this stack [Custom FDM printer]
2018-06-13 21:47:14,891 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_7 #2] added.
2018-06-13 21:47:14,891 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container custom_extruder_8
2018-06-13 21:47:14,918 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_8] added.
2018-06-13 21:47:14,940 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_8 #2_settings] added.
2018-06-13 21:47:14,941 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_8 #2_user] added.
2018-06-13 21:47:14,942 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [74]: Extruder[custom_extruder_8 #2] added to [Custom FDM printer] at position [7]
2018-06-13 21:47:14,942 - WARNING - [MainThread] cura.Settings.GlobalStack.addExtruder [70]: Extruder [custom_extruder_8 #2] has already been added to this stack [Custom FDM printer]
2018-06-13 21:47:14,946 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [custom_extruder_8 #2] added.
2018-06-13 21:47:14,947 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [normal]
2018-06-13 21:47:14,947 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container normal
2018-06-13 21:47:14,949 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [normal] added.
2018-06-13 21:47:14,955 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [Custom FDM printer] added.
2018-06-13 21:47:14,956 - DEBUG - [MainThread] cura.Machines.Models.GenericMaterialsModel._update [23]: Updating GenericMaterialsModel.
2018-06-13 21:47:14,956 - DEBUG - [MainThread] cura.Machines.Models.BrandMaterialsModel._update [70]: Updating BrandMaterialsModel.
2018-06-13 21:47:15,140 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [15]: Updating CustomQualityProfilesDropDownMenuModel.
2018-06-13 21:47:15,141 - INFO - [MainThread] cura.Machines.QualityManager.getQualityChangesGroups [186]: Cannot find node for machine def [fdmprinter] in QualityChanges lookup table
2018-06-13 21:47:15,141 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [50]: Updating QualityProfilesDropDownMenuModel.
2018-06-13 21:47:15,141 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [coarse]
2018-06-13 21:47:15,142 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container coarse
2018-06-13 21:47:15,144 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [coarse] added.
2018-06-13 21:47:15,156 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [draft]
2018-06-13 21:47:15,156 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container draft
2018-06-13 21:47:15,159 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [draft] added.
2018-06-13 21:47:15,171 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [extra_coarse]
2018-06-13 21:47:15,171 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container extra_coarse
2018-06-13 21:47:15,173 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [extra_coarse] added.
2018-06-13 21:47:15,185 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [fast]
2018-06-13 21:47:15,186 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container fast
2018-06-13 21:47:15,188 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [fast] added.
2018-06-13 21:47:15,220 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [high]
2018-06-13 21:47:15,220 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container high
2018-06-13 21:47:15,222 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [355]: Container [high] added.
2018-06-13 21:47:15,235 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [low]
2018-06-13 21:47:15,236 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container low
FAILED TO LOG:  e Exception: Error when loading container low not all arguments converted during string formatting
2018-06-13 21:47:15,238 - ERROR - [MainThread] UM.Logger.logException [85]: Traceback (most recent call last):
2018-06-13 21:47:15,238 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/usr/local/lib/python3/dist-packages/UM/Settings/ContainerRegistry.py", line 178, in findContainers
2018-06-13 21:47:15,239 - ERROR - [MainThread] UM.Logger.logException [85]:     new_container = provider.loadContainer(metadata["id"])
2018-06-13 21:47:15,239 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/usr/local/lib/uranium/plugins/LocalContainerProvider/LocalContainerProvider.py", line 63, in loadContainer
2018-06-13 21:47:15,239 - ERROR - [MainThread] UM.Logger.logException [85]:     container.deserialize(f.read())
2018-06-13 21:47:15,239 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/usr/local/lib/python3/dist-packages/UM/Settings/InstanceContainer.py", line 496, in deserialize
2018-06-13 21:47:15,239 - ERROR - [MainThread] UM.Logger.logException [85]:     raise IncorrectInstanceVersionError("Reported version {0} but expected version {1}".format(str(parser_version), self.Version))
2018-06-13 21:47:15,240 - ERROR - [MainThread] UM.Logger.logException [85]: UM.Settings.InstanceContainer.IncorrectInstanceVersionError: Reported version 2 but expected version 3
2018-06-13 21:47:15,251 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2018-06-13 21:47:15,251 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2018-06-13 21:47:15,251 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/cura/Machines/Models/QualityProfilesDropDownMenuModel.py", line 70, in _update
2018-06-13 21:47:15,252 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     layer_height = self._fetchLayerHeight(quality_group)
2018-06-13 21:47:15,252 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/cura/Machines/Models/QualityProfilesDropDownMenuModel.py", line 97, in _fetchLayerHeight
2018-06-13 21:47:15,252 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     container = quality_group.node_for_global.getContainer()
2018-06-13 21:47:15,253 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/cura/Machines/ContainerNode.py", line 43, in getContainer
2018-06-13 21:47:15,253 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     raise RuntimeError("Failed to lazy-load container [%s], cannot find it" % container_id)
2018-06-13 21:47:15,253 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: RuntimeError: Failed to lazy-load container [low], cannot find it
2018-06-13 21:47:15,316 - DEBUG - [MainThread] cura.Machines.Models.GenericMaterialsModel._update [23]: Updating GenericMaterialsModel.
2018-06-13 21:47:15,318 - DEBUG - [MainThread] cura.Machines.Models.BrandMaterialsModel._update [70]: Updating BrandMaterialsModel.
2018-06-13 21:47:15,333 - DEBUG - [MainThread] cura.Machines.Models.NozzleModel._update [32]: Updating NozzleModel.
2018-06-13 21:47:15,333 - DEBUG - [MainThread] cura.Machines.Models.BuildPlateModel._update [33]: Updating BuildPlateModel.
2018-06-13 21:47:15,334 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [15]: Updating CustomQualityProfilesDropDownMenuModel.
2018-06-13 21:47:15,335 - INFO - [MainThread] cura.Machines.QualityManager.getQualityChangesGroups [186]: Cannot find node for machine def [fdmprinter] in QualityChanges lookup table
2018-06-13 21:47:15,335 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [50]: Updating QualityProfilesDropDownMenuModel.
2018-06-13 21:47:15,336 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [low]
2018-06-13 21:47:15,336 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container low
FAILED TO LOG:  e Exception: Error when loading container low not all arguments converted during string formatting
2018-06-13 21:47:15,338 - ERROR - [MainThread] UM.Logger.logException [85]: Traceback (most recent call last):
2018-06-13 21:47:15,339 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/usr/local/lib/python3/dist-packages/UM/Settings/ContainerRegistry.py", line 178, in findContainers
2018-06-13 21:47:15,339 - ERROR - [MainThread] UM.Logger.logException [85]:     new_container = provider.loadContainer(metadata["id"])
2018-06-13 21:47:15,339 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/usr/local/lib/uranium/plugins/LocalContainerProvider/LocalContainerProvider.py", line 63, in loadContainer
2018-06-13 21:47:15,339 - ERROR - [MainThread] UM.Logger.logException [85]:     container.deserialize(f.read())
2018-06-13 21:47:15,339 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/usr/local/lib/python3/dist-packages/UM/Settings/InstanceContainer.py", line 496, in deserialize
2018-06-13 21:47:15,340 - ERROR - [MainThread] UM.Logger.logException [85]:     raise IncorrectInstanceVersionError("Reported version {0} but expected version {1}".format(str(parser_version), self.Version))
2018-06-13 21:47:15,340 - ERROR - [MainThread] UM.Logger.logException [85]: UM.Settings.InstanceContainer.IncorrectInstanceVersionError: Reported version 2 but expected version 3
2018-06-13 21:47:15,340 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2018-06-13 21:47:15,340 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2018-06-13 21:47:15,341 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/cura/Machines/Models/QualityProfilesDropDownMenuModel.py", line 70, in _update
2018-06-13 21:47:15,341 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     layer_height = self._fetchLayerHeight(quality_group)
2018-06-13 21:47:15,341 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/cura/Machines/Models/QualityProfilesDropDownMenuModel.py", line 97, in _fetchLayerHeight
2018-06-13 21:47:15,341 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     container = quality_group.node_for_global.getContainer()
2018-06-13 21:47:15,341 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/cura/Machines/ContainerNode.py", line 43, in getContainer
2018-06-13 21:47:15,341 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     raise RuntimeError("Failed to lazy-load container [%s], cannot find it" % container_id)
2018-06-13 21:47:15,342 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: RuntimeError: Failed to lazy-load container [low], cannot find it
2018-06-13 21:47:15,406 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [15]: Updating CustomQualityProfilesDropDownMenuModel.
2018-06-13 21:47:15,406 - INFO - [MainThread] cura.Machines.QualityManager.getQualityChangesGroups [186]: Cannot find node for machine def [fdmprinter] in QualityChanges lookup table
2018-06-13 21:47:15,406 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [50]: Updating QualityProfilesDropDownMenuModel.
2018-06-13 21:47:15,407 - INFO - [MainThread] cura.Machines.ContainerNode.getContainer [39]: Lazy-loading container [low]
2018-06-13 21:47:15,407 - DEBUG - [MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [53]: Loading container low
FAILED TO LOG:  e Exception: Error when loading container low not all arguments converted during string formatting
2018-06-13 21:47:15,409 - ERROR - [MainThread] UM.Logger.logException [85]: Traceback (most recent call last):
2018-06-13 21:47:15,410 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/usr/local/lib/python3/dist-packages/UM/Settings/ContainerRegistry.py", line 178, in findContainers
2018-06-13 21:47:15,410 - ERROR - [MainThread] UM.Logger.logException [85]:     new_container = provider.loadContainer(metadata["id"])
2018-06-13 21:47:15,410 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/usr/local/lib/uranium/plugins/LocalContainerProvider/LocalContainerProvider.py", line 63, in loadContainer
2018-06-13 21:47:15,410 - ERROR - [MainThread] UM.Logger.logException [85]:     container.deserialize(f.read())
2018-06-13 21:47:15,410 - ERROR - [MainThread] UM.Logger.logException [85]:   File "/usr/local/lib/python3/dist-packages/UM/Settings/InstanceContainer.py", line 496, in deserialize
2018-06-13 21:47:15,411 - ERROR - [MainThread] UM.Logger.logException [85]:     raise IncorrectInstanceVersionError("Reported version {0} but expected version {1}".format(str(parser_version), self.Version))
2018-06-13 21:47:15,411 - ERROR - [MainThread] UM.Logger.logException [85]: UM.Settings.InstanceContainer.IncorrectInstanceVersionError: Reported version 2 but expected version 3
2018-06-13 21:47:15,411 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2018-06-13 21:47:15,412 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2018-06-13 21:47:15,412 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/cura/Settings/MachineManager.py", line 384, in addMachine
2018-06-13 21:47:15,412 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.setActiveMachine(new_stack.getId())
2018-06-13 21:47:15,413 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/cura/Settings/MachineManager.py", line 360, in setActiveMachine
2018-06-13 21:47:15,413 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     Application.getInstance().setGlobalContainerStack(global_stack)
2018-06-13 21:47:15,413 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/UM/Application.py", line 162, in setGlobalContainerStack
2018-06-13 21:47:15,413 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.globalContainerStackChanged.emit()
2018-06-13 21:47:15,413 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/UM/Signal.py", line 212, in emit
2018-06-13 21:47:15,413 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.__performEmit(*args, **kwargs)
2018-06-13 21:47:15,414 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/UM/Signal.py", line 315, in __performEmit
2018-06-13 21:47:15,414 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     func(dest, *args, **kwargs)
2018-06-13 21:47:15,414 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/cura/Machines/Models/QualityProfilesDropDownMenuModel.py", line 70, in _update
2018-06-13 21:47:15,414 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     layer_height = self._fetchLayerHeight(quality_group)
2018-06-13 21:47:15,414 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/cura/Machines/Models/QualityProfilesDropDownMenuModel.py", line 97, in _fetchLayerHeight
2018-06-13 21:47:15,414 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     container = quality_group.node_for_global.getContainer()
2018-06-13 21:47:15,415 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/local/lib/python3/dist-packages/cura/Machines/ContainerNode.py", line 43, in getContainer
2018-06-13 21:47:15,415 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     raise RuntimeError("Failed to lazy-load container [%s], cannot find it" % container_id)
2018-06-13 21:47:15,415 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: RuntimeError: Failed to lazy-load container [low], cannot find it
```

**Comment by ChrisTerBeke** [comment]
Creating a custom FDM printer works fine for me on 3.4 Beta...

**Comment by Appesteijn** [comment]
Do you have a custom profile: 'Low' ?

Failed to lazy-load container [low], cannot find it
