### ISSUE TITLE
[master] weird fat skin lines

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#4314]
**Application Version**

master

**Platform**

Linux

**Printer**

Kossel XL

**Steps to Reproduce**

Open cura, select printer, select profile, load model, slice.

**Actual Results**

Every other skin layer has a weird region where the lines are too fat and some lines are missing.

**Expected results**

Normal skin

**Additional Information**

The region that is bad is at the start of the skin.

![screenshot_2018-08-31_21-24-42](https://user-images.githubusercontent.com/585618/44934490-e8de0780-ad64-11e8-98c8-351cd9a9152e.png)

**Comment by smartavionics** [comment]
Here's the project, it's not a standard printer, hope you can load it...

[KXL_glasses-leg.3mf-renamed-to.zip](https://github.com/Ultimaker/Cura/files/2341532/KXL_glasses-leg.3mf-renamed-to.zip)

**Comment by diegopradogesto** [comment]
Don't worry, it's very easy to reproduce even with a Custom FFF Printer.

**Comment by diegopradogesto** [comment]
Devs.: CURA-5690

**Comment by LipuFei** [comment]
@smartavionics Also found that in your `kossel_xl_extruder_0.def.json`, `material_diameter`'s `default_value` should actually be `1.75` instead of `"1.75"`.

```
    "default_value": "1.75",   Change it to --> 1.75 without double quotes
```

**Comment by smartavionics** [comment]
OK, thanks a lot for spotting that.

**Comment by smartavionics** [comment]
Shouldn't all the settings be in the project?

If you can't reproduce it, let's assume it was a glitch and close this issue, if I find it happening again, I will reopen.

**Comment by diegopradogesto** [comment]
Try with this project file and see layer 13 for example.

[CFFFP_example.zip](https://github.com/Ultimaker/Cura/files/2383142/CFFFP_example.zip) (Rename to 3mf)

**Comment by smartavionics** [comment]
With my cura it slices but fails to display the layer view and I get these messages:

````
2018-09-15 11:28:40,932 - ERROR - [Thread-3] UM.Logger.logException [84]: Exception: Job <CuraEngineBackend.ProcessSlicedLayersJob.ProcessSlicedLayersJob object at 0x15aca5a8> caused an exception
2018-09-15 11:28:40,932 - ERROR - [Thread-3] UM.Logger.logException [88]: Traceback (most recent call last):
2018-09-15 11:28:40,933 - ERROR - [Thread-3] UM.Logger.logException [88]:   File "/opt/cura/lib/python3/dist-packages/UM/JobQueue.py", line 121, in run
2018-09-15 11:28:40,933 - ERROR - [Thread-3] UM.Logger.logException [88]:     job.run()
2018-09-15 11:28:40,934 - ERROR - [Thread-3] UM.Logger.logException [88]:   File "/opt/cura/lib/cura/plugins/CuraEngineBackend/ProcessSlicedLayersJob.py", line 192, in run
2018-09-15 11:28:40,934 - ERROR - [Thread-3] UM.Logger.logException [88]:     material_color_map[position, :] = color
2018-09-15 11:28:40,934 - ERROR - [Thread-3] UM.Logger.logException [88]: IndexError: index 1 is out of bounds for axis 0 with size 1
````

**Comment by smartavionics** [comment]
I updated my cura+uranium to the current masters and the above failure goes away. Furthermore, I am not seeing the fat skin lines.

I vote that we close this issue for now and if I see them appear again, will reopen it. Thanks for looking at it anyway!

**Comment by LipuFei** [comment]
@smartavionics It's caused by this commit: https://github.com/Ultimaker/CuraEngine/commit/06dc32c224ed28b60bae69df5f031e82442fbe0c

**Comment by smartavionics** [comment]
Hi @LipuFei , well the bug is in the 3.5 beta and is biting people!

**Comment by LipuFei** [comment]
We are on it.

**Comment by smartavionics** [comment]
No longer a problem for me.
