### ISSUE TITLE
15.09.83 - (Crash) after multiple "clear build platform"

### ISSUE THREAD

**Issue by robomaniac** [Ultimaker/Cura#434]
Version: 15.09.83
Platform: Windows-7-6.1.7601-SP1
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "c:\dev\uranium\UM\Qt\Bindings\MainWindow.py", line 111, in mouseMoveEvent
  File "c:\dev\uranium\UM\Qt\QtMouseDevice.py", line 30, in handleEvent
  File "c:\dev\uranium\UM\Signal.py", line 102, in emit
  File "c:\dev\uranium\UM\Controller.py", line 212, in event
  File "C:\Program Files (x86)\Cura_15.09.83\plugins\Tools\RotateTool\RotateTool.py", line 85, in event
    drag_start = (self.getDragStart() - handle_position).normalize()
TypeError: unsupported operand type(s) for -: 'NoneType' and 'Vector'

------------------------------------------------------------------
 I just started using the new .83... today I had multiple part I needed printing. So I don't close Cura. I juse right click "clear build platform" then I drag and drop. I think I did that 3 time and the last time it crash.

**Comment by awhiemstra** [comment]
This should be fixed in .84.
