### ISSUE TITLE
Error today when opening Cura...thoughts?

### ISSUE THREAD

**Issue by pcoulbourne** [Ultimaker/Cura#453]
Version: 15.06.03
Platform: Darwin-14.5.0-x86_64-i386-64bit
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "/Applications/Cura.app/Contents/Resources/cura_app.py", line 10, in <module>
  File "cura/CuraApplication.pyc", line 176, in run
  File "UM/Application.pyc", line 246, in setActiveMachine
  File "UM/Signal.pyc", line 96, in emit
  File "cura/CuraApplication.pyc", line 503, in _onActiveMachineChanged
  File "cura/BuildVolume.pyc", line 142, in rebuild
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by nallath** [comment]
This should be fixed for 15.10
