### ISSUE TITLE
[master] Python divide by zero when line width temporarily zero

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#4555]
**Application Version**

master

**Platform**

Linux

**Printer**

**Steps to Reproduce**

Edit the line width setting and set to zero while changing to another value. i.e. if value is 0.5 and you want 0.4, editing will go via the value 0. and that triggers the div by zero.

**Actual Results**

Log shows div by zero messages.

**Expected results**

Perhaps you don't care about this and it can stay as it is. Just thought I would raise the issue in case you think it's a bit ugly.

**Additional Information**

````
2018-10-12 08:38:47,535 - DEBUG - [MainThread] UM.Logger.logException [84]: Exception: An exception occurred in inherit function =50 / skirt_brim_line_width: float division by zero
2018-10-12 08:38:47,536 - DEBUG - [MainThread] UM.Logger.logException [88]: Traceback (most recent call last):
2018-10-12 08:38:47,536 - DEBUG - [MainThread] UM.Logger.logException [88]:   File "/opt/cura/lib/python3/dist-packages/UM/Settings/SettingFunction.py", line 95, in __call__
2018-10-12 08:38:47,536 - DEBUG - [MainThread] UM.Logger.logException [88]:     return eval(self._compiled, g, locals)
2018-10-12 08:38:47,536 - DEBUG - [MainThread] UM.Logger.logException [88]:   File "<UM.Settings.SettingFunction (0xab31508) =50 / skirt_brim_line_width >", line 1, in <module>
2018-10-12 08:38:47,536 - DEBUG - [MainThread] UM.Logger.logException [88]: ZeroDivisionError: float division by zero
2018-10-12 08:38:47,537 - DEBUG - [MainThread] UM.Logger.logException [84]: Exception: An exception occurred in inherit function =math.ceil(brim_width / (skirt_brim_line_width * initial_layer_line_width_factor / 100.0)): float division by zero
2018-10-12 08:38:47,537 - DEBUG - [MainThread] UM.Logger.logException [88]: Traceback (most recent call last):
2018-10-12 08:38:47,538 - DEBUG - [MainThread] UM.Logger.logException [88]:   File "/opt/cura/lib/python3/dist-packages/UM/Settings/SettingFunction.py", line 95, in __call__
2018-10-12 08:38:47,538 - DEBUG - [MainThread] UM.Logger.logException [88]:     return eval(self._compiled, g, locals)
2018-10-12 08:38:47,538 - DEBUG - [MainThread] UM.Logger.logException [88]:   File "<UM.Settings.SettingFunction (0xe9bbf78) =math.ceil(brim_width / (skirt_brim_line_width * initial_layer_line_width_factor / 100.0)) >", line 1, in <module>
2018-10-12 08:38:47,538 - DEBUG - [MainThread] UM.Logger.logException [88]: ZeroDivisionError: float division by zero
2018-10-12 08:38:47,539 - DEBUG - [MainThread] UM.Logger.logException [84]: Exception: An exception occurred in inherit function =math.ceil(brim_width / (skirt_brim_line_width * initial_layer_line_width_factor / 100.0)): float division by zero
2018-10-12 08:38:47,539 - DEBUG - [MainThread] UM.Logger.logException [88]: Traceback (most recent call last):
2018-10-12 08:38:47,540 - DEBUG - [MainThread] UM.Logger.logException [88]:   File "/opt/cura/lib/python3/dist-packages/UM/Settings/SettingFunction.py", line 95, in __call__
2018-10-12 08:38:47,540 - DEBUG - [MainThread] UM.Logger.logException [88]:     return eval(self._compiled, g, locals)
2018-10-12 08:38:47,540 - DEBUG - [MainThread] UM.Logger.logException [88]:   File "<UM.Settings.SettingFunction (0xe9bbf78) =math.ceil(brim_width / (skirt_brim_line_width * initial_layer_line_width_factor / 100.0)) >", line 1, in <module>
2018-10-12 08:38:47,540 - DEBUG - [MainThread] UM.Logger.logException [88]: ZeroDivisionError: float division by zero
2018-10-12 08:38:47,578 - DEBUG - [MainThread] UM.Logger.logException [84]: Exception: An exception occurred in inherit function =infill_line_distance / infill_line_width: float division by zero
2018-10-12 08:38:47,578 - DEBUG - [MainThread] UM.Logger.logException [88]: Traceback (most recent call last):
2018-10-12 08:38:47,578 - DEBUG - [MainThread] UM.Logger.logException [88]:   File "/opt/cura/lib/python3/dist-packages/UM/Settings/SettingFunction.py", line 95, in __call__
2018-10-12 08:38:47,579 - DEBUG - [MainThread] UM.Logger.logException [88]:     return eval(self._compiled, g, locals)
2018-10-12 08:38:47,579 - DEBUG - [MainThread] UM.Logger.logException [88]:   File "<UM.Settings.SettingFunction (0xda9c678) =infill_line_distance / infill_line_width >", line 1, in <module>
2018-10-12 08:38:47,579 - DEBUG - [MainThread] UM.Logger.logException [88]: ZeroDivisionError: float division by zero
````

**Comment by Ghostkeeper** [comment]
We've known about this problem since v2.0. We don't consider it very important but it's indeed a bug.
