### ISSUE TITLE
master: Multiple bugs

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#464]
Partial log:
======================
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Menu.qml:146: TypeError: Cannot read property '__contentItem' of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Menu.qml:146: TypeError: Cannot read property '__contentItem' of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Menu.qml:146: TypeError: Cannot read property '__contentItem' of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Menu.qml:146: TypeError: Cannot read property '__contentItem' of null
file:///home/tim/Development/Uranium/UM/Qt/qml/UM/Preferences/MachinesPage.qml:30: TypeError: Cannot read property 'name' of undefined
file:///home/tim/Development/Uranium/UM/Qt/qml/UM/Preferences/MachinesPage.qml:33: TypeError: Cannot read property 'typeName' of undefined
file:///home/tim/Development/Uranium/UM/Qt/qml/UM/Preferences/MachinesPage.qml:35: TypeError: Cannot read property 'hasVariants' of undefined
file:///home/tim/Development/Uranium/UM/Qt/qml/UM/Preferences/MachinesPage.qml:36: TypeError: Cannot read property 'variantName' of undefined
file:///home/tim/Development/Uranium/UM/Qt/qml/UM/Preferences/MachinesPage.qml:36: TypeError: Cannot read property 'hasVariants' of undefined
file:///home/tim/Development/Uranium/UM/Qt/qml/UM/Preferences/MachinesPage.qml:42: TypeError: Cannot read property 'name' of undefined
file:///home/tim/Development/Uranium/UM/Qt/qml/UM/Preferences/MachinesPage.qml:47: TypeError: Cannot read property 'name' of undefined
Traceback (most recent call last):
  File "/home/tim/Development/Cura/cura/CuraApplication.py", line 198, in event
    return super().event(event)
  File "/home/tim/Development/Uranium/UM/Qt/QtApplication.py", line 168, in event
    event._function_event.call()
  File "/home/tim/Development/Uranium/UM/Event.py", line 149, in call
    self._function(*self._args, **self._kwargs)
  File "/home/tim/Development/Uranium/UM/Signal.py", line 102, in emit
    func(dest, *args, **kargs)
  File "/home/tim/Development/Uranium/UM/Backend/Backend.py", line 113, in _onSocketStateChanged
    self.startEngine()
  File "/home/tim/Development/Uranium/UM/Backend/Backend.py", line 42, in startEngine
    self._process = self._runEngineProcess(self.getEngineCommand())
  File "/home/tim/Development/Cura/cura/../plugins/CuraEngineBackend/CuraEngineBackend.py", line 89, in getEngineCommand
    return [Preferences.getInstance().getValue("backend/location"), "connect", "127.0.0.1:{0}".format(self._port), "-j", Application.getInstance().getMachineManager().getActiveMachineInstance().getMachineDefinition().getPath(), "-vv"]
AttributeError: 'MachineDefinition' object has no attribute 'getPath'
Error in sys.excepthook:
Traceback (most recent call last):
  File "cura_app.py", line 10, in exceptHook
    cura.CrashHandler.show(type, value, traceback)
  File "/home/tim/Development/Cura/cura/CrashHandler.py", line 19, in show
    if not debug_mode:
UnboundLocalError: local variable 'debug_mode' referenced before assignment

Original exception was:
Traceback (most recent call last):
  File "/home/tim/Development/Cura/cura/CuraApplication.py", line 198, in event
    return super().event(event)
  File "/home/tim/Development/Uranium/UM/Qt/QtApplication.py", line 168, in event
    event._function_event.call()
  File "/home/tim/Development/Uranium/UM/Event.py", line 149, in call
    self._function(*self._args, **self._kwargs)
  File "/home/tim/Development/Uranium/UM/Signal.py", line 102, in emit
    func(dest, *args, **kargs)
  File "/home/tim/Development/Uranium/UM/Backend/Backend.py", line 113, in _onSocketStateChanged
    self.startEngine()
  File "/home/tim/Development/Uranium/UM/Backend/Backend.py", line 42, in startEngine
    self._process = self._runEngineProcess(self.getEngineCommand())
  File "/home/tim/Development/Cura/cura/../plugins/CuraEngineBackend/CuraEngineBackend.py", line 89, in getEngineCommand
    return [Preferences.getInstance().getValue("backend/location"), "connect", "127.0.0.1:{0}".format(self._port), "-j", Application.getInstance().getMachineManager().getActiveMachineInstance().getMachineDefinition().getPath(), "-vv"]
AttributeError: 'MachineDefinition' object has no attribute 'getPath'
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:154: TypeError: Cannot read property of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:154: TypeError: Cannot read property of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:154: TypeError: Cannot read property of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:154: TypeError: Cannot read property of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:154: TypeError: Cannot read property of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:154: TypeError: Cannot read property of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:154: TypeError: Cannot read property of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:154: TypeError: Cannot read property of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:154: TypeError: Cannot read property of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:154: TypeError: Cannot read property of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:154: TypeError: Cannot read property of null
2015-10-07 11:11:37,066 - DEBUG - Preparing to send slice data to engine.
2015-10-07 11:11:41,278 - DEBUG - Calculating normals took 0.038167715072631836 seconds
2015-10-07 11:11:41,278 - DEBUG - Loaded a mesh with 345324 vertices
2015-10-07 11:11:41,386 - DEBUG - Loading mesh took 0.7094206809997559 seconds
2015-10-07 11:11:42,515 - DEBUG - Preparing to send slice data to engine.
2015-10-07 11:11:42,555 - DEBUG - Sending data to engine for slicing.
2015-10-07 11:11:42,623 - DEBUG - Setting value of setting bottom_layers to 6
file:///home/tim/Development/Uranium/UM/Qt/qml/UM/Settings/SettingView.qml:119:35: QML SettingItem: Binding loop detected for property "value"
file:///home/tim/Development/Uranium/UM/Qt/qml/UM/Settings/SettingView.qml:119:35: QML SettingItem: Binding loop detected for property "value"
file:///home/tim/Development/Uranium/UM/Qt/qml/UM/Settings/SettingView.qml:119:35: QML SettingItem: Binding loop detected for property "value"
file:///home/tim/Development/Uranium/UM/Qt/qml/UM/Settings/SettingView.qml:119:35: QML SettingItem: Binding loop detected for property "value"

**Comment by BagelOrb** [comment]
Might be due to Uranium and Cura being out of sync.
