### ISSUE TITLE
one-at-a-time crash

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#4766]
**Application Version**
3.5.1

**Platform**
Linux Mint

**Printer**
UM3

**Steps to Reproduce**
Install Mesh tools from Aldo
Load [hex_tiles.stl.zip](https://github.com/Ultimaker/Cura/files/2565504/hex_tiles.stl.zip)
scale to 10%
Split into parts
Set print sequence to one-at-a-time 

**Actual Results**
Crash

**Expected results**
No crash

**Additional Information**
Log:
`
2018-11-09 11:11:19,243 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [65]: An uncaught error has occurred!
2018-11-09 11:11:19,245 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: Traceback (most recent call last):
2018-11-09 11:11:19,248 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.5/build/inst/lib/python3.5/site-packages/cura/Scene/ConvexHullDecorator.py", line 129, in recomputeConvexHull
2018-11-09 11:11:19,250 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.5/build/inst/lib/python3.5/site-packages/cura/Scene/ConvexHullDecorator.py", line 76, in getConvexHull
2018-11-09 11:11:19,252 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: AttributeError: 'NoneType' object has no attribute 'getMinkowskiHull'
`

**Comment by Vandrasc** [comment]
Indeed reproducible in 3.5 but fixed in 3.6 in the meanwhile. Nice catch, though!
