### ISSUE TITLE
Bug exception please help me.Version: 15.06.03

### ISSUE THREAD

**Issue by tonihidalgo** [Ultimaker/Cura#519]
Version: 15.06.03
Platform: Windows-7-6.1.7601-SP1
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 10, in <module>
  File "c:\dev\cura\cura\CuraApplication.py", line 176, in run
  File "c:\dev\uranium\UM\Application.py", line 246, in setActiveMachine
  File "c:\dev\uranium\UM\Signal.py", line 96, in emit
  File "c:\dev\uranium\UM\Scene\Platform.py", line 48, in _onActiveMachineChanged
  File "c:\dev\uranium\UM\Resources.py", line 50, in getPath
FileNotFoundError: Could not find resource ('witbox_platform.stl',) in 4

**Comment by Ghostkeeper** [comment]
This is a new one, I think!

You are missing the file "C:\dev\cura\resources\meshes\witbox_platform.stl". I don't know how it got missing. The mesh file got renamed two days ago, but that shouldn't affect your version of course.

You can download the file here: https://github.com/Ultimaker/Cura/raw/master/resources/meshes/bq_witbox_platform.stl
You will have to rename it to `witbox_platform.stl` and place it in the aforementioned folder.

You might have to do the same with [hephestos_platform.stl](https://github.com/Ultimaker/Cura/raw/master/resources/meshes/bq_hephestos_platform.stl) and [bq_hephestos_2.stl](https://github.com/Ultimaker/Cura/raw/master/resources/meshes/bq_hephestos_2_platform.stl).
