### ISSUE TITLE
uncaught exception on MacOSX 10.11.2

### ISSUE THREAD

**Issue by chappy1978** [Ultimaker/Cura#543]
Cura Worked for the first time on the second time. It gave me this fault
Version: 15.06.03
Platform: Darwin-15.2.0-x86_64-i386-64bit
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "/Applications/3D Printing/Cura 15.06.app/Contents/Resources/cura_app.py", line 9, in <module>
  File "UM/Application.pyc", line 329, in getInstance
  File "cura/CuraApplication.pyc", line 56, in __init__
  File "UM/Qt/QtApplication.pyc", line 76, in __init__
  File "UM/Application.pyc", line 355, in loadMachines
  File "UM/Settings/MachineSettings.pyc", line 87, in loadValuesFromFile
  File "configparser.pyc", line 672, in read
  File "configparser.pyc", line 993, in _read
  File "codecs.pyc", line 319, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

**Comment by nallath** [comment]
Fixed for next release.
