### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jdslatermd** [Ultimaker/Cura#558]
Latest download of Cura for Mac crashes immediately upon launch with the following:

Version: 15.06.03
Platform: Darwin-15.0.0-x86_64-i386-64bit
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "/Applications/Cura.app/Contents/Resources/cura_app.py", line 9, in <module>
  File "UM/Application.pyc", line 329, in getInstance
  File "cura/CuraApplication.pyc", line 56, in __init__
  File "UM/Qt/QtApplication.pyc", line 48, in __init__
  File "UM/Application.pyc", line 67, in __init__
  File "UM/Preferences.pyc", line 68, in readFromFile
  File "_collections_abc.pyc", line 498, in __iter__
  File "configparser.pyc", line 1204, in __getitem__
  File "configparser.pyc", line 773, in get
  File "configparser.pyc", line 374, in before_get
  File "configparser.pyc", line 423, in _interpolate_some
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: "%20NAME\\x00\\x00\\x00\\x82\\x00\\x00\\x00\\xff\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02y\\x00\\x00\\x00\\x04\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00d\\xff\\xff\\xff\\xff\\x00\\x00\\x00\\x81\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x04\\x00\\x00\\x01\\x84\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00A\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00B\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00r\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x03\\xe8\\x00\\x00\\x00\\x00'"

**Comment by daid** [comment]
Version: 15.06.03

That's not the latest:
http://software.ultimaker.com/Cura_closed_beta/15.10/
