### ISSUE TITLE
OpenGL crash in GNU/Linux, Debian

### ISSUE THREAD

**Issue by MiguelAngelLV** [Ultimaker/Cura#6]
I am trying run the new Cura beta in Debian. I installed pyqt5.4 from Experimental, download the repositorys Cura, Uranium, CuraEngine... But when a launch `cura.py` I get this error
```
Traceback (most recent call last):
  File "/home/link/Descargas/Cura/UM/Qt/Bindings/MainWindow.py", line 120, in _render
    renderer.beginRendering()
  File "/home/link/Descargas/Cura/UM/Qt/QtGL2Renderer.py", line 154, in beginRendering
    self._initialize()
  File "/home/link/Descargas/Cura/UM/Qt/QtGL2Renderer.py", line 321, in _initialize
    Resources.getPath(Resources.ShadersLocation, "default.vert"),
  File "/home/link/Descargas/Cura/UM/Resources.py", line 50, in getPath
    raise FileNotFoundError("Could not find resource {0} in {1}".format(args, type))
FileNotFoundError: Could not find resource ('default.vert',) in 5
Traceback (most recent call last):
  File "/home/link/Descargas/Cura/UM/Qt/Bindings/MainWindow.py", line 120, in _render
    renderer.beginRendering()
  File "/home/link/Descargas/Cura/UM/Qt/QtGL2Renderer.py", line 154, in beginRendering
    self._initialize()
  File "/home/link/Descargas/Cura/UM/Qt/QtGL2Renderer.py", line 321, in _initialize
    Resources.getPath(Resources.ShadersLocation, "default.vert"),
  File "/home/link/Descargas/Cura/UM/Resources.py", line 50, in getPath
    raise FileNotFoundError("Could not find resource {0} in {1}".format(args, type))
FileNotFoundError: Could not find resource ('default.vert',) in 5
2015-05-14 20:56:34,140 - DEBUG - Backend connected on port 49674
Traceback (most recent call last):
  File "/home/link/Descargas/Cura/UM/Qt/Bindings/MainWindow.py", line 120, in _render
    renderer.beginRendering()
  File "/home/link/Descargas/Cura/UM/Qt/QtGL2Renderer.py", line 154, in beginRendering
    self._initialize()
  File "/home/link/Descargas/Cura/UM/Qt/QtGL2Renderer.py", line 321, in _initialize
    Resources.getPath(Resources.ShadersLocation, "default.vert"),
  File "/home/link/Descargas/Cura/UM/Resources.py", line 50, in getPath
    raise FileNotFoundError("Could not find resource {0} in {1}".format(args, type))
FileNotFoundError: Could not find resource ('default.vert',) in 5
Traceback (most recent call last):
  File "/home/link/Descargas/Cura/UM/Qt/Bindings/MainWindow.py", line 120, in _render
    renderer.beginRendering()
  File "/home/link/Descargas/Cura/UM/Qt/QtGL2Renderer.py", line 154, in beginRendering
    self._initialize()
  File "/home/link/Descargas/Cura/UM/Qt/QtGL2Renderer.py", line 321, in _initialize
    Resources.getPath(Resources.ShadersLocation, "default.vert"),
  File "/home/link/Descargas/Cura/UM/Resources.py", line 50, in getPath
    raise FileNotFoundError("Could not find resource {0} in {1}".format(args, type))
FileNotFoundError: Could not find resource ('default.vert',) in 5
```
And the windows show as

![index1](https://cloud.githubusercontent.com/assets/638110/7639465/6cb81158-fa7c-11e4-8bc9-980438b77b3a.png)

**Comment by MiguelAngelLV** [comment]
Sorry, my fault. I forget copy Uranium resources.
