### ISSUE TITLE
Cura can't find file passed on command line

### ISSUE THREAD

**Issue by Feuermurmel** [Ultimaker/Cura#601]
Cura 15.04.4 crashes with an `IOError` on an existing file:

```
$ /.../Cura.app//Contents/MacOS/Cura --slice --ini stuff/profile.ini --output src/foo.gcode src/foo.stl
load preferences from /.../Library/Application Support/Cura/15.04.4/preferences.ini
Listening for engine communications on 49674
Traceback (most recent call last):
  File "/.../Cura.app/Contents/Resources/__boot__.py", line 316, in <module>
    _run()
  File "/.../Cura.app/Contents/Resources/__boot__.py", line 311, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/.../Cura.app/Contents/Resources/cura.py", line 89, in <module>
    main()
  File "/.../Cura.app/Contents/Resources/cura.py", line 67, in main
    for m in meshLoader.loadMeshes(args[0]):
  File "Cura/util/meshLoader.pyo", line 32, in loadMeshes
  File "Cura/util/meshLoaders/stl.pyo", line 54, in loadScene
IOError: [Errno 2] No such file or directory: 'src/foo.stl'
2016-01-18 21:07:30.245 Cura[31285:507] Cura Error$ ls src/foo.stl
src/foo.stl
```

The file at `src/foo.stl` exists and is readable.

**Comment by fieldOfView** [comment]
Thanks for your reports. This is the repository for the "new" Cura. Issues for the old Cura (up to 15.04.x) should be logged on https://github.com/daid/cura

**Comment by daid** [comment]
Old Cura needs absolute paths, not relative.

**Comment by Feuermurmel** [comment]
I've created a new issue: https://github.com/daid/Cura/issues/1399
