### ISSUE TITLE
can't open cure

### ISSUE THREAD

**Issue by kormister** [Ultimaker/Cura#605]
Version: 15.06.03
Platform: Darwin-14.5.0-x86_64-i386-64bit
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "/Applications/Cura.app/Contents/Resources/cura_app.py", line 10, in <module>
  File "cura/CuraApplication.pyc", line 176, in run
  File "UM/Application.pyc", line 246, in setActiveMachine
  File "UM/Signal.pyc", line 96, in emit
  File "cura/CuraApplication.pyc", line 503, in _onActiveMachineChanged
  File "cura/BuildVolume.pyc", line 142, in rebuild
TypeError: Can't convert 'float' object to str implicitly

**Comment by fieldOfView** [comment]
Thanks for reporting, but this is a known issue with this very old version:
https://github.com/Ultimaker/Cura/search?q=BuildVolume.pyc&type=Issues&utf8=%E2%9C%93
Please try a newer version from here:
http://software.ultimaker.com/Cura_closed_beta/15.10/
