### ISSUE TITLE
Running Cura with --debug crashes because sys.stderr is None

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#6579]
**Application version**
4.3.0 (releases, frozen)

**Platform**
Windows 10

**Printer**
n/a

**Reproduction steps**
Open a prompt
cd to installed Cura location
run Cura with --debug argument `cura.exe --debug`

**Actual results**
Cura crashes with the following traceback:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "Console.py", line 24, in <module>
  File "X:\4.3\build\inst\bin\cura_app.py", line 134, in <module>
RuntimeError: sys.stderr is None
```

**Expected results**
Cura runs and log output is shown on the console

**Additional information**
n/a

**Comment by smartavionics** [comment]
You can use cura.exe --debug OK from the bash shell that comes with git.

**Comment by Ghostkeeper** [comment]
I've made a workaround for you. It still works for me. Can you see if that fixed it?

**Comment by fieldOfView** [comment]
@smartavionics doesn't work for me with the "git bash" that I found on my system

@Ghostkeeper, I'll give it a go over the weekend (I don't have a build system for Windows set up, so I'll have to rely on some manual patching)
