### ISSUE TITLE
[4.4.0] crash on startup on ubuntu 18.04

### ISSUE THREAD

**Issue by n00b3rpwn4g3** [Ultimaker/Cura#6735]
**Application version**
4.4.0

**Platform**
Linux-5.0.0-36-generic-x86_64-with-debian-buster-sid

**Printer**
no printer was attached but I had a custom Ender 3 profile loaded from using a previous cura version that I installed from the apt packages

**Reproduction steps**
I downloaded the most recent appimage from Cura's website for Linux distributions, set it to executable, and tried to run it in my downloads folder. It starts up but immediately gives me a crash report.

**Actual results**
It gives me a few separate windows of the same crash report, with more details below.

**Expected results**
It should start up normally I guess.

**Additional information**
This is an image of the crash report window, and I'll post the full error traceback and log parts below:
![Screenshot from 2019-11-30 08-59-13](https://user-images.githubusercontent.com/12039591/69901455-ba781f00-134f-11ea-9472-eb82c93d61dd.png)
error traceback:
```
Traceback (most recent call last):
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/Machines/Models/IntentCategoryModel.py", line 98, in _update
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/Settings/IntentManager.py", line 119, in currentAvailableIntentCategories
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/Settings/IntentManager.py", line 61, in intentCategories
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/Settings/IntentManager.py", line 42, in intentMetadatas
KeyError: 'empty'
```
logs:
```
Thread 0x00007efd99ffb700 (most recent call first):
  File "/tmp/.mount_UltimaTNWt3F/usr/bin/plugins/plugins/RemovableDriveOutputDevice/RemovableDrivePlugin.py", line 61 in _updateThread
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007efd9a7fc700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/4.4/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/4.4/inst/lib/python3.5/site-packages/zeroconf.py", line 1153 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007efd9affd700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 549 in wait
  File "/tmp/.mount_UltimaTNWt3F/usr/bin/plugins/plugins/UM3NetworkPrinting/src/Network/ZeroConfClient.py", line 74 in _handleOnServiceChangedRequests
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007efd9b7fe700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/4.4/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/4.4/inst/lib/python3.5/site-packages/zeroconf.py", line 1017 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007efd9bfff700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/site-packages/zeroconf.py", line 946 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007efdb0b18700 (most recent call first):
  File "/tmp/.mount_UltimaTNWt3F/usr/bin/plugins/plugins/USBPrinting/USBPrinterOutputDeviceManager.py", line 86 in _updateThread
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007efdb133b700 (most recent call first):
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Backend/Backend.py", line 150 in _storeStderrToLogThread
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007efdb1b3c700 (most recent call first):
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Backend/Backend.py", line 138 in _storeOutputToLogThread
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007efdb3fff700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007efdc49d6700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007efdc51d7700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007efdc59d8700 (most recent call first):
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/4.4/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00007efde9261740 (most recent call first):
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 306 in _logInfoWidget
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 156 in _createDialog
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 77 in __init__
  File "/build/4.4/build/inst/bin/cura", line 111 in exceptHook
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 391 in _show
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Event.py", line 189 in call
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 428 in event
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 1003 in event
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 391 in _show
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Event.py", line 189 in call
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 428 in event
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 1003 in event
  File "/build/4.4/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 341 in exec_
  File "/build/4.4/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 804 in run
  File "/build/4.4/build/inst/bin/cura", line 180 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 957 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 968 in _find_and_load
  File "/build/env/4.4/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 957 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 968 in _find_and_load
  File "/build/env/4.4/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 957 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 968 in _find_and_load
```
sorry if it's a really long post I just wanted to include as much relevant info.

**Comment by smartavionics** [comment]
Hi, I think this is a known bug which I believe I have fixed in my builds so you may wish to try one of those. They can be installed alongside the UM builds. You can find them at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0. Please read the README.md file in there.

**Comment by n00b3rpwn4g3** [comment]
Thank you, I downloaded the 2019-11-28 appimage version and it works without errors.

**Comment by n00b3rpwn4g3** [comment]
So should I close the issue now, or does it still kinda apply to the official version so this thread stays open until that's fixed?

**Comment by smartavionics** [comment]
Yes, keep this issue open until the UM people confirm that they have fixed the bug in their sources. Cheers!

**Comment by nallath** [comment]
We've also fixed it in master.
