### ISSUE TITLE
[4.4.0] Cura crash when opening/importing .stl file

### ISSUE THREAD

**Issue by TheEagleEyez** [Ultimaker/Cura#6828]
**Application version**
4.4.0

**Platform**
Windows 10 64-bit

**Printer**
DeltaBot

**Reproduction steps**
1. Launched Cura
2. Clicked "Open File"
3. Selected my part file (.stl format)

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/59067200/71206326-e826f880-2269-11ea-9bc2-1243c51b105f.png)

**Actual results**
A "Crash Report" window opens telling me a "fatal error has occurred"

Traceback (most recent call last):
  File "X:\4.4-exe\build\inst\lib\python3.5\site-packages\cura\BuildVolume.py", line 156, in _onSceneChangeTimerFinished
  File "X:\4.4-exe\build\inst\lib\python3.5\site-packages\cura\BuildVolume.py", line 524, in rebuild
  File "X:\4.4-exe\build\inst\lib\python3.5\site-packages\cura\BuildVolume.py", line 1102, in getEdgeDisallowedSize
  File "X:\4.4-exe\build\inst\lib\python3.5\site-packages\cura\Settings\ExtruderManager.py", line 256, in getUsedExtruderStacks
KeyError: '1'

**Expected results**
Should import the file into cura window so I can slice it

**Project file**
N/A

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/3985491/cura.log)

**Additional information**
Not to sure what the issue is, I just downloaded Cura yesterday and attempted to use it today but I kept getting this when I would open/import a file.

**Comment by Ghostkeeper** [comment]
The log is full of things like these:

    2019-12-19 13:53:23,516 - WARNING - [MainThread] cura.Settings.CuraFormulaFunctions.getValueInExtruder [46]: Value for support_interface_enable of extruder 1 was requested, but that extruder is not available. Returning the result form extruder 0 instead

Somehow, it seems that your support extruder got put on the second extruder. But your printer doesn't have a second extruder.

I'm not able to reproduce the problem itself. I can't get the extruder settings to change to a different extruder or get it to crash. But maybe a workaround is to add a new Deltabot printer to Cura and delete the old one.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
