### ISSUE TITLE
PPA multiple files crash Cura

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#6972]
@thopiekar with latest master PPA Cura crashes when loading multiple files.
When multiplying a file it says that it is placing the files, but nothing happens.

**Comment by Ghostkeeper** [comment]
Yup, this reproduces. It produces the following error in the log:

```
2020-01-14 11:03:49,466 - ERROR - [Thread-3] UM.JobQueue.run [123]: Exception: Job <cura.MultiplyObjectsJob.MultiplyObjectsJob object at 0x7f79595cc150> caused an exception
2020-01-14 11:03:49,469 - ERROR - [Thread-3] UM.JobQueue.run [123]: Traceback (most recent call last):
2020-01-14 11:03:49,471 - ERROR - [Thread-3] UM.JobQueue.run [123]:   File "/home/ruben/Projects/Uranium/UM/JobQueue.py", line 121, in run
2020-01-14 11:03:49,472 - ERROR - [Thread-3] UM.JobQueue.run [123]:     job.run()
2020-01-14 11:03:49,472 - ERROR - [Thread-3] UM.JobQueue.run [123]:   File "/home/ruben/Projects/Cura/cura/MultiplyObjectsJob.py", line 45, in run
2020-01-14 11:03:49,472 - ERROR - [Thread-3] UM.JobQueue.run [123]:     arranger = Arrange.create(x = machine_width, y = machine_depth, scene_root = root, scale = scale, min_offset = self._min_offset)
2020-01-14 11:03:49,473 - ERROR - [Thread-3] UM.JobQueue.run [123]:   File "/home/ruben/Projects/Cura/cura/Arranging/Arrange.py", line 72, in create
2020-01-14 11:03:49,473 - ERROR - [Thread-3] UM.JobQueue.run [123]:     if not points:
2020-01-14 11:03:49,474 - ERROR - [Thread-3] UM.JobQueue.run [123]: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
