### ISSUE TITLE
Stlicing does not start after pressing slice

### ISSUE THREAD

**Issue by muhammadelmogy** [Ultimaker/Cura#7596]
**Application version**
4.6

**Platform**
Windows10 1909

**Printer**
Custom XYZ Cartesian

**Reproduction steps**
1.open model in cura
2.slice first time most likely will work
3.every other time press slice and wait, it will display processing
4.change view to "Prepare" or "Monitor" then button revert back to slice text
5.change the view again to "Review" click again on the slice button, slice will start and finish quickly

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
If I follow the steps till 3 and wait it will take long time to finish

**Expected results**
If steps followed it will behave as described otherwise  it will take too much time

**Project file**
[CFFFP_Fan Holder.zip](https://github.com/Ultimaker/Cura/files/4532162/CFFFP_Fan.Holder.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by nallath** [comment]
Please attach the logs, as per the instruction of the template. We really need it to debug things.

**Comment by muhammadelmogy** [comment]
Log File Uploaded!

**Comment by mahtDFR** [comment]
I'm afraid I can't reproduce it from your project file project file and your logs suggest it's slicing ok.
Are you able to try [resetting your configuration](https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations)? You can zip up the relevant version number first to keep your settings safe.

`2020-04-28 14:25:21,312 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] G28 ;Home
2020-04-28 14:25:21,314 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] 
2020-04-28 14:25:21,317 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] M190 S100.000000 ; Set bed temperature
2020-04-28 14:25:21,319 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] M109 S240.000000 ; Set nozzle temperature
2020-04-28 14:25:21,322 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] G29
2020-04-28 14:25:21,324 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] G1 Z1.0 ;Move the platform down
2020-04-28 14:25:21,327 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] G92 E0
2020-04-28 14:25:21,329 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] G1 Z1.0 ;Move the platform down
2020-04-28 14:25:21,332 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] G1 F1000 E15
2020-04-28 14:25:21,335 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] G1 F5000 Z10.0
2020-04-28 14:25:21,337 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] G1 F3000 E-4
2020-04-28 14:25:21,340 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] G1 F2000 E8
2020-04-28 14:25:21,343 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [106]: [Backend] G92 E0" -s acceleration_layer_0="3000" -s machine_max_feedrate_e="299792458000" -s travel_compensate_overlapping_walls_x_enabled="True" -s speed_wall_0="30.0" -s cool_lift_head="False" -s ooze_shield_angle="60" -s wireframe_flat_delay="0.1" -s smooth_spiralized_contours="True" -s machine_center_is_zero="False" -e0 -s cool_lift_head="False" -s retraction_prime_speed="70" -s machine_extruder_end_pos_abs="False" -s spaghetti_infill_extra_volume="0" -s support="0" -s retraction_min_travel="2" -s machine_nozzle_tip_outer_diameter="1" -s infill_material_flow="100" -s skin_overlap_mm="0.02" -s jerk_travel_layer_0="1" -s meshfix_maximum_deviation="0.025" -s infill_pattern="triangles" -s magic_fuzzy_skin_point_density="1.25" -s support_interface_skip_height="0.3" -s top_bottom_thickness="0.8" -s skin_angles="[ ]" -s support_tower_roof_angle="65" -s raft_surface_acceleration="1500" -s machine_nozzle_heat_up_speed="2.0" -s support_roof_line_distance="0.4" -s support_join_distance="2.0" -s machine_extruder_end_pos_x="0" -s jerk_support_infill="1" -s support_zag_skip_count="12" -s raft_surface_fan_speed="0" -s machine_heat_zone_length="16" -s prime_tower_wipe_enabled="True" -s support_use_towers="False" -s raft_fan_speed="0" -s extruder_nr="0" -s ironing_pattern="zigzag" -s acceleration_support_interface="1500" -s machine_steps_per_mm_x="50" -s speed_z_hop="10" -s slicing_tolerance="middle" -s roofing_material_flow="100" -s bridge_wall_material_flow="50" -s coasting_volume="0.064" -s retraction_hop_only_when_collides="False" -s acceleration_print_layer_0="500" -s wall_overhang_speed_factor="100" -s acceleration_roofing="1500" -s z_seam_position="back" -s support_interface_line_width="0.4" -s skirt_brim_line_width="0.4" -s bridge_skin_material_flow_3="110" -s machine_min_cool_heat_time_window="50.0" -s infill_angles="[ ]" -s wipe_repeat_count="5" -s optimize_wall_printing_order="True" -s material_break_temperature="50" -s support_tower_diameter="3.0" -s material_diameter="1.75" -s material_anti_ooze_retracted_position="-4" -s prime_tower_line_width="0.4" -s meshfix_maximum_travel_resolution="0.8" -s ironing_inset="0.2" -s layer_0_z_overlap="0.15" -s support_interface_density="100" -s sub_div_rad_add="0.4" -s machine_steps_per_mm_z="50" -s cross_infill_pocket_size="1.5" -s wipe_retraction_speed="40" -s machine_nozzle_offset_x="0" -s machine_nozzle_cool_down_speed="2.0" -s machine_settings="0" -s wipe_hop_speed="10" -s resolution="0" -s speed_equalize_flow_max="150" -s coasting_speed="90" -s small_hole_max_size="0" -s mesh_position_y="0" -s material_flow_dependent_temperature="False" -s acceleration_support_infill="1500" -s meshfix_union_all_remove_holes="False" -s brim_gap="0" -s support_bottom_line_width="0.4" -s support_bottom_pattern="concentric" -s support_interface_angles="[ ]" -s layer_start_x="0.0" -s support_fan_enable="False" -s top_thickness="0.8" -s raft_surface_line_width="0.4" -s wall_line_width_x="0.4" -s bridge_wall_speed="10" -s wipe_retraction_extra_prime_amount="0.1" -s ironing_only_highest_layer="True" -s meshfix="0" -s retraction_hop_after_extruder_switch="True" -s bottom_thickness="0.8" -s raft_interface_jerk="1" -s skin_line_width="0.4" -s command_line_settings="0" -s raft_base_acceleration="1500" -s support_brim_enable="True" -s switch_extruder_prime_speed="20" -s small_feature_speed_factor="50" -s support_interface_offset="0.0" -s blackmagic="0" -s acceleration_support_roof="1500" -s wall_material_flow="100" -s travel_compensate_overlapping_walls_enabled="True" -s wipe_retraction_prime_speed="40" -s switch_extruder_retraction_speed="20" -s jerk_ironing="1" -s retraction_extra_prime_amount="0.1" -s wipe_retraction_amount="2.5" -s material_extrusion_cool_down_speed="0.7" -s raft_acceleration="1500" -s bridge_skin_support_threshold="50" -s support_tree_angle="40" -s wall_0_inset="0" -s material_surface_energy="100" -s default_material_print_temperature="200" -s z_seam_corner="z_seam_corner_weighted" -s retraction_amount="2.5" -s support_interface_material_flow="100" -s jerk_roofing="1" -s raft_base_speed="18.75" -s support_offset="0" -s speed_support_roof="10.0" -s support_roof_offset="0.0" -s support_infill_rate="25" -s gradual_support_infill_steps="0" -s support_conical_enabled="False" -s bridge_skin_material_flow_2="100" -s machine_nozzle_head_distance="3" -s travel_avoid_other_parts="True" -s machine_extruder_start_pos_abs="False" -s support_conical_min_width="5.0" -s jerk_layer_0="1" -s wipe_move_distance="20" -s support_interface_enable="False" -s bridge_skin_density_2="75" -s machine_nozzle_id="unknown" -s machine_extruder_start_pos_y="0" -s raft_surface_jerk="1" -s min_skin_width_for_expansion="5.510910596163089e-17" -s infill_support_angle="40" -s meshfix_maximum_resolution="0.5" -s support_roof_line_width="0.4" -s mesh_position_x="0" -s support_roof_angles="[ ]" -s meshfix_keep_open_polygons="False" -s skirt_line_count="4" -s material_break_speed="25" -s material_flow="100" -s multiple_mesh_overlap="0.15" -s material_crystallinity="False" -s support_bottom_line_distance="0.4" -s infill_overlap="10" -s support_brim_line_count="20" -s infill="0" -s speed_topbottom="75" -s spaghetti_max_height="2.0" -s material="0" -s support_roof_pattern="concentric" -s bridge_skin_speed_2="37.5" -s travel_compensate_overlapping_walls_0_enabled="True" -s bridge_fan_speed="100" -s skirt_gap="2" -s support_interface_pattern="concentric" -s retraction_speed="40" -s support_roof_height="1" -s bridge_sparse_infill_max_density="0" -s infill_sparse_density="80" -s infill_sparse_thickness="0.3" -s speed_support_bottom="10.0" -s hole_xy_offset="0" -s support_angle="45" -s bridge_fan_speed_3="0" -s bridge_skin_speed="37.5" -s jerk_wall="1" -s cool_fan_full_at_height="0.2" -s conical_overhang_angle="50" -s skin_material_flow="100" -s skirt_brim_minimal_length="250" -s wall_x_material_flow="100" -s shell="0" -s infill_wall_line_count="0" -s minimum_bottom_area="1.0" -s top_skin_expand_distance="0.8" -s experimental="0" -s support_xy_overrides_z="z_overrides_xy" -s bridge_skin_material_flow="60" -s speed_travel_layer_0="100" -s material_no_load_move_factor="0.940860215" -s jerk_wall_x="1" -s top_layers="3" -s material_anti_ooze_retraction_speed="5" -s z_seam_type="sharpest_corner" -s raft_interface_line_width="0.8" -s retraction_count_max="90" -s magic_fuzzy_skin_point_dist="0.8" -s meshfix_extensive_stitching="False" -s material_break_preparation_speed="2" -s acceleration_wall="1500" -s material_print_temperature_layer_0="240" -s top_skin_preshrink="0.8" -s extruder_prime_pos_abs="False" -s cool_fan_speed_max="100" -s bridge_fan_speed_2="0" -s top_bottom_pattern="zigzag" -s cool_min_layer_time="5" -s connect_skin_polygons="False" -s support_bottom_material_flow="100" -s cool_fan_speed="0.0" -s speed_travel="200" -s support_tree_collision_resolution="0.2" -s support_bottom_angles="[ ]" -s layer_start_y="0.0" -s retraction_extrusion_window="2.5" -s switch_extruder_retraction_amount="16" -s switch_extruder_retraction_speeds="20" -s mesh_position_z="0" -s z_seam_relative="False" -s jerk_skirt_brim="1" -s support_conical_angle="30" -s acceleration_travel="1000" -s limit_support_retractions="True" -s spaghetti_infill_enabled="False" -s infill_support_enabled="False" -s bottom_skin_preshrink="0.8" -s raft_speed="25.0" -s spaghetti_infill_stepped="True" -s minimum_roof_area="1.0" -s cross_support_density_image="" -s raft_base_fan_speed="0" -s support_roof_density="100" -s acceleration_skirt_brim="1500" -s infill_randomize_start_location="False" -s bridge_enable_more_layers="True" -s support_wall_count="0" -s cooling="0" -s support_infill_angles="[ ]" -s support_skip_some_zags="False" -s acceleration_prime_tower="1500" -s jerk_support_interface="1" -s support_infill_sparse_thickness="0.3" -s mold_width="5" -s cool_fan_speed_min="90" -s support_tower_maximum_supported_diameter="3.0" -s wall_overhang_angle="90" -s raft_interface_line_spacing="1.0" -s outer_inset_first="True" -s infill_overlap_mm="0.05" -s ironing_line_spacing="0.1" -s jerk_support="1" -s skirt_brim_speed="25" -s xy_offset_layer_0="0" -s fill_perimeter_gaps="everywhere" -s support_top_distance="0.25" -s jerk_print="1" -s magic_fuzzy_skin_outside_only="False" -s machine_steps_per_mm_y="50" -s material_break_preparation_temperature="231" -s jerk_travel="1" -s jerk_wall_0="1" -s speed_layer_0="200" -s gradual_infill_step_height="1.5" -s machine_nozzle_temp_enabled="True" -s gradual_support_infill_step_height="1" -s alternate_extra_perimeter="True" -s skin_no_small_gaps_heuristic="False" -s speed_print="50" -s cross_infill_density_image="" -s skin_overlap="5" -s max_extrusion_before_wipe="10" -s cool_fan_full_layer="2" -s spaghetti_inset="0.2" -s support_connect_zigzags="False" -s magic_mesh_surface_mode="normal" -s bridge_skin_density="100" -s bridge_wall_coast="100" -s material_print_temperature="231" -s minimum_support_area="0.0" -s jerk_topbottom="1" -s wall_0_wipe_dist="0.2" -s clean_between_layers="False" -s cool_fan_enabled="False" -s bottom_layers="3" -s bridge_skin_speed_3="37.5" -s support_bottom_enable="False" -s initial_bottom_layers="3" -s brim_outside_only="False" -s skin_edge_support_thickness="0" -s skin_edge_support_layers="0" -s machine_extruder_end_code="" -s meshfix_union_all="True" -s speed_support="15" -s brim_width="5" -s wipe_retraction_enable="True" -s speed_roofing="75" -s material_standby_temperature="175" -s infill_line_distance="1.5" -s raft_surface_layers="2" -s prime_tower_min_volume="6" -s roofing_layer_count="0" -s z_seam_y="300" -s xy_offset="0" -s material_break_preparation_retracted_position="-16" -s skin_preshrink="0.8" -s support_bottom_height="1" -s material_end_of_filament_purge_speed="0.5" -s wall_line_width_0="0.4" -s jerk_support_roof="1" -s support_supported_skin_fan_speed="100" -s support_brim_width="8.0" -s switch_extruder_extra_prime_amount="0" -s mesh_rotation_matrix="[[1,0,0], [0,1,0], [0,0,1]]" -s acceleration_wall_0="500" -s material_shrinkage_percentage="0" -s spaghetti_max_infill_angle="10" -s material_initial_print_temperature="230" -s cool_min_speed="10" -s dual="0" -s acceleration_wall_x="1500" -s speed_ironing="50" -s machine_feeder_wheel_diameter="10.0" -s roofing_line_width="0.4" -s support_roof_material_flow="100" -s extruder_prime_pos_y="0" -s bottom_skin_expand_distance="0.8" -s prime_blob_enable="False" -s acceleration_travel_layer_0="500" -s support_interface_height="1" -s support_xy_distance="0.7" -s initial_layer_line_width_factor="100.0" -s infill_offset_y="0" -s roofing_angles="[ ]" -s mold_angle="40" -s support_tree_branch_diameter="2" -s material_maximum_park_duration="300" -s support_bottom_density="100" -s min_infill_area="0" -s wall_thickness="0.8" -s raft_base_line_width="0.8" -s cool_min_layer_time_fan_speed_max="5" -s speed_support_infill="15" -s ironing_enabled="False" -s retract_at_layer_change="False" -s speed_support_interface="10.0" -s wipe_hop_enable="False" -s raft_smoothing="5" -s wall_min_flow="0" -s infill_line_width="0.4" -s fill_outline_gaps="False" -s ironing_flow="10.0" -s raft_base_jerk="1" -s material_guid="0ff92885-617b-4144-a03c-9989872454bc" -s platform_adhesion="0" -s speed_print_layer_0="20" -s raft_interface_acceleration="1500" -s machine_endstop_positive_direction_x="False" -s wall_0_material_flow="100" -s acceleration_print="1500" -s material_adhesion_tendency="0" -s speed="0" -s material_end_of_filament_purge_length="20" -s max_skin_angle_for_expansion="90" -s minimum_interface_area="1.0" -s retraction_hop="1" -s material_flow_temp_graph="[[3.5,200],[7.0,240]]" -s travel="0" -s support_line_width="0.4" -s raft_interface_fan_speed="0" -s small_feature_max_length="0.0" -s filter_out_tiny_gaps="True" -s raft_surface_line_spacing="0.4" -s support_tree_branch_diameter_angle="5" -s material_flush_purge_speed="0.5" -s spaghetti_flow="20" -s support_skip_zag_per_mm="20" -s speed_infill="60" -s prime_tower_flow="100" -s raft_interface_thickness="0.44999999999999996" -s support_bottom_offset="0.0" -s machine_steps_per_mm_e="1600" -s mold_enabled="False" -s small_feature_speed_factor_0="50" -s acceleration_infill="1500" -s z_seam_x="155.5" -s raft_surface_speed="25.0" -s retraction_hop_enabled="False" -s support_xy_distance_overhang="0.2" -s raft_surface_thickness="0.3" -s support_bottom_stair_step_height="0.3" -s retraction_combing_max_distance="10" -s travel_avoid_supports="False" -s raft_margin="15" -s infill_enable_travel_optimization="True" -s machine_extruder_end_pos_y="0" -s jerk_print_layer_0="1" -s wipe_hop_amount="1" -s support_pattern="zigzag" -s machine_extruder_start_pos_x="0" -s machine_endstop_positive_direction_z="True" -s speed_prime_tower="50" -s wall_line_count="2" -s acceleration_ironing="1500" -s extruder_prime_pos_z="0" -s support_roof_enable="False" -s coasting_min_volume="0.8" -s support_line_distance="1.6" -s support_bottom_distance="0.25" -s machine_extruder_start_code="" -s wipe_pause="0" -s machine_nozzle_offset_y="0" -s bridge_skin_density_3="80" -s acceleration_layer_0="1500" -s travel_compensate_overlapping_walls_x_enabled="True" -s speed_wall_0="20" -s machine_extruder_cooling_fan_number="0" -s speed_wall="60" -s speed_equalize_flow_enabled="True" -s skirt_brim_material_flow="100" -s material_break_retracted_position="-50" -s retraction_retract_speed="50" -s extruder_prime_pos_x="0" -s zig_zaggify_support="False" -s support_bottom_stair_step_width="5.0" -s acceleration_support_bottom="1500" -s roofing_pattern="zigzag" -s brim_line_count="13" -s acceleration_support="1500" -s raft_jerk="1" -s gradual_infill_steps="0" -s mold_roof_height="0.5" -s line_width="0.4" -s top_bottom_pattern_0="zigzag" -s raft_interface_speed="18.75" -s infill_multiplier="1" -s material_flush_purge_length="60" -s center_object="False" -s wall_line_width="0.4" -s coasting_enable="False" -s material_final_print_temperature="230" -s infill_wipe_dist="0.1" -s jerk_prime_tower="1" -s support_material_flow="90" -s retraction_hop_after_extruder_switch_height="1" -s raft_base_thickness="0.24" -s jerk_infill="1" -s machine_nozzle_size="0.4" -s material_flow_layer_0="100" -s raft_base_line_spacing="1.6" -s support_initial_layer_line_distance="1.6" -s jerk_support_bottom="1" -s magic_fuzzy_skin_thickness="0.3" -s conical_overhang_enabled="False" -s speed_wall_x="40" -s magic_fuzzy_skin_enabled="False" -s infill_offset_x="0" -s zig_zaggify_infill="True" -s acceleration_topbottom="1500" -s connect_infill_polygons="False" -s wipe_brush_pos_x="100" -s machine_endstop_positive_direction_y="False" -s retraction_enable="True" -s skin_outline_count="1" -s brim_replaces_support="True" -s raft_airgap="0.3" -s cool_fan_speed_0="50" -s infill_before_walls="True" -s wipe_retraction_retract_speed="40" -s travel_avoid_distance="0.625" -s support_z_distance="0.1" -s expand_skins_expand_distance="0.8" -s wall_min_flow_retract="False" -s support_tree_branch_distance="1" -g -e0 -l "0" -s extruder_nr="0" -e0 -l "1" -s extruder_nr="0" -s anti_overhang_mesh="True" -e0 -l "2" -s extruder_nr="0" -s anti_overhang_mesh="True"
2020-04-28 14:25:22,310 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._onSlicingFinishedMessage [678]: Slicing took 1.685253620147705 seconds
2020-04-28 14:25:22,310 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._onSlicingFinishedMessage [679]: Number of models per buildplate: {0: 3}
2020-04-28 14:25:22,311 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._onSlicingFinishedMessage [693]: See if there is more to slice...
2020-04-28 14:25:22,312 - DEBUG - [Thread-10] CuraEngineBackend.ProcessSlicedLayersJob.run [70]: Processing new layer for build plate 0...
2020-04-28 14:25:22,315 - DEBUG - [MainThread] UM.Backend.Backend._logSocketState [192]: Socket state changed to Closing
2020-04-28 14:25:22,391 - DEBUG - [MainThread] UM.Backend.Backend._onSocketError [216]: Socket debug: Arcus Error (13): Closing socket because other side requested close.
2020-04-28 14:25:22,394 - DEBUG - [MainThread] UM.Backend.Backend._logSocketState [194]: Socket state changed to Closed
2020-04-28 14:25:22,400 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._onBackendQuit [844]: Backend quit with return code 0. Resetting process and socket.
2020-04-28 14:25:22,507 - DEBUG - [Thread-10] CuraEngineBackend.ProcessSlicedLayersJob.run [250]: Processing layers took 0.19185829162597656 seconds
2020-04-28 14:25:22,529 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._onProcessLayersFinished [874]: See if there is more to slice(2)...
2020-04-28 14:26:20,440 - DEBUG - [MainThread] cura.AutoSave._onTimeout [60]: Autosaving preferences, instances and profiles
2020-04-28 14:27:06,536 - DEBUG - [MainThread] RemovableDriveOutputDevice.RemovableDriveOutputDevice.requestWrite [83]: Writing to J:/CFFFP_e09b9a67-9dde-4ff0-98c1-b8407c85261e.gcode
2020-04-28 14:27:19,585 - ERROR - [MainThread] RemovableDriveOutputDevice.RemovableDriveOutputDevice.requestWrite [103]: Permission denied when trying to write to J:/CFFFP_e09b9a67-9dde-4ff0-98c1-b8407c85261e.gcode: [Errno 13] Permission denied: 'J:/CFFFP_e09b9a67-9dde-4ff0-98c1-b8407c85261e.gcode'
2020-04-28 14:27:19,603 - DEBUG - [MainThread] RemovableDriveOutputDevice.RemovableDriveOutputDevice.requestWrite [83]: Writing to J:/CFFFP_e09b9a67-9dde-4ff0-98c1-b8407c85261e.gcode
2020-04-28 14:27:20,244 - ERROR - [MainThread] RemovableDriveOutputDevice.RemovableDriveOutputDevice.requestWrite [103]: Permission denied when trying to write to J:/CFFFP_e09b9a67-9dde-4ff0-98c1-b8407c85261e.gcode: [Errno 13] Permission denied: 'J:/CFFFP_e09b9a67-9dde-4ff0-98c1-b8407c85261e.gcode'
2020-04-28 14:27:27,689 - DEBUG - [MainThread] RemovableDriveOutputDevice.RemovableDriveOutputDevice.requestWrite [83]: Writing to J:/CFFFP_e09b9a67-9dde-4ff0-98c1-b8407c85261e.gcode
2020-04-28 14:27:27,707 - DEBUG - [MainThread] SliceInfoPlugin.SliceInfo._onWriteStarted [109]: 'info/send_slice_info' is turned off.
2020-04-28 14:27:27,870 - WARNING - [Thread-11] UM.Decorators.deprecated_function [23]: <function GlobalStack.extruders at 0x000001F67C066488> is deprecated (since 4.4): Please use extruderList instead.
2020-04-28 14:27:27,976 - DEBUG - [Thread-11] UM.FileHandler.WriteFileJob.run [80]: Writing file took 0.26489734649658203 seconds
2020-04-28 14:27:30,100 - INFO - [MainThread] RemovableDriveOutputDevice.RemovableDrivePlugin.ejectDevice [44]: Attempting to eject the device
2020-04-28 14:27:30,101 - INFO - [MainThread] RemovableDriveOutputDevice.RemovableDrivePlugin.ejectDevice [51]: Succesfully ejected the device
2020-04-28 14:27:30,105 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [406]: file:///C:/Program Files/Ultimaker Cura 4.6/resources/qml/RoundedRectangle.qml:68: TypeError: Cannot read property of null
2020-04-28 15:03:44,309 - DEBUG - [MainThread] cura.TaskManagement.OnExitCallbackManager.addCallback [28]: on-app-exit callback [<bound method USBPrinterOutputDevice._checkActivePrintingUponAppExit of <USBPrinting.USBPrinterOutputDevice.USBPrinterOutputDevice object at 0x000001F60A4F0D38>>] added.
2020-04-28 15:03:44,310 - DEBUG - [Thread-12] USBPrinting.AutoDetectBaudJob.run [24]: Auto detect baud rate started.
2020-04-28 15:03:45,916 - DEBUG - [Thread-12] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 115200 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:03:50,420 - DEBUG - [Thread-12] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 250000 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:03:54,923 - DEBUG - [Thread-12] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 500000 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:03:59,427 - DEBUG - [Thread-12] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 230400 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:04:03,930 - DEBUG - [Thread-12] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 57600 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:04:08,434 - DEBUG - [Thread-12] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 38400 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:04:12,937 - DEBUG - [Thread-12] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 19200 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:04:17,441 - DEBUG - [Thread-12] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 9600 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:04:36,945 - DEBUG - [Thread-12] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 115200 works. Retry nr: 1. Wait timeout: 15
2020-04-28 15:04:56,951 - DEBUG - [Thread-12] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 250000 works. Retry nr: 1. Wait timeout: 15
2020-04-28 15:05:09,973 - ERROR - [Thread-12] UM.Logger.logException [106]: Exception: Job <USBPrinting.AutoDetectBaudJob.AutoDetectBaudJob object at 0x000001F60DDC6048> caused an exception
2020-04-28 15:05:09,976 - ERROR - [Thread-12] UM.Logger.logException [110]: Traceback (most recent call last):
2020-04-28 15:05:09,979 - ERROR - [Thread-12] UM.Logger.logException [110]:   File "X:\4.6-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 132, in run
2020-04-28 15:05:09,981 - ERROR - [Thread-12] UM.Logger.logException [110]:   File "C:\Program Files\Ultimaker Cura 4.6\plugins\USBPrinting\AutoDetectBaudJob.py", line 84, in run
2020-04-28 15:05:09,984 - ERROR - [Thread-12] UM.Logger.logException [110]:     serial.write(b"M105\n")
2020-04-28 15:05:09,987 - ERROR - [Thread-12] UM.Logger.logException [110]:   File "serial\serialwin32.py", line 315, in write
2020-04-28 15:05:09,989 - ERROR - [Thread-12] UM.Logger.logException [110]: serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'The device does not recognize the command.', None, 22))
2020-04-28 15:05:26,609 - DEBUG - [MainThread] cura.TaskManagement.OnExitCallbackManager.addCallback [28]: on-app-exit callback [<bound method USBPrinterOutputDevice._checkActivePrintingUponAppExit of <USBPrinting.USBPrinterOutputDevice.USBPrinterOutputDevice object at 0x000001F60F7FDAF8>>] added.
2020-04-28 15:05:26,610 - DEBUG - [Thread-1] USBPrinting.AutoDetectBaudJob.run [24]: Auto detect baud rate started.
2020-04-28 15:05:28,217 - DEBUG - [Thread-1] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 115200 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:05:32,720 - DEBUG - [Thread-1] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 250000 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:05:37,224 - DEBUG - [Thread-1] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 500000 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:05:41,727 - DEBUG - [Thread-1] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 230400 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:05:46,231 - DEBUG - [Thread-1] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 57600 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:05:50,734 - DEBUG - [Thread-1] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 38400 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:05:55,237 - DEBUG - [Thread-1] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM3 if baud rate 19200 works. Retry nr: 0. Wait timeout: 3
2020-04-28 15:05:56,175 - DEBUG - [MainThread] cura.TaskManagement.OnExitCallbackManager.triggerNextCallback [48]: Scheduled the next on-app-exit callback [<bound method USBPrinterOutputDevice._checkActivePrintingUponAppExit of <USBPrinting.USBPrinterOutputDevice.USBPrinterOutputDevice object at 0x000001F60A4F0D38>>]
2020-04-28 15:05:56,178 - DEBUG - [MainThread] cura.TaskManagement.OnExitCallbackManager.triggerNextCallback [48]: Scheduled the next on-app-exit callback [<bound method USBPrinterOutputDevice._checkActivePrintingUponAppExit of <USBPrinting.USBPrinterOutputDevice.USBPrinterOutputDevice object at 0x000001F60F7FDAF8>>]
2020-04-28 15:05:56,181 - DEBUG - [MainThread] cura.TaskManagement.OnExitCallbackManager.triggerNextCallback [51]: No more on-app-exit callbacks to process. Tell the app to exit.
2020-04-28 15:05:56,183 - INFO - [MainThread] cura.CuraApplication.closeApplication [577]: Close application
2020-04-28 15:05:56,190 - DEBUG - [MainThread] UM.Qt.QtApplication.windowClosed [470]: Shutting down cura
2020-04-28 15:05:56,324 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [304]: Attempting to kill the engine process
`

**Comment by GregValiant** [comment]
Is this still a problem in 5.12.1 or can this be closed?
