### ISSUE TITLE
I get white MONITOR tab

### ISSUE THREAD

**Issue by ChrisYOLO** [Ultimaker/Cura#7710]
Chris Rafths

**Application version**
(The version of the application this issue occurs with.)
 Latest (4.6.1)
**Platform**
Windows 10 Ryzen 2700X RTX 2070

**Printer**
I bought a printer from one of my friends. It's "motherboard" is bassed in reprap and it's called MKS Robin. But i was told to use Prusa i3 as a printer in Cura.

**Reproduction steps**
1. I connected the printer to my pc i couldn't find it so i downloaded CH340 drivers
2. I downloaded Cura and i configured 

**Screenshot(s)**
https://gyazo.com/d454a8ba86d8d193fb0b3e649dccf035

**Actual results**
still the same white moonitor screen 

**Expected results**
Getting it to work

**Project file**
i had no project i was trying to connect it...

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4595661/cura.log)

**Additional information**
The printer is brand new i was able to use it with other programms but i want to use it with Cura as its more stable please help i tried finding a solution but i couldn't find anything

**Comment by Ghostkeeper** [comment]
You get that white page when there is no connected printer. In your case, it seems that it had no connected printer because access to COM ports is denied by Windows:

```
2020-05-07 22:38:48,120 - DEBUG - [Thread-3] USBPrinting.AutoDetectBaudJob.run [50]: Checking COM7 if baud rate 500000 works. Retry nr: 0. Wait timeout: 3
2020-05-07 22:38:48,123 - WARNING - [Thread-3] UM.Logger.logException [106]: Exception: Unable to create serial
2020-05-07 22:38:48,127 - WARNING - [Thread-3] UM.Logger.logException [110]: Traceback (most recent call last):
2020-05-07 22:38:48,131 - WARNING - [Thread-3] UM.Logger.logException [110]:   File "C:\Program Files\Ultimaker Cura 4.6\plugins\USBPrinting\AutoDetectBaudJob.py", line 54, in run
2020-05-07 22:38:48,134 - WARNING - [Thread-3] UM.Logger.logException [110]:     serial = Serial(str(self._serial_port), baud_rate, timeout = read_timeout, writeTimeout = write_timeout)
2020-05-07 22:38:48,137 - WARNING - [Thread-3] UM.Logger.logException [110]:   File "serial\serialwin32.py", line 31, in __init__
2020-05-07 22:38:48,140 - WARNING - [Thread-3] UM.Logger.logException [110]:   File "serial\serialutil.py", line 240, in __init__
2020-05-07 22:38:48,144 - WARNING - [Thread-3] UM.Logger.logException [110]:   File "serial\serialwin32.py", line 62, in open
2020-05-07 22:38:48,147 - WARNING - [Thread-3] UM.Logger.logException [110]: serial.serialutil.SerialException: could not open port 'COM7': PermissionError(13, 'Access is denied.', None, 5)
```

Maybe something is occupying that COM port? Is there something else running that could be connecting to the printer? Maybe another instance of Cura, or a different slicer, Pronterface, etc?
