### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by EcoScan** [Ultimaker/Cura#831]
Version: 15.06.02
Platform: Windows-7-6.1.7601-SP1
Qt: 5.4.1
PyQt: 5.4.1

I use Beta version 15.06.03 as it allows me to really tailor the printing process to my products. Very happy so far until a bug showed up with commend below.
----------------------------------------------------------
Version: 15.06.02
Platform: Windows-7-6.1.7601-SP1
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 10, in <module>
  File "c:\dev\cura\cura\CuraApplication.py", line 176, in run
  File "c:\dev\uranium\UM\Application.py", line 246, in setActiveMachine
  File "c:\dev\uranium\UM\Signal.py", line 96, in emit
  File "c:\dev\cura\cura\CuraApplication.py", line 503, in _onActiveMachineChanged
  File "c:\dev\cura\cura\BuildVolume.py", line 142, in rebuild
TypeError: Can't convert 'float' object to str implicitly

--------------------------------------------------------------
I uninstalled and reinstalled but same keeps re-appearing also with version 15.06.02 and can't use Cura at moment. It suddenly happened when I was entering different line width.

Tried to install on friends computer (also running on W7) and here seems to work fine.

Please advise, any comments welcome

**Comment by fieldOfView** [comment]
15.06.03 is a *very* old version, which has many bugs. It evolved into Cura 2.1.
Please upgrade to Cura 2.1.2, which you can download here:
http://software.ultimaker.com
