### ISSUE TITLE
[1.2.3-Dremels Bundle] A fatal exception has occurred that we cannot recover from!

### ISSUE THREAD

**Issue by lenigma1** [Ultimaker/Cura#9082]
Version: 1.2.3
Platform: Windows-10-10.0.19041
Qt: 5.7.0
PyQt: 5.7

Exception:
Traceback (most recent call last):
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\Qt\Bindings\MainWindow.py", line 184, in _render
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\Qt\QtRenderer.py", line 138, in render
  File "C:\Program Files\Dremel DigiLab 3D Slicer\plugins\LayerView\LayerPass.py", line 95, in render
    batch.render(self._scene.getActiveCamera())
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\View\RenderBatch.py", line 215, in render
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\View\RenderBatch.py", line 255, in _renderItem
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\View\GL\OpenGL.py", line 251, in createIndexBuffer
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\Mesh\MeshData.py", line 218, in getIndicesAsByteArray
MemoryError

-------------------------
Thread 0x00001dcc (most recent call first):
  File "C:\Program Files\Dremel DigiLab 3D Slicer\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 87 in _updateThread
  File "c:\Python35\lib\threading.py", line 862 in run
  File "c:\Python35\lib\threading.py", line 914 in _bootstrap_inner
  File "c:\Python35\lib\threading.py", line 882 in _bootstrap

Thread 0x00001734 (most recent call first):
  File "c:\Python35\lib\threading.py", line 293 in wait
  File "c:\Python35\lib\threading.py", line 424 in acquire
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\JobQueue.py", line 86 in _nextJob
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\JobQueue.py", line 116 in run
  File "c:\Python35\lib\threading.py", line 914 in _bootstrap_inner
  File "c:\Python35\lib\threading.py", line 882 in _bootstrap

Thread 0x000016c8 (most recent call first):
  File "c:\Python35\lib\threading.py", line 293 in wait
  File "c:\Python35\lib\threading.py", line 424 in acquire
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\JobQueue.py", line 86 in _nextJob
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\JobQueue.py", line 116 in run
  File "c:\Python35\lib\threading.py", line 914 in _bootstrap_inner
  File "c:\Python35\lib\threading.py", line 882 in _bootstrap

Thread 0x000004d8 (most recent call first):
  File "c:\Python35\lib\threading.py", line 293 in wait
  File "c:\Python35\lib\threading.py", line 424 in acquire
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\JobQueue.py", line 86 in _nextJob
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\JobQueue.py", line 116 in run
  File "c:\Python35\lib\threading.py", line 914 in _bootstrap_inner
  File "c:\Python35\lib\threading.py", line 882 in _bootstrap

Thread 0x0000203c (most recent call first):
  File "c:\Python35\lib\threading.py", line 293 in wait
  File "c:\Python35\lib\threading.py", line 424 in acquire
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\JobQueue.py", line 86 in _nextJob
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/UM\JobQueue.py", line 116 in run
  File "c:\Python35\lib\threading.py", line 914 in _bootstrap_inner
  File "c:\Python35\lib\threading.py", line 882 in _bootstrap

Thread 0x00002e80 (most recent call first):
  File "c:\Python35\lib\threading.py", line 297 in wait
  File "c:\Python35\lib\site-packages\zeroconf.py", line 1569 in wait
  File "c:\Python35\lib\site-packages\zeroconf.py", line 1153 in run
  File "c:\Python35\lib\threading.py", line 914 in _bootstrap_inner
  File "c:\Python35\lib\threading.py", line 882 in _bootstrap

Thread 0x00002d54 (most recent call first):
  File "c:\Python35\lib\threading.py", line 297 in wait
  File "c:\Python35\lib\site-packages\zeroconf.py", line 1569 in wait
  File "c:\Python35\lib\site-packages\zeroconf.py", line 1017 in run
  File "c:\Python35\lib\threading.py", line 914 in _bootstrap_inner
  File "c:\Python35\lib\threading.py", line 882 in _bootstrap

Thread 0x0000251c (most recent call first):
  File "C:\Program Files\Dremel DigiLab 3D Slicer\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 58 in _updateThread
  File "c:\Python35\lib\threading.py", line 862 in run
  File "c:\Python35\lib\threading.py", line 914 in _bootstrap_inner
  File "c:\Python35\lib\threading.py", line 882 in _bootstrap

Thread 0x00000ab0 (most recent call first):
  File "c:\Python35\lib\threading.py", line 297 in wait
  File "c:\Python35\lib\site-packages\zeroconf.py", line 1569 in wait
  File "c:\Python35\lib\site-packages\zeroconf.py", line 1153 in run
  File "c:\Python35\lib\threading.py", line 914 in _bootstrap_inner
  File "c:\Python35\lib\threading.py", line 882 in _bootstrap

Thread 0x00002ef8 (most recent call first):
  File "c:\Python35\lib\threading.py", line 297 in wait
  File "c:\Python35\lib\site-packages\zeroconf.py", line 1569 in wait
  File "c:\Python35\lib\site-packages\zeroconf.py", line 1017 in run
  File "c:\Python35\lib\threading.py", line 914 in _bootstrap_inner
  File "c:\Python35\lib\threading.py", line 882 in _bootstrap

Thread 0x00001634 (most recent call first):
  File "c:\Python35\lib\threading.py", line 297 in wait
  File "c:\Python35\lib\site-packages\zeroconf.py", line 1569 in wait
  File "c:\Python35\lib\site-packages\zeroconf.py", line 1017 in run
  File "c:\Python35\lib\threading.py", line 914 in _bootstrap_inner
  File "c:\Python35\lib\threading.py", line 882 in _bootstrap

Current thread 0x00003244 (most recent call first):
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/cura\CrashHandler.py", line 100 in show
  File "C:/cura point three/cura-build/build/inst/bin/cura_app.py", line 45 in exceptHook
  File "C:/cura point three/cura-build/build/inst/lib/python3.5/site-packages/cura\CuraApplication.py", line 668 in run
  File "C:/cura point three/cura-build/build/inst/bin/cura_app.py", line 73 in <module>
  File "c:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26 in run
  File "c:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14 in run

Im unsure if this has to do with Windows not finding a driver for the 3D45?
But this is my very first crash in a year of running Dremels terribly outdated Cura software(I LOVE 4.8 guys! just wish it would see the printer...)

Im sorry if this is the incorrect format or protcol, as its my very first experience with GitHub as well!

**Comment by fvrmr** [comment]
This is something we don't maintain. Hope Dremel can help you with this.
