### ISSUE TITLE
Cura 4.9 keep crashing

### ISSUE THREAD

**Issue by bizzlerulez** [Ultimaker/Cura#9632]
Cura 4.9
Windows 10
Ender 5 pro

Cura keeps crashing when I try to open any file. Size don't mather

Error Traceback: `Traceback (most recent call last): File "C:\Users\Derya\AppData\Roaming\cura\4.9\plugins\CustomJobPrefix\CustomJobPrefix\PrintInformationPatches.py", line 120, in _triggerJobNameUpdate self._updateJobName() File "C:\Users\Derya\AppData\Roaming\cura\4.9\plugins\CustomJobPrefix\CustomJobPrefix\PrintInformationPatches.py", line 129, in _updateJobName base_name = self._print_information._stripAccents(self._print_information._base_name) AttributeError: 'PrintInformation' object has no attribute '_stripAccents'`
[cura.log](https://github.com/Ultimaker/Cura/files/6350363/cura.log)

Crash Log:
` Thread 0x00004ad0 (most recent call first):
File "C:\Program Files\Ultimaker Cura 4.9.0\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 87 in _updateThread
File "threading.py", line 870 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00005358 (most recent call first):
File "threading.py", line 306 in wait
File "zeroconf_init_.py", line 2117 in wait
File "zeroconf_init_.py", line 1434 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00002cc8 (most recent call first):
File "threading.py", line 306 in wait
File "threading.py", line 558 in wait
File "C:\Program Files\Ultimaker Cura 4.9.0\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 81 in _handleOnServiceChangedRequests
File "threading.py", line 870 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00003f08 (most recent call first):
File "threading.py", line 306 in wait
File "zeroconf_init_.py", line 2117 in wait
File "zeroconf_init_.py", line 1262 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x000026bc (most recent call first):
File "zeroconf_init_.py", line 1183 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00000f18 (most recent call first):
File "C:\Program Files\Ultimaker Cura 4.9.0\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
File "threading.py", line 870 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00003810 (most recent call first):
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Backend\Backend.py", line 165 in _storeStderrToLogThread
File "threading.py", line 870 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x000030ac (most recent call first):
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Backend\Backend.py", line 153 in _storeOutputToLogThread
File "threading.py", line 870 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x0000268c (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00002dc0 (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00001c9c (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00004b30 (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x0000249c (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00000960 (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00006688 (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00001608 (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x0000693c (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00005f5c (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x000065ac (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Thread 0x00007dfc (most recent call first):
File "threading.py", line 302 in wait
File "threading.py", line 433 in acquire
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
File "threading.py", line 932 in _bootstrap_inner
File "threading.py", line 890 in _bootstrap

Current thread 0x000050c8 (most recent call first):
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 396 in _logInfoWidget
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 182 in _createDialog
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 86 in init
File "X:\4.9-exe\build\inst\bin\cura_app.py", line 167 in exceptHook
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\UI\PrintInformation.py", line 253 in _calculateInformation
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\UI\PrintInformation.py", line 169 in _onPrintDurationMessage
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\UI\PrintInformation.py", line 428 in setToZeroPrintInformation
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\UI\PrintInformation.py", line 441 in _onSceneChanged
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in show
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 469 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1085 in event
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 383 in exec
File "X:\4.9-exe\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 862 in run
File "X:\4.9-exe\build\inst\bin\cura_app.py", line 241 in
File "Console.py", line 36 in run
File "startup.py", line 74 in run
`

**Comment by fieldOfView** [comment]
The crash is caused by the "Printjob Naming" plugin. It seems you have an older version of that plugin installed. Could you please check if there is an update for the plugin in the Marketplace? The latest version fixes this particular issue, and was published around a month ago.
