### ISSUE TITLE
Cura 4.9.1 ModuleNotFoundError: No module named 'UM.Qt.Bindings.FileProviderModel'

### ISSUE THREAD

**Issue by AlfredoSequeida** [Ultimaker/Cura#9859]
### Application Version

4.9.1

### Platform

Arch Linux

### Printer

None

### Reproduction steps

Open Cura. I am running Python 3.9.5, if that helps. This happens when installing the package using Pacman, however, the App image from the releases page works fine. 

### Actual results

```
/usr/lib/python3.9/site-packages/UM/PluginRegistry.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/lib/python3.9/site-packages/UM/Settings/InstanceContainer.py:53: DeprecationWarning: invalid escape sequence \d
  version_regex = re.compile("\nversion ?= ?(\d+)")
/usr/lib/python3.9/site-packages/UM/Settings/InstanceContainer.py:55: DeprecationWarning: invalid escape sequence \w
  type_regex = re.compile("\ntype ?= ?(\w+)")
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/cura/CuraApplication.py", line 34, in <module>
    from UM.Qt.Bindings.FileProviderModel import FileProviderModel
ModuleNotFoundError: No module named 'UM.Qt.Bindings.FileProviderModel'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/cura", line 195, in <module>
    from cura.CuraApplication import CuraApplication
  File "/usr/lib/python3.9/site-packages/cura/CuraApplication.py", line 34, in <module>
    from UM.Qt.Bindings.FileProviderModel import FileProviderModel
ModuleNotFoundError: No module named 'UM.Qt.Bindings.FileProviderModel'
```

### Expected results

Cura should open

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No crash log was created.

**Comment by fvrmr** [comment]
Hi @AlfredoSequeida thank you for your report.
But we don't maintain the package Packman, only the AppImage. So please report this issue to the maintainer of this package. 
I will close this issue since this is not a problem with the AppImage of Cura.
Hope you understand.
