### ISSUE TITLE
The plug-in could not find the package installed in the working directory

### ISSUE THREAD

**Issue by frank-pian** [Ultimaker/Cura#9923]
### Application Version

4.8

### Platform

windows10

### Printer

CR-10

### Reproduction steps

I'm a Cura plugins developer. I want to add a third party Python package to the plug-in working directory. But booting from cura_app.py does not find the package.

1. Copy the package to the plug-in working directory.
![图片](https://user-images.githubusercontent.com/8214804/120053799-cdf86900-c05e-11eb-9a8e-e72cd65f85f9.png)

2. Added to the sys.Path

```
import os, sys
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "crcmod"))
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "Crypto"))
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "aliyunsdkcore"))
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "aliyunsdkkms"))
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "oss2"))
print(sys.path)
from oss2 import SizedFileAdapter, determine_part_size, headers
from oss2.models import PartInfo
import oss2
```

3. Run cura_app.py

### Actual results

No module named 'oss2'

### Expected results

The Python package is imported normally

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Could not find plugin CrealityCloud
['E:\\cura-dev\\ultimaker\\uranium', 'E:\\cura-dev\\ultimaker\\cura', 'E:\\Cura\\Uranium', 'e:\\cura-install\\bin\\python35.zip', 'e:\\cura-install\\DLLs', 'e:\\cura-install\\lib', 'e:\\cura-install\\bin', 'C:\\Users\\106016\\AppData\\Roaming\\Python\\Python35\\site-packages', 'e:\\cura-install', 'e:\\cura-install\\lib\\site-packages', 'E:\\cura-dev\\ultimaker\\cura\\plugins\\CrealityCloud\\crcmod', 'E:\\cura-dev\\ultimaker\\cura\\plugins\\CrealityCloud\\Crypto', 'E:\\cura-dev\\ultimaker\\cura\\plugins\\CrealityCloud\\aliyunsdkkms', 'E:\\cura-dev\\ultimaker\\cura\\plugins\\CrealityCloud\\aliyunsdkkms', 'E:\\cura-dev\\ultimaker\\cura\\plugins\\CrealityCloud\\oss2', 'E:\\cura-dev\\ultimaker\\cura\\plugins\\CrealityCloud\\crcmod', 'E:\\cura-dev\\ultimaker\\cura\\plugins\\CrealityCloud\\Crypto', 'E:\\cura-dev\\ultimaker\\cura\\plugins\\CrealityCloud\\aliyunsdkkms', 'E:\\cura-dev\\ultimaker\\cura\\plugins\\CrealityCloud\\aliyunsdkkms', 'E:\\cura-dev\\ultimaker\\cura\\plugins\\CrealityCloud\\oss2']
2021-05-29 09:14:41,443 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]: Exception: Import error loading module CrealityCloud
2021-05-29 09:14:41,444 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]: Traceback (most recent call last):
2021-05-29 09:14:41,445 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:   File "E:\cura-dev\ultimaker\uranium\UM\PluginRegistry.py", line 677, in _findPlugin
2021-05-29 09:14:41,447 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:     module = imp.load_module(plugin_id, file, path, desc) #type: ignore #MyPy gets the wrong output type from imp.find_module for some reason.
2021-05-29 09:14:41,448 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:   File "e:\cura-install\lib\imp.py", line 245, in load_module
2021-05-29 09:14:41,449 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:     return load_package(name, filename)
2021-05-29 09:14:41,450 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:   File "e:\cura-install\lib\imp.py", line 217, in load_package
2021-05-29 09:14:41,451 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:     return _load(spec)
2021-05-29 09:14:41,452 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:   File "<frozen importlib._bootstrap>", line 693, in _load
2021-05-29 09:14:41,453 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
2021-05-29 09:14:41,453 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:   File "<frozen importlib._bootstrap_external>", line 697, in exec_module
2021-05-29 09:14:41,454 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2021-05-29 09:14:41,455 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:   File "E:\cura-dev\ultimaker\cura\plugins\CrealityCloud\__init__.py", line 4, in <module>
2021-05-29 09:14:41,456 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:     from . import CrealityCloudOutputDevicePlugin
2021-05-29 09:14:41,457 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:   File "E:\cura-dev\ultimaker\cura\plugins\CrealityCloud\CrealityCloudOutputDevicePlugin.py", line 3, in <module>
2021-05-29 09:14:41,458 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:     from .CrealityCloudOutputDevice import CrealityCloudOutputDevice
2021-05-29 09:14:41,459 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:   File "E:\cura-dev\ultimaker\cura\plugins\CrealityCloud\CrealityCloudOutputDevice.py", line 2, in <module>
2021-05-29 09:14:41,460 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:     from . CrealityCloudUtils import CrealityCloudUtils
2021-05-29 09:14:41,461 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:   File "E:\cura-dev\ultimaker\cura\plugins\CrealityCloud\CrealityCloudUtils.py", line 18, in <module>
2021-05-29 09:14:41,462 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]:     from oss2 import SizedFileAdapter, determine_part_size, headers
2021-05-29 09:14:41,462 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [679]: ImportError: No module named 'oss2'

**Comment by Ghostkeeper** [comment]
Cura explicitly forbids loading packages from the working directory:

https://github.com/Ultimaker/Cura/blob/2464f64129b26c4d35c1af07aca9bf55864277f1/cura_app.py#L6-L13

Allowing this would be a security problem. A hacker could place executable Python packages in the working directory, since he doesn't need administrative access to modify files there (depending on what the working directory is). Those packages could get loaded before the real packages that Cura needs get loaded. As Cura calls upon functions from those packages, the hacker could execute code on the user's local machine with Cura's permission.
